Repository kiegroup/kie-cloud-operator, pull requests merged in 2019-02, with the labels that each got.

#60 [KIECLOUD-102] Support DM deployments
  config/common.yaml
  config/envs/rhdm-authoring-ha.yaml
  config/envs/rhdm-authoring.yaml
  config/envs/rhdm-optaweb-trial.yaml
  config/envs/rhdm-production-immutable.yaml
  config/envs/rhdm-trial.yaml
  config/envs/rhpam-authoring-ha.yaml
  config/envs/rhpam-authoring.yaml
  config/envs/rhpam-production-immutable.yaml
  config/envs/rhpam-production.yaml
  config/envs/rhpam-trial.yaml
  deploy/catalog_resources/kiecloud-operator.v0.1.0.clusterserviceversion.yaml
  deploy/crds/kieapp.crd.yaml
  deploy/crs/kieapp_authoring-ha.yaml
  deploy/crs/kieapp_rhdm_authoring-ha.yaml
  deploy/crs/kieapp_rhdm_authoring.yaml
  deploy/crs/kieapp_rhdm_optaweb-trial.yaml
  deploy/crs/kieapp_rhdm_production-immutable.yaml
  deploy/crs/kieapp_rhdm_trial.yaml
  deploy/crs/kieapp_rhpam_authoring-ha.yaml
  deploy/crs/kieapp_rhpam_authoring.yaml
  deploy/crs/kieapp_rhpam_production-immutable.yaml
  deploy/crs/kieapp_rhpam_production.yaml
  deploy/crs/kieapp_rhpam_trial.yaml
  pkg/apis/app/v1/kieapp_types.go
  pkg/apis/app/v1/zz_generated.deepcopy.go
  pkg/controller/kieapp/constants/constants.go
  pkg/controller/kieapp/defaults/auth_test.go
  pkg/controller/kieapp/defaults/defaults.go
  pkg/controller/kieapp/defaults/defaults_test.go
  pkg/controller/kieapp/defaults/merge.go
  pkg/controller/kieapp/defaults/merge_test.go
  pkg/controller/kieapp/kieapp_controller.go
  pkg/controller/kieapp/kieapp_controller_test.go
  pkg/controller/kieapp/test/crd_validation_test.go
  pkg/controller/kieapp/test/mock_imagestreamtag.go
  pkg/controller/kieapp/test/mock_service.go
Labels: approved, lgtm, size/XXL

#61 [KIECLOUD-106] operator version annotation in CR & set image reference policy
  README.md
  pkg/controller/kieapp/kieapp_controller.go
Labels: lgtm, size/S

#62 [KIECLOUD-113] 7.3 changes
  config/common.yaml
  deploy/catalog_resources/kiecloud-operator.v0.1.0.clusterserviceversion.yaml
  deploy/operator.yaml
  pkg/controller/kieapp/constants/constants.go
  pkg/controller/kieapp/defaults/defaults_test.go
  pkg/controller/kieapp/kieapp_controller.go
  pkg/controller/kieapp/kieapp_controller_test.go
Labels: approved, lgtm, size/L

#64 [KIECLOUD-118] Use icon-processerver
  deploy/catalog_resources/kiecloud-operator.v0.1.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#65 [KIECLOUD-115] cekit for rhel builds
  .gitignore
  Makefile
  README.md
  build/Dockerfile.rhel
  container.yaml
  hack/go-build.sh
  image.yaml
  modules/business-automation-operator/install
  modules/business-automation-operator/module.yaml
Labels: approved, lgtm, size/M

#66 [KIECLOUD-124] crd validation fixes
  deploy/crds/kieapp.crd.yaml
  pkg/apis/app/v1/kieapp_types.go
  pkg/controller/kieapp/defaults/auth_test.go
  pkg/controller/kieapp/test/crd_validation_test.go
Labels: approved, lgtm, size/S

#67 [KIECLOUD-125] add application label to objects
  config/common.yaml
  config/envs/rhdm-authoring-ha.yaml
  config/envs/rhdm-optaweb-trial.yaml
  config/envs/rhdm-production-immutable.yaml
  config/envs/rhdm-trial.yaml
  config/envs/rhpam-authoring-ha.yaml
  config/envs/rhpam-authoring.yaml
  config/envs/rhpam-production-immutable.yaml
  config/envs/rhpam-production.yaml
  config/envs/rhpam-trial.yaml
  pkg/controller/kieapp/kieapp_controller.go
Labels: approved, lgtm, size/M

#68 [KIECLOUD-128] set default server object in CR
  pkg/controller/kieapp/defaults/defaults.go
  pkg/controller/kieapp/defaults/defaults_test.go
Labels: approved, lgtm, size/M

#70 [KIECLOUD-115] osbs changes
  container.yaml
  hack/go-build.sh
  image.yaml
  modules/business-automation-operator/install
  modules/kie-cloud-operator/install
  modules/kie-cloud-operator/module.yaml
Labels: approved, lgtm, size/M

#73 [KIECLOUD-132] role fixes for manual deployment
  deploy/role.yaml
Labels: approved, lgtm, size/S

#72 [KIECLOUD-131] imageRegistry validation
  deploy/crds/kieapp.crd.yaml
  deploy/examples/image_registry.yaml
Labels: approved, lgtm, size/S

#75 [KIECLOUD-133] add cekit flag so image properly tagged after build
  Makefile
  README.md
  hack/go-build.sh
  image.yaml
Labels: approved, lgtm, size/S

#77 bundle file generation for OperatorHub
  deploy/catalog_resources/redhat/bundle.1.0.0.yaml
  hack/catalog-redhat.sh
Labels: approved, lgtm, size/XL

#78 bundle shell script mod
  hack/catalog-redhat.sh
Labels: approved, lgtm, size/XS

#79 [KIECLOUD-115] build improvements
  Makefile
  README.md
  hack/go-build.sh
  image.yaml
  modules/kie-cloud-operator/install
Labels: approved, lgtm, size/M

#82 Update icon to BRMS
  deploy/catalog_resources/community/kiecloud-operator.v1.0.0.clusterserviceversion.yaml
  deploy/catalog_resources/redhat/bundle.1.0.0.yaml
  deploy/catalog_resources/redhat/businessautomation-operator.v1.0.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#81 [1.0] [RHDM-861] Adjust Decision central probe URL
  pkg/controller/kieapp/constants/constants.go
  pkg/controller/kieapp/defaults/defaults_test.go
Labels: approved, lgtm, needs-ok-to-test, size/XS

#84 add tchughesiv to approvers
  OWNERS
Labels: approved, lgtm, size/XS

#80 [RHDM-861] Adjust Decision central probe URL
  pkg/controller/kieapp/constants/constants.go
  pkg/controller/kieapp/defaults/defaults_test.go
Labels: approved, lgtm, ok-to-test, size/XS
