Repository kiegroup/kie-cloud-operator, pull requests merged in 2019-12, with the labels that each got.

#315 fix past micro imagetag
  pkg/controller/kieapp/constants/constants.go
Labels: approved, lgtm, release-1.3.0, size/XS

#316 Merge branch 'master' into release-v1.3.x
  pkg/controller/kieapp/constants/constants.go
Labels: approved, lgtm, release-1.3.0, size/XS

#317 7.6.1 / 1.3.1 version
  config/7.6.1/common.yaml
  config/7.6.1/dbs/external.yaml
  config/7.6.1/dbs/h2.yaml
  config/7.6.1/dbs/mysql.yaml
  config/7.6.1/dbs/postgresql.yaml
  config/7.6.1/envs/rhdm-authoring-ha.yaml
  config/7.6.1/envs/rhdm-authoring.yaml
  config/7.6.1/envs/rhdm-production-immutable.yaml
  config/7.6.1/envs/rhdm-trial.yaml
  config/7.6.1/envs/rhpam-authoring-ha.yaml
  config/7.6.1/envs/rhpam-authoring.yaml
  config/7.6.1/envs/rhpam-production-immutable.yaml
  config/7.6.1/envs/rhpam-production.yaml
  config/7.6.1/envs/rhpam-trial.yaml
  config/7.6.1/jms/activemq-jms-config.yaml
  deploy/catalog_resources/community/1.3.1/kieapp.crd.yaml
  deploy/catalog_resources/community/1.3.1/kiecloud-operator.1.3.1.clusterserviceversion.yaml
  deploy/catalog_resources/community/kiecloud.package.yaml
  deploy/catalog_resources/redhat/1.3.1/businessautomation-operator.1.3.1.clusterserviceversion.yaml
  deploy/catalog_resources/redhat/1.3.1/kieapp.crd.yaml
  deploy/catalog_resources/redhat/businessautomation.package.yaml
  deploy/operator.yaml
  pkg/apis/app/v2/kieapp_types.go
  pkg/controller/kieapp/constants/constants.go
  pkg/controller/kieapp/defaults/defaults.go
  pkg/controller/kieapp/defaults/defaults_test.go
  tools/csv-gen/csv-gen.go
  version/version.go
Labels: approved, lgtm, release-1.3.1, size/XL

#318 [RHPAM-2550] fix expose metrics issue
  deploy/catalog_resources/community/1.3.0/kiecloud-operator.1.3.0.clusterserviceversion.yaml
  deploy/catalog_resources/redhat/1.3.0/businessautomation-operator.1.3.0.clusterserviceversion.yaml
  deploy/role.yaml
  pkg/components/components.go
Labels: approved, lgtm, release-1.3.0, size/M

#319 [RHPAM-2550] cherry-picked - fix expose metrics issue
  deploy/catalog_resources/community/1.3.0/kiecloud-operator.1.3.0.clusterserviceversion.yaml
  deploy/catalog_resources/community/1.3.1/kiecloud-operator.1.3.1.clusterserviceversion.yaml
  deploy/catalog_resources/redhat/1.3.0/businessautomation-operator.1.3.0.clusterserviceversion.yaml
  deploy/catalog_resources/redhat/1.3.1/businessautomation-operator.1.3.1.clusterserviceversion.yaml
  deploy/role.yaml
  pkg/components/components.go
Labels: approved, lgtm, release-1.3.1, size/M

#322 use container-first go modules for OSBS
  image.yaml
Labels: approved, lgtm, release-1.3.1, size/XS

#323 use container-first go modules for OSBS
  image.yaml
Labels: approved, lgtm, release-1.3.0, size/XS

#327 [RHPAM-2602] fix configmap difference errors during 1.3.0 upgrades
  config/7.5.0/common.yaml
  config/7.5.1/common.yaml
  deploy/catalog_resources/community/1.3.0/kiecloud-operator.1.3.0.clusterserviceversion.yaml
  deploy/catalog_resources/redhat/1.3.0/businessautomation-operator.1.3.0.clusterserviceversion.yaml
  deploy/role.yaml
Labels: approved, release-1.3.0, size/L

#328 [RHPAM-2602] fix configmap difference errors during 1.3.1 upgrades
  config/7.5.1/common.yaml
  deploy/catalog_resources/community/1.3.0/kiecloud-operator.1.3.0.clusterserviceversion.yaml
  deploy/catalog_resources/community/1.3.1/kiecloud-operator.1.3.1.clusterserviceversion.yaml
  deploy/catalog_resources/redhat/1.3.0/businessautomation-operator.1.3.0.clusterserviceversion.yaml
  deploy/catalog_resources/redhat/1.3.1/businessautomation-operator.1.3.1.clusterserviceversion.yaml
  deploy/role.yaml
Labels: approved, release-1.3.1, size/XL

#329 [RHPAM-2401-1] - QE review, db is not ba component
  config/7.6.0/dbs/postgresql.yaml
  pkg/controller/kieapp/defaults/merge_test.go
Labels: approved, lgtm, release-1.3.0, size/XS

#332 [RHPAM-2209] Fix failing scenarios
  pkg/controller/kieapp/defaults/auth.go
  pkg/controller/kieapp/defaults/auth_test.go
  pkg/controller/kieapp/kieapp_controller.go
  pkg/controller/kieapp/kieapp_controller_test.go
Labels: approved, lgtm, release-1.3.1, size/S

#326 [RHPAM-2401-1] - QE review, db is not ba component
  config/7.6.0/dbs/postgresql.yaml
  config/7.6.1/dbs/postgresql.yaml
  pkg/controller/kieapp/defaults/merge_test.go
Labels: approved, lgtm, release-1.3.1, size/S

#333 [RHPAM-2431] - Busybox dependency in Kieserver DeploymentConfig
  config/7.6.0/dbs/mysql.yaml
  config/7.6.0/dbs/postgresql.yaml
  config/7.6.1/dbs/mysql.yaml
  config/7.6.1/dbs/postgresql.yaml
Labels: approved, lgtm, ok-to-test, release-1.3.1, size/S

#335 [RHPAM-2431] - Busybox dependency in Kieserver DeploymentConfig
  config/7.6.0/dbs/mysql.yaml
  config/7.6.0/dbs/postgresql.yaml
Labels: approved, lgtm, release-1.3.0, size/S
