Repository kiegroup/kie-cloud-operator, pull requests merged in 2019-04, with the labels that each got.

#111 [KIECLOUD-174] new password fields for configuring DBs and AMQ
  config/dbs/h2.yaml
  config/dbs/mysql.yaml
  config/dbs/postgresql.yaml
  config/envs/rhdm-authoring-ha.yaml
  config/envs/rhpam-authoring-ha.yaml
  deploy/catalog_resources/redhat/catalog-source.yaml
  deploy/crds/kieapp.crd.yaml
  pkg/apis/app/v1/kieapp_types.go
  pkg/controller/kieapp/defaults/defaults.go
  pkg/controller/kieapp/defaults/defaults_test.go
Labels: approved, lgtm, size/L

#112 [RHPAM-1952] resolve kie server sticky session issue
  config/common.yaml
  config/dbs/h2.yaml
  config/envs/rhdm-trial.yaml
  config/envs/rhpam-trial.yaml
  pkg/controller/kieapp/defaults/defaults_test.go
Labels: approved, lgtm, size/XS

#113 minimal update for important vulnerabilities during rhel build
  modules/kie-cloud-operator/install
Labels: approved, lgtm, size/XS

#114 check for openshift cluster before watching objects
  Gopkg.lock
  Gopkg.toml
  cmd/manager/main.go
  vendor/github.com/RHsyseng/operator-utils/.gitignore
  vendor/github.com/RHsyseng/operator-utils/Gopkg.lock
  vendor/github.com/RHsyseng/operator-utils/Gopkg.toml
  vendor/github.com/RHsyseng/operator-utils/LICENSE
  vendor/github.com/RHsyseng/operator-utils/Makefile
  vendor/github.com/RHsyseng/operator-utils/README.md
  vendor/github.com/RHsyseng/operator-utils/pkg/utils/openshift/utils.go
  vendor/github.com/RHsyseng/operator-utils/version/version.go
Labels: approved, lgtm, size/XL

#115 add simplify to go fmt
  hack/go-fmt.sh
  pkg/controller/kieapp/constants/constants.go
Labels: approved, lgtm, size/S

#116 Moved schema validation logic to operator library
  Gopkg.lock
  Gopkg.toml
  pkg/controller/kieapp/test/crd_validation_test.go
  vendor/github.com/RHsyseng/operator-utils/.travis.yml
  vendor/github.com/RHsyseng/operator-utils/Gopkg.lock
  vendor/github.com/RHsyseng/operator-utils/README.md
  vendor/github.com/RHsyseng/operator-utils/pkg/validation/schema.go
Labels: approved, lgtm, size/L

#117 Use operator-utils to verify that CRD is complete
  Gopkg.lock
  deploy/catalog_resources/redhat/catalog-source.yaml
  deploy/crds/kieapp.crd.yaml
  pkg/apis/app/v1/kieapp_types.go
  pkg/controller/kieapp/test/crd_validation_test.go
  vendor/github.com/RHsyseng/operator-utils/Gopkg.lock
  vendor/github.com/RHsyseng/operator-utils/pkg/validation/schema.go
  vendor/github.com/RHsyseng/operator-utils/pkg/validation/schema_sync.go
  vendor/github.com/RHsyseng/operator-utils/pkg/validation/schema_sync_test.go
  vendor/github.com/RHsyseng/operator-utils/pkg/validation/schema_test.go
Labels: approved, lgtm, size/XL

#118 OperatorSource and supporting files
  README.md
  deploy/catalog_resources/community/kiecloud-operator.1.0.0.clusterserviceversion.yaml
  deploy/catalog_resources/community/kiecloud.package.yaml
  deploy/catalog_resources/courier/bundle_dir/kieapp.crd.yaml
  deploy/catalog_resources/courier/bundle_dir/kiecloud-operator.1.0.0.clusterserviceversion.yaml
  deploy/catalog_resources/courier/bundle_dir/kiecloud.package.yaml
  deploy/catalog_resources/courier/kiecloud-operatorsource.yaml
  deploy/catalog_resources/redhat/businessautomation-operator.1.0.0.clusterserviceversion.yaml
  deploy/catalog_resources/redhat/businessautomation.package.yaml
  deploy/catalog_resources/redhat/catalog-source.yaml
  hack/catalog-source.sh
  hack/catalog.sh
Labels: approved, lgtm, size/M

#120 fix rhel build
  image.yaml
  modules/kie-cloud-operator/install
Labels: approved, lgtm, ok-to-test, size/XS

#121 [KIECLOUD-164] - Update the operator probes to match the new probes
  Gopkg.lock
  config/common.yaml
  hack/catalog-redhat.sh
  hack/catalog.sh
  pkg/apis/app/v1/kieapp_types.go
  pkg/controller/kieapp/constants/constants.go
  pkg/controller/kieapp/defaults/defaults.go
  pkg/controller/kieapp/defaults/defaults_test.go
Labels: approved, lgtm, ok-to-test, size/M

#122 increment image tag for PAM/DM 7.3.1
  pkg/controller/kieapp/constants/constants.go
Labels: approved, size/XS

#123 increment version 1.0.1 for 7.3.1
  image.yaml
  version/version.go
Labels: approved, lgtm, size/XS

#124 Revert "[KIECLOUD-164] - Update the operator probes to match the new probes"
  Gopkg.lock
  config/common.yaml
  hack/catalog-redhat.sh
  hack/catalog.sh
  pkg/apis/app/v1/kieapp_types.go
  pkg/controller/kieapp/constants/constants.go
  pkg/controller/kieapp/defaults/defaults.go
  pkg/controller/kieapp/defaults/defaults_test.go
Labels: approved, lgtm, size/M

#125 increment version 1.0.1 for 7.3.1
  .gitignore
  hack/go-build.sh
  image.yaml
  pkg/controller/kieapp/constants/constants.go
  version/version.go
Labels: approved, lgtm, size/S

#126 cherry-pick 1.0.1 & rhel build fixes
  .gitignore
  hack/go-build.sh
  image.yaml
  modules/kie-cloud-operator/install
Labels: approved, size/S

#127 1.0.1 OLM fixes
  deploy/catalog_resources/community/kiecloud-operator.1.0.1.clusterserviceversion.yaml
  deploy/catalog_resources/community/kiecloud.package.yaml
  deploy/catalog_resources/redhat/businessautomation-operator.1.0.1.clusterserviceversion.yaml
  deploy/catalog_resources/redhat/businessautomation.1.0.0.package.yaml
  deploy/catalog_resources/redhat/businessautomation.1.0.1.package.yaml
  deploy/catalog_resources/redhat/catalog-source.yaml
  hack/catalog-redhat.sh
  hack/catalog-source.sh
  hack/catalog.sh
Labels: approved, lgtm, size/L

#130 admin user field
  config/common.yaml
  deploy/catalog_resources/redhat/catalog-source.yaml
  deploy/crds/kieapp.crd.yaml
  pkg/apis/app/v1/kieapp_types.go
  pkg/controller/kieapp/constants/constants.go
  pkg/controller/kieapp/defaults/defaults.go
  pkg/controller/kieapp/defaults/defaults_test.go
Labels: approved, lgtm, size/M

#131 enhancements for Operators Manifests Push Service (OMPS)
  README.md
  deploy/catalog_resources/community/1.0.1/kiecloud-operator.1.0.1.clusterserviceversion.yaml
  deploy/catalog_resources/community/1.0.1/kiecloud.1.0.1.package.yaml
  deploy/catalog_resources/community/kiecloud.package.yaml
  deploy/catalog_resources/courier/bundle_dir/1.0.1/kieapp.crd.yaml
  deploy/catalog_resources/courier/bundle_dir/1.0.1/kiecloud-operator.1.0.1.clusterserviceversion.yaml
  deploy/catalog_resources/courier/bundle_dir/1.0.1/kiecloud.1.0.1.package.yaml
  deploy/catalog_resources/courier/bundle_dir/kieapp.crd.yaml
  deploy/catalog_resources/courier/bundle_dir/kiecloud-operator.1.0.0.clusterserviceversion.yaml
  deploy/catalog_resources/courier/bundle_dir/kiecloud.package.yaml
  deploy/catalog_resources/redhat/1.0.0/businessautomation-operator.1.0.0.clusterserviceversion.yaml
  deploy/catalog_resources/redhat/1.0.0/businessautomation.1.0.0.package.yaml
  deploy/catalog_resources/redhat/1.0.1/businessautomation-operator.1.0.1.clusterserviceversion.yaml
  deploy/catalog_resources/redhat/1.0.1/businessautomation.1.0.1.package.yaml
  deploy/catalog_resources/redhat/businessautomation.1.0.0.package.yaml
  deploy/catalog_resources/redhat/businessautomation.1.0.1.package.yaml
  deploy/catalog_resources/redhat/catalog-source.yaml
  hack/catalog-source.sh
  hack/catalog.sh
  image.yaml
  modules/kie-cloud-operator/install
Labels: approved, lgtm, size/M

#132 cherry-pick omps enhancements into 1.0.x
  deploy/catalog_resources/community/1.0.1/kiecloud-operator.1.0.1.clusterserviceversion.yaml
  deploy/catalog_resources/community/1.0.1/kiecloud.1.0.1.package.yaml
  deploy/catalog_resources/community/kiecloud.package.yaml
  deploy/catalog_resources/courier/bundle_dir/1.0.1/kieapp.crd.yaml
  deploy/catalog_resources/courier/bundle_dir/1.0.1/kiecloud-operator.1.0.1.clusterserviceversion.yaml
  deploy/catalog_resources/courier/bundle_dir/1.0.1/kiecloud.1.0.1.package.yaml
  deploy/catalog_resources/redhat/1.0.0/businessautomation-operator.1.0.0.clusterserviceversion.yaml
  deploy/catalog_resources/redhat/1.0.0/businessautomation.1.0.0.package.yaml
  deploy/catalog_resources/redhat/1.0.1/businessautomation-operator.1.0.1.clusterserviceversion.yaml
  deploy/catalog_resources/redhat/1.0.1/businessautomation.1.0.1.package.yaml
  deploy/catalog_resources/redhat/businessautomation.1.0.0.package.yaml
  deploy/catalog_resources/redhat/businessautomation.1.0.1.package.yaml
  deploy/catalog_resources/redhat/catalog-source.yaml
  hack/catalog-source.sh
  hack/catalog.sh
  image.yaml
  modules/kie-cloud-operator/install
Labels: approved, lgtm, size/M

#129 version 1.1 / 7.4
  README.md
  deploy/catalog_resources/community/1.1.0/kiecloud-operator.1.1.0.clusterserviceversion.yaml
  deploy/catalog_resources/community/1.1.0/kiecloud.1.1.0.package.yaml
  deploy/catalog_resources/courier/bundle_dir/1.0.1/kieapp.1.0.crd.yaml
  deploy/catalog_resources/courier/bundle_dir/1.1.0/kieapp.crd.yaml
  deploy/catalog_resources/courier/bundle_dir/1.1.0/kiecloud-operator.1.1.0.clusterserviceversion.yaml
  deploy/catalog_resources/courier/bundle_dir/1.1.0/kiecloud.1.1.0.package.yaml
  deploy/catalog_resources/redhat/1.1.0/businessautomation-operator.1.1.0.clusterserviceversion.yaml
  deploy/catalog_resources/redhat/1.1.0/businessautomation.1.1.0.package.yaml
  deploy/catalog_resources/redhat/catalog-source.yaml
  deploy/crds/kieapp.1.0.crd.yaml
  deploy/operator.yaml
  hack/catalog-redhat.sh
  hack/catalog-source.sh
  hack/catalog.sh
  hack/go-build.sh
  hack/go-test.sh
  image.yaml
  pkg/controller/kieapp/constants/constants.go
  version/version.go
Labels: approved, lgtm, size/XXL

#133 [JBPM-8150] Allow users to change Kie server id in Deployment config
  config/common.yaml
  deploy/crds/kieapp.crd.yaml
  deploy/examples/openshift_startup.yaml
  deploy/examples/server_config.yaml
  pkg/apis/app/v1/kieapp_types.go
  pkg/controller/kieapp/constants/constants.go
  pkg/controller/kieapp/defaults/defaults.go
  pkg/controller/kieapp/defaults/defaults_test.go
  pkg/controller/kieapp/kieapp_controller.go
  pkg/controller/kieapp/watch.go
Labels: approved, lgtm, size/L

#138 [KIECLOUD-190] KIE Server needs to respect configured imageTag
  deploy/catalog_resources/courier/kiecloud-operatorsource.yaml
  pkg/controller/kieapp/defaults/defaults.go
  pkg/controller/kieapp/defaults/defaults_test.go
Labels: approved, lgtm, size/M

#139 metadata improvements
  deploy/catalog_resources/community/1.0.1/kiecloud-operator.1.0.1.clusterserviceversion.yaml
  deploy/catalog_resources/community/1.1.0/kiecloud-operator.1.1.0.clusterserviceversion.yaml
  deploy/catalog_resources/redhat/1.0.1/businessautomation-operator.1.0.1.clusterserviceversion.yaml
  deploy/catalog_resources/redhat/1.1.0/businessautomation-operator.1.1.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/M

#136 [KIECLOUD-190] KIE Server needs to respect configured imageTag
  pkg/controller/kieapp/defaults/defaults.go
  pkg/controller/kieapp/defaults/defaults_test.go
Labels: approved, lgtm, size/M

#141 [KIECLOUD-193] Update CSV installModes
  deploy/catalog_resources/community/1.0.1/kiecloud-operator.1.0.1.clusterserviceversion.yaml
  deploy/catalog_resources/community/1.1.0/kiecloud-operator.1.1.0.clusterserviceversion.yaml
  deploy/catalog_resources/redhat/1.0.1/businessautomation-operator.1.0.1.clusterserviceversion.yaml
  deploy/catalog_resources/redhat/1.1.0/businessautomation-operator.1.1.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#142 [KIECLOUD-193] Update CSV installModes
  deploy/catalog_resources/community/1.0.1/kiecloud-operator.1.0.1.clusterserviceversion.yaml
  deploy/catalog_resources/redhat/1.0.1/businessautomation-operator.1.0.1.clusterserviceversion.yaml
  deploy/catalog_resources/redhat/catalog-source.yaml
Labels: approved, lgtm, size/XS

#143 [KIECLOUD-194] Deployment podStatuses faulty in OpenShift 4
  pkg/apis/app/v1/kieapp_types.go
  pkg/controller/kieapp/kieapp_controller.go
Labels: approved, lgtm, size/M

#145 packr vendoring fixes
  .gitignore
  Makefile
  README.md
  pkg/controller/kieapp/defaults/.packr/packr.go
  pkg/controller/kieapp/defaults/defaults.go
Labels: approved, lgtm, size/S

#146 add packr requirement to dep toml for builds
  Gopkg.lock
  Gopkg.toml
Labels: approved, lgtm, size/XS

#148 [KIECLOUD-194] Deployment podStatuses, edge case bug fix
  pkg/apis/app/v1/zz_generated.deepcopy.go
  pkg/controller/kieapp/kieapp_controller.go
Labels: approved, lgtm, size/M

#149 go upgrade for rhel builds
  image.yaml
  modules/kie-cloud-operator/install
Labels: approved, lgtm, size/XS

#150 [KIECLOUD-194] Deployment podStatuses changed in OLM/OCP 4
  pkg/apis/app/v1/kieapp_types.go
  pkg/apis/app/v1/zz_generated.deepcopy.go
  pkg/controller/kieapp/kieapp_controller.go
Labels: approved, lgtm, size/L

#147 [KIECLOUD-164] - Update the operator probes to match the new probes
  Gopkg.lock
  config/common.yaml
  pkg/apis/app/v1/kieapp_types.go
  pkg/controller/kieapp/constants/constants.go
  pkg/controller/kieapp/defaults/defaults.go
  pkg/controller/kieapp/defaults/defaults_test.go
Labels: approved, lgtm, ok-to-test, size/M

#151 remove tech preview from rhel builds
  deploy/catalog_resources/community/1.1.0/kiecloud-operator.1.1.0.clusterserviceversion.yaml
  deploy/catalog_resources/community/1.1.0/kiecloud.1.1.0.package.yaml
  deploy/catalog_resources/redhat/1.1.0/businessautomation-operator.1.1.0.clusterserviceversion.yaml
  deploy/catalog_resources/redhat/1.1.0/businessautomation.1.1.0.package.yaml
  hack/go-build.sh
Labels: approved, lgtm, size/S

#152 [KIECLOUD-184] default to OpenShiftStartupStrategy
  config/common.yaml
  config/envs/rhdm-production-immutable.yaml
  config/envs/rhpam-production-immutable.yaml
  deploy/examples/openshift_startup.yaml
Labels: approved, lgtm, size/M

#155 [KIECLOUD-194] Test coverage for PR 148
  pkg/controller/kieapp/kieapp_controller_test.go
  pkg/controller/kieapp/test/mock_service.go
Labels: approved, lgtm, size/L

#156 [KIECLOUD-199] temporary disable ocp check for ocp 4.1
  Gopkg.lock
  cmd/manager/main.go
Labels: approved, lgtm, size/M

#158 use tagged branch for builds
  hack/go-build.sh
Labels: approved, lgtm, size/XS

#157 use tagged branch for builds
  hack/go-build.sh
Labels: approved, lgtm, size/XS

#159 [KIECLOUD-194] Test coverage for PR148
  pkg/controller/kieapp/kieapp_controller_test.go
  pkg/controller/kieapp/test/mock_service.go
Labels: approved, lgtm, size/L

#161 use specific revision instead of branch in dep
  Gopkg.toml
Labels: approved, lgtm, size/XS
