Repository kiegroup/kie-cloud-operator, pull requests merged in 2019-05, with the labels that each got.

#166 [RHPAM-2125] Adding support for H2 Mixed Mode connection
  config/dbs/h2.yaml
  pkg/controller/kieapp/defaults/defaults_test.go
Labels: approved, lgtm, needs-ok-to-test, size/XS

#167 [KIECLOUD-219] allow smartRouter to be enabled from CR
  config/common.yaml
  config/envs/rhdm-authoring-ha.yaml
  config/envs/rhdm-authoring.yaml
  config/envs/rhdm-production-immutable.yaml
  config/envs/rhdm-trial.yaml
  config/envs/rhpam-authoring-ha.yaml
  config/envs/rhpam-authoring.yaml
  config/envs/rhpam-production-immutable.yaml
  config/envs/rhpam-production.yaml
  config/envs/rhpam-trial.yaml
  deploy/crs/kieapp_rhpam_production.yaml
  pkg/apis/app/v1/kieapp_types.go
  pkg/apis/app/v1/zz_generated.deepcopy.go
  pkg/controller/kieapp/defaults/defaults.go
  pkg/controller/kieapp/defaults/defaults_test.go
  pkg/controller/kieapp/defaults/merge_test.go
  pkg/controller/kieapp/kieapp_controller.go
  pkg/controller/kieapp/kieapp_controller_test.go
Labels: approved, lgtm, size/L

#169 [KIECLOUD-217] - Kie data path standardization
  config/common.yaml
  config/dbs/h2.yaml
  config/envs/rhdm-authoring-ha.yaml
  config/envs/rhpam-authoring-ha.yaml
  pkg/controller/kieapp/defaults/defaults_test.go
Labels: approved, lgtm, ok-to-test, size/M

#172 [KIECLOUD-221] upgrade datagrid and amq broker versions
  config/envs/rhdm-authoring-ha.yaml
  config/envs/rhpam-authoring-ha.yaml
  config/jms/activemq-jms-config.yaml
Labels: approved, lgtm, ok-to-test, size/S

#176 version/rhel updates
  README.md
  build/Dockerfile
  build/bin/entrypoint
  hack/go-build.sh
  image.yaml
  modules/kie-cloud-operator/install
Labels: approved, lgtm, size/M

#179 user_setup script fixes
  build/Dockerfile
  build/bin/user_setup
  image.yaml
  modules/kie-cloud-operator/install
Labels: approved, lgtm, size/S

#180 add product upgrade flags to CR spec
  deploy/crds/kieapp.crd.yaml
  deploy/examples/minor_upgrade.yaml
  hack/go-build.sh
  pkg/apis/app/v1/kieapp_types.go
  pkg/apis/app/v1/zz_generated.deepcopy.go
  pkg/controller/kieapp/defaults/defaults.go
  pkg/controller/kieapp/defaults/defaults_test.go
Labels: approved, lgtm, size/M

#182 [KIECLOUD-226] - Set RHPAM_NONXA to false on authoring scenarios with…
  config/dbs/h2.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#183 [KIECLOUD-229] switch back to Rolling deployment strategy for kie server
  config/dbs/h2.yaml
  pkg/controller/kieapp/defaults/defaults_test.go
Labels: approved, lgtm, size/XS

#184 [KIECLOUD-211] - Update Operator to match the templates changes made …
  config/dbs/mysql.yaml
  pkg/controller/kieapp/defaults/defaults_test.go
Labels: approved, lgtm, ok-to-test, size/XS

#187 [KIECLOUD-198] change timestamp to something more readable
  pkg/controller/kieapp/logs/logs.go
Labels: approved, lgtm, size/XS

#185 [RHPAM-2008] HTTP 503 error is shown in Monitoring
  config/common.yaml
Labels: approved, lgtm, ok-to-test, size/S

#188 specify go version 1.11.5 in osbs builds
  modules/kie-cloud-operator/install
Labels: approved, lgtm, size/XS

#190 Merge master into release-v1.1.x branch
  config/common.yaml
  config/dbs/h2.yaml
  config/dbs/mysql.yaml
  modules/kie-cloud-operator/install
  pkg/controller/kieapp/defaults/defaults_test.go
  pkg/controller/kieapp/logs/logs.go
Labels: approved, lgtm, size/M
