Repository kiegroup/kie-cloud-operator, pull requests merged in 2019-08, with the labels that each got.

#244 [KIECLOUD-160] Removing unnecessary git ports from containers
  config/7.5.0/envs/rhdm-authoring-ha.yaml
  config/7.5.0/envs/rhdm-authoring.yaml
  config/7.5.0/envs/rhdm-trial.yaml
  config/7.5.0/envs/rhpam-authoring-ha.yaml
  config/7.5.0/envs/rhpam-authoring.yaml
  config/7.5.0/envs/rhpam-trial.yaml
  pkg/controller/kieapp/defaults/defaults_test.go
Labels: approved, lgtm, ok-to-test, size/M

#233 [KIECLOUD-122] - Enable JMS for RHDM and RHPAM images.
  config/7.5.0/jms/activemq-jms-config.yaml
  deploy/crds/kieapp.crd.yaml
  deploy/crs/kieapp_rhpam_production-immutable-jms.yaml
  pkg/apis/app/v1/kieapp_types.go
  pkg/controller/kieapp/defaults/defaults.go
  pkg/controller/kieapp/defaults/defaults_test.go
  pkg/controller/kieapp/shared/utils.go
Labels: approved, lgtm, size/L

#246 [KIECLOUD-276] Adjust readiness probe parameters
  config/7.5.0/common.yaml
Labels: approved, lgtm, needs-ok-to-test, size/S

#247 [RHPAM-2282] Changes in users and roles made by Business central are not persisted
  config/7.5.0/common.yaml
Labels: approved, lgtm, size/XS

#249 [KIECLOUD-289] custom image/tag support for objects
  config/7.4.0/common.yaml
  config/7.4.1/common.yaml
  config/7.5.0/common.yaml
  deploy/crds/kieapp.crd.yaml
  deploy/examples/v2/custom_images_registry.yaml
  deploy/examples/v2/image_registry.yaml
  pkg/apis/app/v2/kieapp_types.go
  pkg/controller/kieapp/constants/constants.go
  pkg/controller/kieapp/defaults/defaults.go
  pkg/controller/kieapp/defaults/defaults_test.go
  pkg/controller/kieapp/test/crd_validation_test.go
Labels: approved, lgtm, size/L

#250 [KIECLOUD-303] remove include_unpublished_pulp_repos from image.yaml
  image.yaml
Labels: approved, lgtm, size/XS

#252 [KIECLOUD-285] Enable basic upgrade support
  Gopkg.lock
  Gopkg.toml
  deploy/catalog_resources/community/1.2.0/kiecloud-operator.1.2.0.clusterserviceversion.yaml
  deploy/catalog_resources/redhat/1.2.0/businessautomation-operator.1.2.0.clusterserviceversion.yaml
  deploy/examples/v2/minor_upgrade.yaml
  pkg/apis/app/v2/conversion.go
  pkg/apis/app/v2/conversion_test.go
  pkg/controller/kieapp/constants/constants.go
  pkg/controller/kieapp/defaults/defaults.go
  pkg/controller/kieapp/defaults/defaults_test.go
  pkg/controller/kieapp/defaults/upgrade.go
  pkg/controller/kieapp/defaults/upgrade_test.go
  pkg/controller/kieapp/kieapp_controller.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/util_test.go
  vendor/github.com/google/go-cmp/cmp/compare_test.go
  vendor/github.com/google/go-cmp/cmp/internal/value/sort.go
  vendor/github.com/google/go-cmp/cmp/internal/value/zero.go
  vendor/github.com/google/go-cmp/cmp/internal/value/zero_test.go
  vendor/github.com/google/go-cmp/cmp/report_compare.go
  vendor/github.com/google/go-cmp/cmp/report_reflect.go
  vendor/github.com/google/go-cmp/cmp/report_slices.go
  vendor/github.com/google/go-cmp/cmp/report_text.go
Labels: approved, lgtm, size/XL

#255 csv mods for seamless upgrades; use csv as owner for ui/cm objects
  deploy/catalog_resources/community/1.1.1/kiecloud-operator.1.1.1.clusterserviceversion.yaml
  deploy/catalog_resources/community/1.2.0/kiecloud-operator.1.2.0.clusterserviceversion.yaml
  deploy/catalog_resources/redhat/1.1.1/businessautomation-operator.1.1.1.clusterserviceversion.yaml
  deploy/catalog_resources/redhat/1.2.0/businessautomation-operator.1.2.0.clusterserviceversion.yaml
  deploy/operator.yaml
  pkg/controller/kieapp/defaults/defaults.go
  pkg/controller/kieapp/deploy_ui.go
  pkg/controller/kieapp/kieapp_controller.go
Labels: approved, lgtm, size/L

#256 change ownerhandler for cm & ui objects
  pkg/controller/kieapp/watch.go
Labels: approved, lgtm, size/XS

#258 [KIECLOUD-257] fix image name for scaledown controller
  config/7.4.0/envs/rhdm-authoring-ha.yaml
  config/7.4.0/envs/rhpam-authoring-ha.yaml
  config/7.4.1/envs/rhdm-authoring-ha.yaml
  config/7.4.1/envs/rhpam-authoring-ha.yaml
  config/7.5.0/envs/rhdm-authoring-ha.yaml
  config/7.5.0/envs/rhpam-authoring-ha.yaml
  pkg/controller/kieapp/kieapp_controller.go
Labels: approved, lgtm, size/S

#259 Merge remote-tracking branch 'upstream/master' into release-v1.2.x
  config/7.4.0/envs/rhdm-authoring-ha.yaml
  config/7.4.0/envs/rhpam-authoring-ha.yaml
  config/7.4.1/envs/rhdm-authoring-ha.yaml
  config/7.4.1/envs/rhpam-authoring-ha.yaml
  config/7.5.0/envs/rhdm-authoring-ha.yaml
  config/7.5.0/envs/rhpam-authoring-ha.yaml
  deploy/catalog_resources/community/1.1.1/kiecloud-operator.1.1.1.clusterserviceversion.yaml
  deploy/catalog_resources/community/1.2.0/kiecloud-operator.1.2.0.clusterserviceversion.yaml
  deploy/catalog_resources/redhat/1.1.1/businessautomation-operator.1.1.1.clusterserviceversion.yaml
  deploy/catalog_resources/redhat/1.2.0/businessautomation-operator.1.2.0.clusterserviceversion.yaml
  deploy/operator.yaml
  pkg/controller/kieapp/defaults/defaults.go
  pkg/controller/kieapp/deploy_ui.go
  pkg/controller/kieapp/kieapp_controller.go
  pkg/controller/kieapp/watch.go
Labels: approved, lgtm, size/L
