Repository kiegroup/kie-cloud-operator, pull requests merged in 2019-11, with the labels that each got.

#287 [RHPAM-2401] - Change strategy to type Rolling for other BA components
  config/7.6.0/common.yaml
  config/7.6.0/dbs/postgresql.yaml
  config/7.6.0/envs/rhdm-authoring-ha.yaml
  config/7.6.0/envs/rhpam-authoring-ha.yaml
  config/7.6.0/envs/rhpam-production.yaml
  config/7.6.0/jms/activemq-jms-config.yaml
  pkg/controller/kieapp/defaults/defaults_test.go
  pkg/controller/kieapp/defaults/merge_test.go
  pkg/controller/kieapp/defaults/upgrade_test.go
Labels: approved, lgtm, release-1.3.0, size/L

#288 [RHPAM-2279/RHDM-1057] update amq and datagrid images
  pkg/controller/kieapp/constants/constants.go
Labels: approved, lgtm, release-1.3.0, size/XS

#281 [RHPAM-2209] Allow configure GitHooks and RoleMapper
  config/7.6.0/common.yaml
  deploy/crds/kieapp.crd.yaml
  deploy/examples/v2/auth_ldap.yaml
  deploy/examples/v2/githooks.yaml
  pkg/apis/app/v2/kieapp_types.go
  pkg/apis/app/v2/zz_generated.deepcopy.go
  pkg/controller/kieapp/constants/constants.go
  pkg/controller/kieapp/defaults/auth.go
  pkg/controller/kieapp/defaults/auth_test.go
  pkg/controller/kieapp/defaults/defaults.go
  pkg/controller/kieapp/defaults/defaults_test.go
  pkg/controller/kieapp/kieapp_controller.go
  pkg/controller/kieapp/kieapp_controller_test.go
  pkg/controller/kieapp/test/crd_validation_test.go
Labels: approved, lgtm, release-1.3.0, size/XL

#302 cleanup release crds
  deploy/catalog_resources/community/1.1.0/kieapp.1.1.crd.yaml
  deploy/catalog_resources/community/1.1.1/kieapp.1.1.crd.yaml
  deploy/catalog_resources/redhat/1.1.0/kieapp.1.1.crd.yaml
  deploy/catalog_resources/redhat/1.1.1/kieapp.1.1.crd.yaml
Labels: approved, lgtm, size/XS

#303 [RHPAM-2490] - Replace roles configuration shown for internal authent…
  deploy/ui/form.json
Labels: approved, lgtm, ok-to-test, size/S

#304 [RHPAM-2490] - Replace roles configuration shown for internal authent…
  deploy/ui/form.json
Labels: approved, lgtm, ok-to-test, size/S

#285 move away from role wildcard rules
  config/7.5.0/common.yaml
  config/7.5.1/common.yaml
  config/7.6.0/common.yaml
  deploy/catalog_resources/community/1.3.0/kiecloud-operator.1.3.0.clusterserviceversion.yaml
  deploy/catalog_resources/redhat/1.3.0/businessautomation-operator.1.3.0.clusterserviceversion.yaml
  deploy/role.yaml
  pkg/components/components.go
  pkg/controller/kieapp/deploy_ui.go
Labels: approved, release-1.3.0, size/XL

#310 [KIECLOUD-343] allow product to get routes
  config/7.5.0/common.yaml
  config/7.5.1/common.yaml
  config/7.6.0/common.yaml
Labels: approved, lgtm, release-1.3.0, size/M

#311 Merge branch 'master' into release-v1.3.x
  config/7.5.0/common.yaml
  config/7.5.1/common.yaml
  config/7.6.0/common.yaml
Labels: approved, lgtm, release-1.3.0, size/M

#313 [KIECLOUD-343] allow product to get pods
  config/7.5.0/common.yaml
  config/7.5.1/common.yaml
  config/7.6.0/common.yaml
Labels: approved, lgtm, release-1.3.0, size/XS

#314 Merge branch 'master' into release-v1.3.x
  config/7.5.0/common.yaml
  config/7.5.1/common.yaml
  config/7.6.0/common.yaml
Labels: approved, lgtm, release-1.3.0, size/XS
