Repository kiegroup/kie-cloud-operator, pull requests merged in 2019-06, with the labels that each got.

#195 cekit 3.1.0 changes
  README.md
  image.yaml
Labels: approved, lgtm, size/XS

#186 [KIECLOUD-230] - Adjust authoring-ha environment to use jboss datagrid
  config/envs/rhdm-authoring-ha.yaml
  config/envs/rhpam-authoring-ha.yaml
  config/jms/activemq-jms-config.yaml
  pkg/apis/app/v1/kieapp_types.go
  pkg/controller/kieapp/constants/constants.go
  pkg/controller/kieapp/defaults/defaults_test.go
  pkg/controller/kieapp/kieapp_controller.go
  pkg/controller/kieapp/kieapp_controller_test.go
Labels: approved, lgtm, ok-to-test, size/XL

#194 [KIECLOUD-97] - Propagate OpenShiftStartupStrategy related changes to…
  config/common.yaml
  pkg/controller/kieapp/defaults/defaults_test.go
Labels: approved, lgtm, ok-to-test, size/S

#196 Merge master into release-v1.1.x branch
  README.md
  config/common.yaml
  config/envs/rhdm-authoring-ha.yaml
  config/envs/rhpam-authoring-ha.yaml
  config/jms/activemq-jms-config.yaml
  image.yaml
  pkg/apis/app/v1/kieapp_types.go
  pkg/controller/kieapp/constants/constants.go
  pkg/controller/kieapp/defaults/defaults_test.go
  pkg/controller/kieapp/kieapp_controller.go
  pkg/controller/kieapp/kieapp_controller_test.go
Labels: approved, lgtm, size/XL

#198 version 1.1.1 / 7.4.1
  README.md
  deploy/catalog_resources/community/1.1.1/kiecloud-operator.1.1.1.clusterserviceversion.yaml
  deploy/catalog_resources/community/1.1.1/kiecloud.1.1.1.package.yaml
  deploy/catalog_resources/courier/bundle_dir/1.1.1/kieapp.crd.yaml
  deploy/catalog_resources/courier/bundle_dir/1.1.1/kiecloud-operator.1.1.1.clusterserviceversion.yaml
  deploy/catalog_resources/courier/bundle_dir/1.1.1/kiecloud.1.1.1.package.yaml
  deploy/catalog_resources/redhat/1.1.1/businessautomation-operator.1.1.1.clusterserviceversion.yaml
  deploy/catalog_resources/redhat/1.1.1/businessautomation.1.1.1.package.yaml
  hack/go-build.sh
  image.yaml
  modules/kie-cloud-operator/install
  pkg/controller/kieapp/constants/constants.go
  version/version.go
Labels: approved, lgtm, size/L

#199 [KIECLOUD-239] Log CR errors in debug level
  Gopkg.lock
  Gopkg.toml
  pkg/ui/serve.go
  vendor/github.com/RHsyseng/console-cr-form/cmd/testwebapp.go
  vendor/github.com/RHsyseng/console-cr-form/pkg/web/http.go
Labels: approved, lgtm, size/S

#197 [KIECLOUD-231] watch/reconcile UI objects
  pkg/controller/kieapp/watch.go
Labels: approved, lgtm, size/XS

#201 [KIECLOUD-97] - Synchronize OpenShiftStartupStrategy related changes …
  config/common.yaml
  pkg/controller/kieapp/defaults/defaults_test.go
Labels: approved, lgtm, ok-to-test, size/S

#202 [KIECLOUD-97] - Cherry-picked Synchronize OpenShiftStartupStrategy related changes …
  config/common.yaml
  pkg/controller/kieapp/defaults/defaults_test.go
Labels: approved, lgtm, size/S

#205 fix resourceNames across 1.1.x versions
  deploy/catalog_resources/community/1.1.0/kiecloud-operator.1.1.0.clusterserviceversion.yaml
  deploy/catalog_resources/community/1.1.1/kiecloud-operator.1.1.1.clusterserviceversion.yaml
  deploy/catalog_resources/redhat/1.1.0/businessautomation-operator.1.1.0.clusterserviceversion.yaml
  deploy/catalog_resources/redhat/1.1.1/businessautomation-operator.1.1.1.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#213 [KIECLOUD-251] ensure installer link text is not shown in description…
  deploy/catalog_resources/community/1.1.0/kiecloud-operator.1.1.0.clusterserviceversion.yaml
  deploy/catalog_resources/community/1.1.1/kiecloud-operator.1.1.1.clusterserviceversion.yaml
  deploy/catalog_resources/redhat/1.1.0/businessautomation-operator.1.1.0.clusterserviceversion.yaml
  deploy/catalog_resources/redhat/1.1.1/businessautomation-operator.1.1.1.clusterserviceversion.yaml
  pkg/controller/kieapp/constants/constants.go
  pkg/controller/kieapp/deploy_ui.go
  pkg/controller/kieapp/deploy_ui_test.go
Labels: approved, lgtm, size/M

#215 [RHPAM-2226] Validation subelement is missing for datasources
  config/dbs/mysql.yaml
  config/dbs/postgresql.yaml
Labels: approved, lgtm, size/XS

#214 [RHPAM-2226] Validation subelement is missing for datasources
  config/dbs/mysql.yaml
  config/dbs/postgresql.yaml
Labels: approved, lgtm, size/XS
