Repository kiegroup/kie-cloud-operator, pull requests merged in 2019-07, with the labels that each got.

#212 [KIECLOUD-149] Fix rhdm/rhpam trial environments
  config/envs/rhdm-trial.yaml
  config/envs/rhpam-trial.yaml
Labels: approved, lgtm, size/S

#218 [RHPAM-1387] - Allow set Smart router location to external URL in RHPAM
  config/common.yaml
Labels: approved, lgtm, size/XS

#217 [RHPAM-1387] - Allow set Smart router location to external URL in RHPAM
  config/common.yaml
Labels: approved, lgtm, size/XS

#219 fixed console js deps vulnerabilities
  Gopkg.lock
  Gopkg.toml
  vendor/github.com/RHsyseng/console-cr-form/frontend/package-lock.json
Labels: approved, lgtm, size/M

#208 Rename JMS fields
  config/jms/activemq-jms-config.yaml
  deploy/crds/kieapp.crd.yaml
  deploy/crs/kieapp_rhdm_production-immutable-jms.yaml
  deploy/crs/kieapp_rhpam_production-immutable-jms.yaml
  pkg/apis/app/v1/kieapp_types.go
  pkg/controller/kieapp/defaults/defaults.go
  pkg/controller/kieapp/defaults/defaults_test.go
Labels: approved, lgtm, size/L

#220 [KIECLOUD-258] if imageRegistry defined, create local imagestreams
  pkg/apis/app/v1/kieapp_types.go
  pkg/apis/app/v1/zz_generated.deepcopy.go
  pkg/controller/kieapp/defaults/defaults.go
  pkg/controller/kieapp/defaults/defaults_test.go
  pkg/controller/kieapp/kieapp_controller.go
Labels: approved, lgtm, size/M

#221 [RHPAM-1387 ] - Allow set Smart router location to external URL in RHPAM
  config/common.yaml
  deploy/crds/kieapp.crd.yaml
  deploy/crs/kieapp_rhpam_production.yaml
  pkg/apis/app/v1/kieapp_types.go
  pkg/apis/app/v1/zz_generated.deepcopy.go
  pkg/controller/kieapp/constants/constants.go
  pkg/controller/kieapp/defaults/defaults.go
  pkg/controller/kieapp/defaults/defaults_test.go
  pkg/controller/kieapp/kieapp_controller_test.go
Labels: approved, lgtm, size/L

#222 [RHPAM-1387 ] - Allow set Smart router location to external URL in RHPAM
  config/common.yaml
  deploy/crds/kieapp.crd.yaml
  deploy/crs/kieapp_rhpam_production.yaml
  pkg/apis/app/v1/kieapp_types.go
  pkg/apis/app/v1/zz_generated.deepcopy.go
  pkg/controller/kieapp/constants/constants.go
  pkg/controller/kieapp/defaults/defaults.go
  pkg/controller/kieapp/defaults/defaults_test.go
  pkg/controller/kieapp/kieapp_controller_test.go
Labels: approved, lgtm, size/L

#224 deprecate smartRouter objects from example CRs
  deploy/crs/kieapp_rhpam_production.yaml
  deploy/examples/keystore-config.yaml
  deploy/examples/server_config.yaml
Labels: approved, lgtm, size/S

#223 deprecate smartRouter objects from example CRs
  deploy/crs/kieapp_rhpam_production.yaml
  deploy/examples/keystore-config.yaml
  deploy/examples/server_config.yaml
Labels: approved, lgtm, size/S

#225 [KIECLOUD-277] - JMS Parameters available for user to configure but n…
  config/jms/activemq-jms-config.yaml
  pkg/apis/app/v1/kieapp_types.go
  pkg/apis/app/v1/zz_generated.deepcopy.go
  pkg/controller/kieapp/defaults/defaults.go
  pkg/controller/kieapp/defaults/defaults_test.go
Labels: approved, lgtm, size/L

#226 Revert "[KIECLOUD-277] - JMS Parameters available for user to configure but n…"
  config/jms/activemq-jms-config.yaml
  pkg/apis/app/v1/kieapp_types.go
  pkg/apis/app/v1/zz_generated.deepcopy.go
  pkg/controller/kieapp/defaults/defaults.go
  pkg/controller/kieapp/defaults/defaults_test.go
Labels: approved, lgtm, size/L

#228 new capabilities annotation
  deploy/catalog_resources/community/1.1.0/kiecloud-operator.1.1.0.clusterserviceversion.yaml
  deploy/catalog_resources/redhat/1.1.0/businessautomation-operator.1.1.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#227 [KIECLOUD-277] - JMS Parameters available for user to configure but n…
  config/jms/activemq-jms-config.yaml
  pkg/apis/app/v1/kieapp_types.go
  pkg/apis/app/v1/zz_generated.deepcopy.go
  pkg/controller/kieapp/defaults/defaults.go
  pkg/controller/kieapp/defaults/defaults_test.go
Labels: approved, lgtm, size/L

#229 new capabilities annotation
  deploy/catalog_resources/community/1.1.0/kiecloud-operator.1.1.0.clusterserviceversion.yaml
  deploy/catalog_resources/community/1.1.1/kiecloud-operator.1.1.1.clusterserviceversion.yaml
  deploy/catalog_resources/redhat/1.1.0/businessautomation-operator.1.1.0.clusterserviceversion.yaml
  deploy/catalog_resources/redhat/1.1.1/businessautomation-operator.1.1.1.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#230 [KIECLOUD-278] remove go cache files post osbs build
  modules/kie-cloud-operator/install
Labels: approved, lgtm, size/XS

#234 [KIECLOUD-281] Change operator to use versioned config dirs
  config/7.4.0/common.yaml
  config/7.4.0/dbs/external.yaml
  config/7.4.0/dbs/h2.yaml
  config/7.4.0/dbs/mysql.yaml
  config/7.4.0/dbs/postgresql.yaml
  config/7.4.0/envs/rhdm-authoring-ha.yaml
  config/7.4.0/envs/rhdm-authoring.yaml
  config/7.4.0/envs/rhdm-production-immutable.yaml
  config/7.4.0/envs/rhdm-trial.yaml
  config/7.4.0/envs/rhpam-authoring-ha.yaml
  config/7.4.0/envs/rhpam-authoring.yaml
  config/7.4.0/envs/rhpam-production-immutable.yaml
  config/7.4.0/envs/rhpam-production.yaml
  config/7.4.0/envs/rhpam-trial.yaml
  config/7.4.0/jms/activemq-jms-config.yaml
  config/7.4.1/common.yaml
  config/7.4.1/dbs/external.yaml
  config/7.4.1/dbs/h2.yaml
  config/7.4.1/dbs/mysql.yaml
  config/7.4.1/dbs/postgresql.yaml
  config/7.4.1/envs/rhdm-authoring-ha.yaml
  config/7.4.1/envs/rhdm-authoring.yaml
  config/7.4.1/envs/rhdm-production-immutable.yaml
  config/7.4.1/envs/rhdm-trial.yaml
  config/7.4.1/envs/rhpam-authoring-ha.yaml
  config/7.4.1/envs/rhpam-authoring.yaml
  config/7.4.1/envs/rhpam-production-immutable.yaml
  config/7.4.1/envs/rhpam-production.yaml
  config/7.4.1/envs/rhpam-trial.yaml
  config/7.4.1/jms/activemq-jms-config.yaml
  pkg/apis/app/v1/kieapp_types.go
  pkg/apis/app/v1/zz_generated.deepcopy.go
  pkg/controller/kieapp/constants/constants.go
  pkg/controller/kieapp/defaults/defaults.go
  pkg/controller/kieapp/defaults/defaults_test.go
  pkg/controller/kieapp/defaults/merge_test.go
  pkg/controller/kieapp/kieapp_controller.go
  pkg/controller/kieapp/kieapp_controller_test.go
Labels: approved, lgtm, size/XXL

#235 [KIECLOUD-284] Change patch upgrade default to false
  pkg/controller/kieapp/defaults/defaults.go
  pkg/controller/kieapp/defaults/defaults_test.go
  pkg/controller/kieapp/kieapp_controller_test.go
Labels: approved, lgtm, size/M

#236 Merge 1.1.1 code from master
  config/7.4.0/common.yaml
  config/7.4.0/dbs/external.yaml
  config/7.4.0/dbs/h2.yaml
  config/7.4.0/dbs/mysql.yaml
  config/7.4.0/dbs/postgresql.yaml
  config/7.4.0/envs/rhdm-authoring-ha.yaml
  config/7.4.0/envs/rhdm-authoring.yaml
  config/7.4.0/envs/rhdm-production-immutable.yaml
  config/7.4.0/envs/rhdm-trial.yaml
  config/7.4.0/envs/rhpam-authoring-ha.yaml
  config/7.4.0/envs/rhpam-authoring.yaml
  config/7.4.0/envs/rhpam-production-immutable.yaml
  config/7.4.0/envs/rhpam-production.yaml
  config/7.4.0/envs/rhpam-trial.yaml
  config/7.4.0/jms/activemq-jms-config.yaml
  config/7.4.1/common.yaml
  config/7.4.1/dbs/external.yaml
  config/7.4.1/dbs/h2.yaml
  config/7.4.1/dbs/mysql.yaml
  config/7.4.1/dbs/postgresql.yaml
  config/7.4.1/envs/rhdm-authoring-ha.yaml
  config/7.4.1/envs/rhdm-authoring.yaml
  config/7.4.1/envs/rhdm-production-immutable.yaml
  config/7.4.1/envs/rhdm-trial.yaml
  config/7.4.1/envs/rhpam-authoring-ha.yaml
  config/7.4.1/envs/rhpam-authoring.yaml
  config/7.4.1/envs/rhpam-production-immutable.yaml
  config/7.4.1/envs/rhpam-production.yaml
  config/7.4.1/envs/rhpam-trial.yaml
  config/7.4.1/jms/activemq-jms-config.yaml
  pkg/apis/app/v1/kieapp_types.go
  pkg/apis/app/v1/zz_generated.deepcopy.go
  pkg/controller/kieapp/constants/constants.go
  pkg/controller/kieapp/defaults/defaults.go
  pkg/controller/kieapp/defaults/defaults_test.go
  pkg/controller/kieapp/defaults/merge_test.go
  pkg/controller/kieapp/kieapp_controller.go
  pkg/controller/kieapp/kieapp_controller_test.go
Labels: approved, lgtm, size/XXL

#237 [KIECLOUD-283] version 1.2.0 / 7.5.0
  README.md
  config/7.5.0/common.yaml
  config/7.5.0/dbs/external.yaml
  config/7.5.0/dbs/h2.yaml
  config/7.5.0/dbs/mysql.yaml
  config/7.5.0/dbs/postgresql.yaml
  config/7.5.0/envs/rhdm-authoring-ha.yaml
  config/7.5.0/envs/rhdm-authoring.yaml
  config/7.5.0/envs/rhdm-production-immutable.yaml
  config/7.5.0/envs/rhdm-trial.yaml
  config/7.5.0/envs/rhpam-authoring-ha.yaml
  config/7.5.0/envs/rhpam-authoring.yaml
  config/7.5.0/envs/rhpam-production-immutable.yaml
  config/7.5.0/envs/rhpam-production.yaml
  config/7.5.0/envs/rhpam-trial.yaml
  config/7.5.0/jms/activemq-jms-config.yaml
  deploy/catalog_resources/community/1.2.0/kiecloud-operator.1.2.0.clusterserviceversion.yaml
  deploy/catalog_resources/community/1.2.0/kiecloud.1.2.0.package.yaml
  deploy/catalog_resources/courier/bundle_dir/1.1.0/kieapp.1.1.crd.yaml
  deploy/catalog_resources/courier/bundle_dir/1.1.0/kieapp.crd.yaml
  deploy/catalog_resources/courier/bundle_dir/1.1.1/kieapp.1.1.crd.yaml
  deploy/catalog_resources/courier/bundle_dir/1.1.1/kieapp.crd.yaml
  deploy/catalog_resources/courier/bundle_dir/1.2.0/kieapp.1.2.crd.yaml
  deploy/catalog_resources/courier/bundle_dir/1.2.0/kiecloud-operator.1.2.0.clusterserviceversion.yaml
  deploy/catalog_resources/courier/bundle_dir/1.2.0/kiecloud.1.2.0.package.yaml
  deploy/catalog_resources/redhat/1.2.0/businessautomation-operator.1.2.0.clusterserviceversion.yaml
  deploy/catalog_resources/redhat/1.2.0/businessautomation.1.2.0.package.yaml
  deploy/crds/kieapp.1.1.crd.yaml
  deploy/crds/kieapp.1.2.crd.yaml
  deploy/crds/kieapp.crd.yaml
  deploy/operator.yaml
  hack/go-build.sh
  hack/go-dep.sh
  image.yaml
  modules/kie-cloud-operator/install
  pkg/controller/kieapp/constants/constants.go
  version/version.go
Labels: approved, lgtm, size/XXL

#239 install latest available minor version of go-toolset for osbs builds
  modules/kie-cloud-operator/install
Labels: approved, lgtm, size/XS

#240 fix ba operator csv image tag
  deploy/catalog_resources/redhat/1.2.0/businessautomation-operator.1.2.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#241 [KIECLOUD-281] fix configmap version logic release-v1.1.x
  pkg/controller/kieapp/defaults/defaults.go
  pkg/controller/kieapp/kieapp_controller.go
Labels: approved, lgtm, size/S

#238 install latest available minor version of go-toolset for osbs builds
  modules/kie-cloud-operator/install
Labels: approved, lgtm, size/XS

#242 [KIECLOUD-281] fix configmap version logic
  pkg/controller/kieapp/defaults/defaults.go
  pkg/controller/kieapp/kieapp_controller.go
Labels: approved, lgtm, size/S

#243 change crd link so that console has access
  deploy/crds/kieapp.1.2.crd.yaml
  deploy/crds/kieapp.crd.yaml
Labels: approved, lgtm, size/XXL
