Repository kiegroup/kie-cloud-operator, pull requests merged in 2019-10, with the labels that each got.

#277 [KIECLOUD-312] Console UI denies access to admins
  pkg/controller/kieapp/deploy_ui.go
Labels: approved, lgtm, size/S

#278 csv generation code cleanup
  tools/csv-gen/csv-gen.go
Labels: approved, lgtm, size/XS

#280 change oauth SAR to allow edit role user access
  pkg/controller/kieapp/deploy_ui.go
Labels: approved, lgtm, size/XS

#275 [KIECLOUD-328] required changes to build meta information for CPaaS
  image.yaml
Labels: approved, lgtm, size/XS

#276 [KIECLOUD-328] required changes to build meta information for CPaaS
  image.yaml
Labels: approved, lgtm, size/XS

#282 1.2.0 move to nested bundles
  deploy/catalog_resources/community/1.0.1/kiecloud-operator.1.0.1.clusterserviceversion.yaml
  deploy/catalog_resources/community/1.0.1/kiecloud.1.0.1.package.yaml
  deploy/catalog_resources/community/1.1.0/kieapp.1.1.crd.yaml
  deploy/catalog_resources/community/1.1.0/kiecloud.1.1.0.package.yaml
  deploy/catalog_resources/community/1.1.1/kieapp.1.1.crd.yaml
  deploy/catalog_resources/community/1.1.1/kiecloud.1.1.1.package.yaml
  deploy/catalog_resources/community/1.2.0/kieapp.crd.yaml
  deploy/catalog_resources/community/kiecloud.package.yaml
  deploy/catalog_resources/courier/bundle_dir/1.0.1/kieapp.1.0.crd.yaml
  deploy/catalog_resources/courier/bundle_dir/1.0.1/kiecloud-operator.1.0.1.clusterserviceversion.yaml
  deploy/catalog_resources/courier/bundle_dir/1.0.1/kiecloud.1.0.1.package.yaml
  deploy/catalog_resources/courier/bundle_dir/1.1.0/kieapp.1.1.crd.yaml
  deploy/catalog_resources/courier/bundle_dir/1.1.0/kiecloud-operator.1.1.0.clusterserviceversion.yaml
  deploy/catalog_resources/courier/bundle_dir/1.1.0/kiecloud.1.1.0.package.yaml
  deploy/catalog_resources/courier/bundle_dir/1.1.1/kieapp.1.1.crd.yaml
  deploy/catalog_resources/courier/bundle_dir/1.1.1/kiecloud-operator.1.1.1.clusterserviceversion.yaml
  deploy/catalog_resources/courier/bundle_dir/1.1.1/kiecloud.1.1.1.package.yaml
  deploy/catalog_resources/courier/bundle_dir/1.2.0/kieapp.1.2.crd.yaml
  deploy/catalog_resources/courier/bundle_dir/1.2.0/kiecloud-operator.1.2.0.clusterserviceversion.yaml
  deploy/catalog_resources/courier/bundle_dir/1.2.0/kiecloud.1.2.0.package.yaml
  deploy/catalog_resources/courier/kiecloud-operatorsource.yaml
  deploy/catalog_resources/redhat/1.0.0/businessautomation-operator.1.0.0.clusterserviceversion.yaml
  deploy/catalog_resources/redhat/1.0.0/businessautomation.1.0.0.package.yaml
  deploy/catalog_resources/redhat/1.0.1/businessautomation-operator.1.0.1.clusterserviceversion.yaml
  deploy/catalog_resources/redhat/1.0.1/businessautomation.1.0.1.package.yaml
  deploy/catalog_resources/redhat/1.1.0/businessautomation.1.1.0.package.yaml
  deploy/catalog_resources/redhat/1.1.0/kieapp.1.1.crd.yaml
  deploy/catalog_resources/redhat/1.1.1/businessautomation.1.1.1.package.yaml
  deploy/catalog_resources/redhat/1.1.1/kieapp.1.1.crd.yaml
  deploy/catalog_resources/redhat/1.2.0/kieapp.crd.yaml
  deploy/catalog_resources/redhat/businessautomation.package.yaml
  deploy/crds/kieapp.1.0.crd.yaml
  modules/kie-cloud-operator/install
Labels: approved, lgtm, size/XXL

#286 simplify versioning
  README.md
  getversion.go
  hack/go-build.sh
  pkg/controller/kieapp/deploy_ui_test.go
Labels: approved, lgtm, release-1.2.1, size/M

#284 [KIECLOUD-332] 1.2.0 image naming convention changes
  deploy/catalog_resources/redhat/1.2.0/businessautomation-operator.1.2.0.clusterserviceversion.yaml
  image.yaml
  pkg/controller/kieapp/constants/constants.go
  pkg/controller/kieapp/defaults/defaults.go
  pkg/controller/kieapp/defaults/defaults_test.go
Labels: approved, lgtm, size/L

#289 [KIECLOUD-332] 1.2.1 image naming convention changes
  deploy/catalog_resources/community/1.2.1/kiecloud-operator.1.2.1.clusterserviceversion.yaml
  deploy/catalog_resources/redhat/1.2.0/businessautomation-operator.1.2.0.clusterserviceversion.yaml
  deploy/catalog_resources/redhat/1.2.1/businessautomation-operator.1.2.1.clusterserviceversion.yaml
  image.yaml
  pkg/controller/kieapp/constants/constants.go
  pkg/controller/kieapp/defaults/defaults.go
  pkg/controller/kieapp/defaults/defaults_test.go
  tools/csv-gen/csv-gen.go
Labels: approved, lgtm, release-1.2.1, size/L

#290 fix nested bundle for release
  image.yaml
  modules/kie-cloud-operator/install
Labels: approved, lgtm, size/XS

#292 switch to rsync for manifests
  modules/kie-cloud-operator/install
Labels: approved, lgtm, size/XS

#291 fix nested bundle for release
  image.yaml
  modules/kie-cloud-operator/install
Labels: approved, lgtm, release-1.2.1, size/XS

#293 [RHPAM-2248] - Resources requests have incorrect name in CR YAML
  deploy/ui/form.json
Labels: approved, lgtm, ok-to-test, size/S

#294 [RHPAM-2248] - Resources requests have incorrect name in CR YAML
  deploy/ui/form.json
Labels: approved, lgtm, needs-ok-to-test, size/S

#295 [RHPAM-2247] - Role properties file configuration shown for internal au…
  deploy/ui/form.json
Labels: approved, lgtm, ok-to-test, size/S

#297 RHPAM-2247 - Role properties file configuration shown for internal au…
  deploy/ui/form.json
Labels: approved, lgtm, ok-to-test, size/S

#301 Merge 1.2.1 into `release-1.2.x` branch
  Gopkg.lock
  Makefile
  README.md
  config/7.5.1/common.yaml
  config/7.5.1/dbs/external.yaml
  config/7.5.1/dbs/h2.yaml
  config/7.5.1/dbs/mysql.yaml
  config/7.5.1/dbs/postgresql.yaml
  config/7.5.1/envs/rhdm-authoring-ha.yaml
  config/7.5.1/envs/rhdm-authoring.yaml
  config/7.5.1/envs/rhdm-production-immutable.yaml
  config/7.5.1/envs/rhdm-trial.yaml
  config/7.5.1/envs/rhpam-authoring-ha.yaml
  config/7.5.1/envs/rhpam-authoring.yaml
  config/7.5.1/envs/rhpam-production-immutable.yaml
  config/7.5.1/envs/rhpam-production.yaml
  config/7.5.1/envs/rhpam-trial.yaml
  config/7.5.1/jms/activemq-jms-config.yaml
  deploy/catalog_resources/community/1.1.0/kieapp.v1.crd.yaml
  deploy/catalog_resources/community/1.1.1/kieapp.v1.crd.yaml
  deploy/catalog_resources/community/1.2.1/kieapp.crd.yaml
  deploy/catalog_resources/community/1.2.1/kiecloud-operator.1.2.1.clusterserviceversion.yaml
  deploy/catalog_resources/community/kiecloud.package.yaml
  deploy/catalog_resources/redhat/1.1.0/kieapp.v1.crd.yaml
  deploy/catalog_resources/redhat/1.1.1/kieapp.v1.crd.yaml
  deploy/catalog_resources/redhat/1.2.1/businessautomation-operator.1.2.1.clusterserviceversion.yaml
  deploy/catalog_resources/redhat/1.2.1/kieapp.crd.yaml
  deploy/catalog_resources/redhat/businessautomation.package.yaml
  deploy/crds/kieapp.v1.crd.yaml
  deploy/crds/kieapp.v2.crd.yaml
  deploy/operator.yaml
  deploy/role.yaml
  getversion.go
  hack/go-build.sh
  image.yaml
  modules/kie-cloud-operator/install
  pkg/components/components.go
  pkg/controller/kieapp/constants/constants.go
  pkg/controller/kieapp/defaults/upgrade_test.go
  pkg/controller/kieapp/deploy_ui.go
  pkg/controller/kieapp/deploy_ui_test.go
  tools/csv-gen/csv-gen.go
  tools/util/marshaller.go
  version/version.go
Labels: approved, lgtm, release-1.2.1, size/XXL

#266 Refactor to use new operator-utils functions
  Gopkg.lock
  Gopkg.toml
  pkg/controller/kieapp/deploy_ui.go
  pkg/controller/kieapp/kieapp_controller.go
  pkg/controller/kieapp/kieapp_controller_test.go
  vendor/github.com/RHsyseng/operator-utils/Gopkg.lock
  vendor/github.com/RHsyseng/operator-utils/Gopkg.toml
  vendor/github.com/RHsyseng/operator-utils/pkg/resource/compare/defaults.go
  vendor/github.com/RHsyseng/operator-utils/pkg/resource/compare/map.go
  vendor/github.com/RHsyseng/operator-utils/pkg/resource/compare/types.go
  vendor/github.com/RHsyseng/operator-utils/pkg/resource/read/reader.go
  vendor/github.com/RHsyseng/operator-utils/pkg/resource/read/reader_test.go
  vendor/github.com/RHsyseng/operator-utils/pkg/resource/write/writer.go
  vendor/github.com/RHsyseng/operator-utils/pkg/resource/write/writer_test.go
Labels: approved, lgtm, release-1.3.0, size/XL

#299 upgrade version to 1.3.0 / 7.6.0
  config/7.6.0/common.yaml
  config/7.6.0/dbs/external.yaml
  config/7.6.0/dbs/h2.yaml
  config/7.6.0/dbs/mysql.yaml
  config/7.6.0/dbs/postgresql.yaml
  config/7.6.0/envs/rhdm-authoring-ha.yaml
  config/7.6.0/envs/rhdm-authoring.yaml
  config/7.6.0/envs/rhdm-production-immutable.yaml
  config/7.6.0/envs/rhdm-trial.yaml
  config/7.6.0/envs/rhpam-authoring-ha.yaml
  config/7.6.0/envs/rhpam-authoring.yaml
  config/7.6.0/envs/rhpam-production-immutable.yaml
  config/7.6.0/envs/rhpam-production.yaml
  config/7.6.0/envs/rhpam-trial.yaml
  config/7.6.0/jms/activemq-jms-config.yaml
  deploy/catalog_resources/community/1.3.0/kieapp.crd.yaml
  deploy/catalog_resources/community/1.3.0/kiecloud-operator.1.3.0.clusterserviceversion.yaml
  deploy/catalog_resources/community/kiecloud.package.yaml
  deploy/catalog_resources/redhat/1.3.0/businessautomation-operator.1.3.0.clusterserviceversion.yaml
  deploy/catalog_resources/redhat/1.3.0/kieapp.crd.yaml
  deploy/catalog_resources/redhat/businessautomation.package.yaml
  deploy/operator.yaml
  image.yaml
  pkg/controller/kieapp/constants/constants.go
  pkg/controller/kieapp/defaults/defaults.go
  pkg/controller/kieapp/defaults/defaults_test.go
  pkg/controller/kieapp/defaults/upgrade_test.go
  tools/csv-gen/csv-gen.go
  version/version.go
Labels: approved, lgtm, release-1.3.0, size/XXL

#300 [RHPAM-2205] - Add AMQ support to Operator installer UI
  deploy/ui/form.json
Labels: approved, lgtm, ok-to-test, release-1.3.0, size/L
