Repository kiegroup/kie-cloud-operator, pull requests merged in 2019-09, with the labels that each got.

#254 Full reconcile of resources using shared library
  Gopkg.lock
  Gopkg.toml
  pkg/apis/app/v1/kieapp_types.go
  pkg/apis/app/v2/kieapp_types.go
  pkg/controller/kieapp/deploy_ui.go
  pkg/controller/kieapp/kieapp_controller.go
  pkg/controller/kieapp/kieapp_controller_test.go
  pkg/controller/kieapp/shared/utils.go
  pkg/controller/kieapp/test/mock_service.go
  pkg/controller/kube_service.go
  vendor/github.com/RHsyseng/operator-utils/Gopkg.lock
  vendor/github.com/RHsyseng/operator-utils/pkg/resource/compare/defaults.go
  vendor/github.com/RHsyseng/operator-utils/pkg/resource/compare/defaults_test.go
  vendor/github.com/RHsyseng/operator-utils/pkg/resource/compare/map.go
  vendor/github.com/RHsyseng/operator-utils/pkg/resource/compare/test/external_test.go
  vendor/github.com/RHsyseng/operator-utils/pkg/resource/compare/test/utils_test.go
  vendor/github.com/RHsyseng/operator-utils/pkg/resource/compare/types.go
  vendor/github.com/RHsyseng/operator-utils/pkg/resource/compare/utils.go
  vendor/github.com/RHsyseng/operator-utils/pkg/resource/test/utils.go
  vendor/github.com/RHsyseng/operator-utils/pkg/resource/test/utils_test.go
  vendor/github.com/RHsyseng/operator-utils/pkg/resource/types.go
  vendor/github.com/RHsyseng/operator-utils/pkg/resource/types_test.go
  vendor/github.com/RHsyseng/operator-utils/pkg/resource/write/hooks/update_hooks.go
  vendor/github.com/RHsyseng/operator-utils/pkg/resource/write/writer.go
  vendor/github.com/RHsyseng/operator-utils/pkg/resource/write/writer_test.go
Labels: approved, lgtm, size/XXL

#260 Merge branch 'master' into release-v1.2.x
  Gopkg.lock
  Gopkg.toml
  pkg/apis/app/v1/kieapp_types.go
  pkg/apis/app/v2/kieapp_types.go
  pkg/controller/kieapp/deploy_ui.go
  pkg/controller/kieapp/kieapp_controller.go
  pkg/controller/kieapp/kieapp_controller_test.go
  pkg/controller/kieapp/shared/utils.go
  pkg/controller/kieapp/test/mock_service.go
  pkg/controller/kube_service.go
  vendor/github.com/RHsyseng/operator-utils/Gopkg.lock
  vendor/github.com/RHsyseng/operator-utils/pkg/resource/compare/defaults.go
  vendor/github.com/RHsyseng/operator-utils/pkg/resource/compare/defaults_test.go
  vendor/github.com/RHsyseng/operator-utils/pkg/resource/compare/map.go
  vendor/github.com/RHsyseng/operator-utils/pkg/resource/compare/test/external_test.go
  vendor/github.com/RHsyseng/operator-utils/pkg/resource/compare/test/utils_test.go
  vendor/github.com/RHsyseng/operator-utils/pkg/resource/compare/types.go
  vendor/github.com/RHsyseng/operator-utils/pkg/resource/compare/utils.go
  vendor/github.com/RHsyseng/operator-utils/pkg/resource/test/utils.go
  vendor/github.com/RHsyseng/operator-utils/pkg/resource/test/utils_test.go
  vendor/github.com/RHsyseng/operator-utils/pkg/resource/types.go
  vendor/github.com/RHsyseng/operator-utils/pkg/resource/types_test.go
  vendor/github.com/RHsyseng/operator-utils/pkg/resource/write/hooks/update_hooks.go
  vendor/github.com/RHsyseng/operator-utils/pkg/resource/write/writer.go
  vendor/github.com/RHsyseng/operator-utils/pkg/resource/write/writer_test.go
Labels: approved, lgtm, size/XXL

#262 Reserve CSV upgrades for 1.2.1 / 7.5.1 release
  deploy/catalog_resources/community/1.1.1/kiecloud-operator.1.1.1.clusterserviceversion.yaml
  deploy/catalog_resources/community/1.2.0/kiecloud-operator.1.2.0.clusterserviceversion.yaml
  deploy/catalog_resources/redhat/1.1.1/businessautomation-operator.1.1.1.clusterserviceversion.yaml
  deploy/catalog_resources/redhat/1.2.0/businessautomation-operator.1.2.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/S

#263 Merge branch 'master' into release-v1.2.x
  deploy/catalog_resources/community/1.1.1/kiecloud-operator.1.1.1.clusterserviceversion.yaml
  deploy/catalog_resources/community/1.2.0/kiecloud-operator.1.2.0.clusterserviceversion.yaml
  deploy/catalog_resources/redhat/1.1.1/businessautomation-operator.1.1.1.clusterserviceversion.yaml
  deploy/catalog_resources/redhat/1.2.0/businessautomation-operator.1.2.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/S

#265 [RHPAM-2354] OutOfMemoryError on Datagrid cause issues on project import indexing
  config/7.5.0/envs/rhdm-authoring-ha.yaml
  config/7.5.0/envs/rhpam-authoring-ha.yaml
  pkg/controller/kieapp/constants/constants.go
Labels: approved, lgtm, size/S

#268 reconcile only secrets owned by CR
  pkg/controller/kieapp/kieapp_controller.go
Labels: approved, lgtm, size/S

#267 [RHDM-1057_RHPAM-2279] - Review and update Authoring HA template for …
  config/7.5.0/envs/rhdm-authoring-ha.yaml
  config/7.5.0/envs/rhpam-authoring-ha.yaml
  pkg/controller/kieapp/constants/constants.go
  pkg/controller/kieapp/defaults/defaults_test.go
Labels: approved, lgtm, size/XL

#269 Merge branch 'master' into release-v1.2.x
  config/7.5.0/envs/rhdm-authoring-ha.yaml
  config/7.5.0/envs/rhpam-authoring-ha.yaml
  pkg/controller/kieapp/constants/constants.go
  pkg/controller/kieapp/defaults/defaults_test.go
  pkg/controller/kieapp/kieapp_controller.go
Labels: approved, lgtm, size/XL

#264 increment versions to 1.2.1 / 7.5.1
  README.md
  config/7.5.1/common.yaml
  config/7.5.1/dbs/external.yaml
  config/7.5.1/dbs/h2.yaml
  config/7.5.1/dbs/mysql.yaml
  config/7.5.1/dbs/postgresql.yaml
  config/7.5.1/envs/rhdm-authoring-ha.yaml
  config/7.5.1/envs/rhdm-authoring.yaml
  config/7.5.1/envs/rhdm-production-immutable.yaml
  config/7.5.1/envs/rhdm-trial.yaml
  config/7.5.1/envs/rhpam-authoring-ha.yaml
  config/7.5.1/envs/rhpam-authoring.yaml
  config/7.5.1/envs/rhpam-production-immutable.yaml
  config/7.5.1/envs/rhpam-production.yaml
  config/7.5.1/envs/rhpam-trial.yaml
  config/7.5.1/jms/activemq-jms-config.yaml
  deploy/catalog_resources/community/1.0.1/kiecloud-operator.1.0.1.clusterserviceversion.yaml
  deploy/catalog_resources/community/1.0.1/kiecloud.1.0.1.package.yaml
  deploy/catalog_resources/community/1.1.0/kiecloud-operator.1.1.0.clusterserviceversion.yaml
  deploy/catalog_resources/community/1.1.0/kiecloud.1.1.0.package.yaml
  deploy/catalog_resources/community/1.2.1/kiecloud-operator.1.2.1.clusterserviceversion.yaml
  deploy/catalog_resources/community/1.2.1/kiecloud.1.2.1.package.yaml
  deploy/catalog_resources/courier/bundle_dir/1.0.1/kieapp.1.0.crd.yaml
  deploy/catalog_resources/courier/bundle_dir/1.0.1/kiecloud-operator.1.0.1.clusterserviceversion.yaml
  deploy/catalog_resources/courier/bundle_dir/1.0.1/kiecloud.1.0.1.package.yaml
  deploy/catalog_resources/courier/bundle_dir/1.1.0/kieapp.1.1.crd.yaml
  deploy/catalog_resources/courier/bundle_dir/1.1.0/kiecloud-operator.1.1.0.clusterserviceversion.yaml
  deploy/catalog_resources/courier/bundle_dir/1.1.0/kiecloud.1.1.0.package.yaml
  deploy/catalog_resources/courier/bundle_dir/1.2.1/kieapp.1.2.crd.yaml
  deploy/catalog_resources/courier/bundle_dir/1.2.1/kiecloud-operator.1.2.1.clusterserviceversion.yaml
  deploy/catalog_resources/courier/bundle_dir/1.2.1/kiecloud.1.2.1.package.yaml
  deploy/catalog_resources/redhat/1.0.0/businessautomation.1.0.0.package.yaml
  deploy/catalog_resources/redhat/1.0.1/businessautomation.1.0.1.package.yaml
  deploy/catalog_resources/redhat/1.1.0/businessautomation-operator.1.1.0.clusterserviceversion.yaml
  deploy/catalog_resources/redhat/1.1.0/businessautomation.1.1.0.package.yaml
  deploy/catalog_resources/redhat/1.2.1/businessautomation-operator.1.2.1.clusterserviceversion.yaml
  deploy/catalog_resources/redhat/1.2.1/businessautomation.1.2.1.package.yaml
  deploy/operator.yaml
  hack/go-build.sh
  image.yaml
  modules/kie-cloud-operator/install
  pkg/controller/kieapp/constants/constants.go
  pkg/controller/kieapp/defaults/upgrade_test.go
  pkg/controller/kieapp/deploy_ui_test.go
  version/version.go
Labels: approved, lgtm, size/XXL

#270 rename crd files & fix package link
  README.md
  deploy/catalog_resources/community/1.2.1/kiecloud.1.2.1.package.yaml
  deploy/catalog_resources/courier/bundle_dir/1.1.1/kieapp.1.1.crd.yaml
  deploy/catalog_resources/courier/bundle_dir/1.1.1/kieapp.v1.crd.yaml
  deploy/catalog_resources/courier/bundle_dir/1.2.0/kieapp.1.2.crd.yaml
  deploy/catalog_resources/courier/bundle_dir/1.2.0/kieapp.v2.crd.yaml
  deploy/catalog_resources/courier/bundle_dir/1.2.1/kieapp.1.2.crd.yaml
  deploy/catalog_resources/courier/bundle_dir/1.2.1/kieapp.v2.crd.yaml
  deploy/catalog_resources/courier/kiecloud-operatorsource.yaml
  deploy/crds/kieapp.1.0.crd.yaml
  deploy/crds/kieapp.v1.crd.yaml
  deploy/crds/kieapp.v2.crd.yaml
Labels: approved, lgtm, size/XXL

#271 [KIECLOUD-299] csv generation
  Gopkg.lock
  Makefile
  deploy/catalog_resources/community/1.2.1/kiecloud-operator.1.2.1.clusterserviceversion.yaml
  deploy/catalog_resources/community/1.2.1/kiecloud.1.2.1.package.yaml
  deploy/catalog_resources/redhat/1.2.1/businessautomation-operator.1.2.1.clusterserviceversion.yaml
  deploy/catalog_resources/redhat/1.2.1/businessautomation.1.2.1.package.yaml
  deploy/operator.yaml
  deploy/role.yaml
  pkg/components/components.go
  tools/csv-gen/csv-gen.go
  tools/util/marshaller.go
Labels: approved, lgtm, size/XXL
