Repository kiegroup/kie-cloud-operator, pull requests merged in 2019-03, with the labels that each got.

#87 [RHPAM-1942] Adjust dialect and EJB timer configuration according to …
  config/envs/rhpam-authoring-ha.yaml
  config/envs/rhpam-production-immutable.yaml
  config/envs/rhpam-production.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#86 [RHPAM-1942] Adjust dialect and EJB timer configuration according to …
  config/envs/rhpam-authoring-ha.yaml
  config/envs/rhpam-production-immutable.yaml
  config/envs/rhpam-production.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#88 remove crd comments
  deploy/crds/kieapp.crd.yaml
Labels: approved, lgtm, size/M

#85 [KIECLOUD-52] Consolidate server configurations
  config/common.yaml
  config/envs/rhdm-authoring-ha.yaml
  config/envs/rhdm-production-immutable.yaml
  config/envs/rhdm-trial.yaml
  config/envs/rhpam-authoring-ha.yaml
  config/envs/rhpam-authoring.yaml
  config/envs/rhpam-production-immutable.yaml
  config/envs/rhpam-production.yaml
  config/envs/rhpam-trial.yaml
  deploy/catalog_resources/redhat/bundle.1.0.0.yaml
  deploy/crds/kieapp.crd.yaml
  deploy/crs/kieapp_rhdm_production-immutable.yaml
  deploy/examples/auth_sso.yaml
  deploy/examples/immutable_deployment.yaml
  deploy/examples/immutable_s2i.yaml
  deploy/examples/server_common_config.yaml
  hack/catalog-redhat.sh
  pkg/apis/app/v1/kieapp_types.go
  pkg/apis/app/v1/zz_generated.deepcopy.go
  pkg/apis/app/v1/zz_generated.defaults.go
  pkg/controller/kieapp/defaults/auth.go
  pkg/controller/kieapp/defaults/auth_test.go
  pkg/controller/kieapp/defaults/defaults.go
  pkg/controller/kieapp/defaults/defaults_test.go
  pkg/controller/kieapp/defaults/merge.go
  pkg/controller/kieapp/defaults/merge_test.go
  pkg/controller/kieapp/kieapp_controller.go
  pkg/controller/kieapp/kieapp_controller_test.go
  pkg/controller/kieapp/shared/utils.go
Labels: approved, lgtm, size/XXL

#89 [KIECLOUD-139] use commonConfig.applicationName for object naming
  deploy/examples/common_config.yaml
  pkg/controller/kieapp/defaults/defaults.go
  pkg/controller/kieapp/defaults/defaults_test.go
  pkg/controller/kieapp/kieapp_controller.go
  pkg/controller/kieapp/kieapp_controller_test.go
Labels: approved, lgtm, size/M

#90 [KIECLOUD-142] sort servers
  pkg/controller/kieapp/defaults/defaults.go
Labels: approved, lgtm, size/S

#83 [KIECLOUD-116] Fix CRD and S2I reconciliation
  config/common.yaml
  deploy/crds/kieapp.crd.yaml
  deploy/examples/immutable_deployment.yaml
  pkg/controller/kieapp/defaults/defaults_test.go
  pkg/controller/kieapp/kieapp_controller.go
Labels: approved, lgtm, size/L

#91 CatalogSource file and generation for redhat catalog
  deploy/catalog_resources/redhat/catalog-source.yaml
  hack/catalog-redhat.sh
Labels: approved, lgtm, size/XL

#92 add keystore secret specification option
  config/common.yaml
  config/envs/rhdm-authoring-ha.yaml
  config/envs/rhdm-authoring.yaml
  config/envs/rhdm-production-immutable.yaml
  config/envs/rhdm-trial.yaml
  config/envs/rhpam-authoring-ha.yaml
  config/envs/rhpam-authoring.yaml
  config/envs/rhpam-production-immutable.yaml
  config/envs/rhpam-trial.yaml
  deploy/catalog_resources/redhat/catalog-source.yaml
  deploy/crds/kieapp.crd.yaml
  deploy/examples/keystore-config.yaml
  deploy/examples/server_common_config.yaml
  hack/catalog-redhat.sh
  hack/catalog-source.sh
  hack/go-test.sh
  pkg/apis/app/v1/kieapp_types.go
  pkg/apis/app/v1/zz_generated.deepcopy.go
  pkg/controller/kieapp/constants/constants.go
  pkg/controller/kieapp/defaults/defaults.go
  pkg/controller/kieapp/defaults/defaults_test.go
  pkg/controller/kieapp/defaults/merge.go
  pkg/controller/kieapp/defaults/merge_test.go
  pkg/controller/kieapp/kieapp_controller.go
  pkg/controller/kieapp/kieapp_controller_test.go
Labels: approved, lgtm, size/L

#93 script cleanup
  deploy/examples/auth_ldap.yaml
  deploy/examples/server_common_config.yaml
  hack/catalog-redhat.sh
  hack/go-build.sh
  hack/go-test.sh
  hack/go-vet.sh
Labels: approved, lgtm, size/S

#94 improve server example
  README.md
  deploy/examples/auth_ldap.yaml
  deploy/examples/auth_sso.yaml
  deploy/examples/server_common_config.yaml
  deploy/examples/server_config.yaml
  pkg/controller/kieapp/defaults/defaults_test.go
Labels: approved, lgtm, size/L

#96 [KIECLOUD-145] add replicas option
  config/common.yaml
  config/envs/rhdm-authoring-ha.yaml
  config/envs/rhdm-authoring.yaml
  config/envs/rhdm-optaweb-trial.yaml
  config/envs/rhdm-production-immutable.yaml
  config/envs/rhdm-trial.yaml
  config/envs/rhpam-authoring-ha.yaml
  config/envs/rhpam-authoring.yaml
  config/envs/rhpam-production-immutable.yaml
  config/envs/rhpam-production.yaml
  config/envs/rhpam-trial.yaml
  deploy/catalog_resources/redhat/catalog-source.yaml
  deploy/crds/kieapp.crd.yaml
  deploy/examples/immutable_deployment.yaml
  deploy/examples/server_config.yaml
  pkg/apis/app/v1/kieapp_types.go
  pkg/apis/app/v1/zz_generated.deepcopy.go
  pkg/controller/kieapp/constants/constants.go
  pkg/controller/kieapp/defaults/defaults.go
  pkg/controller/kieapp/defaults/defaults_test.go
  pkg/controller/kieapp/kieapp_controller.go
  pkg/controller/kieapp/kieapp_controller_test.go
  pkg/controller/kieapp/shared/utils.go
Labels: approved, lgtm, size/XXL

#98 [KIECLOUD-121] Add KIE_SERVER_MODE default values
  config/common.yaml
  config/envs/rhpam-production.yaml
  pkg/controller/kieapp/defaults/defaults_test.go
Labels: approved, lgtm, size/S

#97 [KIECLOUD-151] Remove optaweb references
  config/envs/rhdm-optaweb-trial.yaml
  deploy/catalog_resources/redhat/catalog-source.yaml
  deploy/crds/kieapp.crd.yaml
  deploy/crs/kieapp_rhdm_optaweb-trial.yaml
  pkg/apis/app/v1/kieapp_types.go
  pkg/controller/kieapp/constants/constants.go
Labels: approved, lgtm, size/L

#95 [KIECLOUD-146] Add CRD and model
  config/common.yaml
  config/dbs/external.yaml
  config/dbs/h2.yaml
  config/dbs/mysql.yaml
  config/dbs/postgresql.yaml
  config/envs/rhdm-production-immutable.yaml
  config/envs/rhdm-trial.yaml
  config/envs/rhpam-authoring-ha.yaml
  config/envs/rhpam-authoring.yaml
  config/envs/rhpam-production-immutable.yaml
  config/envs/rhpam-production.yaml
  config/envs/rhpam-trial.yaml
  deploy/catalog_resources/redhat/catalog-source.yaml
  deploy/crds/kieapp.crd.yaml
  deploy/examples/server_externaldb.yaml
  deploy/examples/server_h2.yaml
  deploy/examples/server_mysql.yaml
  deploy/examples/server_mysql_ephemeral.yaml
  deploy/examples/server_postgresql.yaml
  pkg/apis/app/v1/kieapp_types.go
  pkg/apis/app/v1/zz_generated.deepcopy.go
  pkg/controller/kieapp/constants/constants.go
  pkg/controller/kieapp/defaults/auth.go
  pkg/controller/kieapp/defaults/defaults.go
  pkg/controller/kieapp/defaults/defaults_test.go
  pkg/controller/kieapp/defaults/merge.go
  pkg/controller/kieapp/defaults/merge_test.go
  pkg/controller/kieapp/kieapp_controller.go
  pkg/controller/kieapp/kieapp_controller_test.go
Labels: approved, lgtm, size/XXL

#99 add crd validation for commonConfig
  deploy/catalog_resources/redhat/catalog-source.yaml
  deploy/crds/kieapp.crd.yaml
  deploy/examples/common_config.yaml
Labels: approved, lgtm, size/L

#101 remove required fields from for commonConfig validation
  deploy/catalog_resources/redhat/catalog-source.yaml
  deploy/crds/kieapp.crd.yaml
Labels: approved, lgtm, size/S

#100 [KIECLOUD-149] Fix trial environments
  config/dbs/h2.yaml
  config/envs/rhdm-authoring.yaml
  config/envs/rhdm-trial.yaml
  config/envs/rhpam-authoring.yaml
  config/envs/rhpam-trial.yaml
  deploy/crs/kieapp_rhdm_production-immutable.yaml
  pkg/controller/kieapp/constants/constants.go
  pkg/controller/kieapp/defaults/defaults_test.go
  pkg/controller/kieapp/defaults/merge_test.go
Labels: approved, lgtm, size/L

#103 csv improvements
  README.md
  deploy/catalog_resources/community/kiecloud-operator.v1.0.0.clusterserviceversion.yaml
  deploy/catalog_resources/redhat/businessautomation-operator.v1.0.0.clusterserviceversion.yaml
  deploy/catalog_resources/redhat/catalog-source.yaml
  deploy/operator.yaml
Labels: approved, lgtm, size/L

#102 CommonConfig clean up
  config/common.yaml
  config/dbs/h2.yaml
  config/dbs/mysql.yaml
  config/dbs/postgresql.yaml
  config/envs/rhdm-authoring-ha.yaml
  config/envs/rhdm-production-immutable.yaml
  config/envs/rhpam-authoring-ha.yaml
  config/envs/rhpam-production-immutable.yaml
  deploy/catalog_resources/redhat/catalog-source.yaml
  deploy/crds/kieapp.crd.yaml
  deploy/examples/common_config.yaml
  deploy/examples/server_h2.yaml
  deploy/examples/server_postgresql.yaml
  pkg/apis/app/v1/kieapp_types.go
  pkg/apis/app/v1/zz_generated.deepcopy.go
  pkg/controller/kieapp/constants/constants.go
  pkg/controller/kieapp/defaults/defaults.go
  pkg/controller/kieapp/defaults/defaults_test.go
  pkg/controller/kieapp/kieapp_controller.go
Labels: approved, lgtm, size/XL

#104 [KIECLOUD-152] RHDM environment issues
  config/envs/rhdm-authoring.yaml
  config/envs/rhdm-production-immutable.yaml
Labels: approved, lgtm, size/S

#105 [KIECLOUD-155] rhdm authoring-ha fixes
  config/envs/rhdm-authoring-ha.yaml
  deploy/catalog_resources/community/kiecloud-operator.v1.0.0.clusterserviceversion.yaml
  deploy/catalog_resources/redhat/businessautomation-operator.v1.0.0.clusterserviceversion.yaml
  deploy/catalog_resources/redhat/catalog-source.yaml
  pkg/apis/app/v1/kieapp_types.go
  pkg/apis/app/v1/zz_generated.deepcopy.go
  pkg/controller/kieapp/defaults/defaults_test.go
  pkg/controller/kieapp/defaults/merge.go
  pkg/controller/kieapp/kieapp_controller.go
  pkg/controller/kieapp/watch.go
Labels: approved, lgtm, size/L

#107 [RHPAM-1970] add init containers for DB checks
  config/dbs/mysql.yaml
  config/dbs/postgresql.yaml
Labels: approved, lgtm, size/S

#108 change documentation link in csv
  deploy/catalog_resources/community/kiecloud-operator.v1.0.0.clusterserviceversion.yaml
  deploy/catalog_resources/redhat/businessautomation-operator.v1.0.0.clusterserviceversion.yaml
  deploy/catalog_resources/redhat/catalog-source.yaml
Labels: approved, lgtm, size/XS

#109 permissions cleanup
  config/common.yaml
  deploy/catalog_resources/community/kiecloud-operator.v1.0.0.clusterserviceversion.yaml
  deploy/catalog_resources/redhat/businessautomation-operator.v1.0.0.clusterserviceversion.yaml
  deploy/catalog_resources/redhat/catalog-source.yaml
  deploy/role.yaml
Labels: approved, lgtm, size/L

#110 [KIECLOUD-165] fix h2 db persistence
  config/dbs/h2.yaml
Labels: approved, lgtm, size/M

#106 [KIECLOUD-168] rhpam authoring-ha fixes
  config/envs/rhdm-authoring-ha.yaml
  config/envs/rhpam-authoring-ha.yaml
  pkg/controller/kieapp/defaults/defaults_test.go
Labels: approved, lgtm, size/L
