Repository kiegroup/kie-cloud-operator, pull requests merged in 2020-09, with the labels that each got.

#505 generate 7.8.1 csv w/ digests
  deploy/catalog_resources/community/7.8/kiecloud-operator.7.8.1.clusterserviceversion.yaml
  deploy/catalog_resources/redhat/7.8/businessautomation-operator.7.8.1.clusterserviceversion.yaml
Labels: approved, lgtm, release-7.8.1

#506 generate 7.8.1 csv w/ digests
  deploy/olm-catalog/businessautomation-operator/7.8.1/manifests/businessautomation-operator.7.8.1.clusterserviceversion.yaml
Labels: approved, lgtm, release-7.9.0

#507 update bundle for 7.9.0
  deploy/olm-catalog/businessautomation-operator/7.9.0/manifests/businessautomation-operator.7.9.0.clusterserviceversion.yaml
  deploy/olm-catalog/kiecloud-operator/7.9.0/manifests/kiecloud-operator.7.9.0.clusterserviceversion.yaml
  hack/go-build-bundle.sh
  image-bundle.yaml
Labels: approved, lgtm, release-7.9.0

#503 [KIECLOUD-422] display admin user & pwd in Operator Hub
  README.md
  deploy/crds/kieapp.crd.yaml
  deploy/olm-catalog/dev/7.9.0/manifests/businessautomation-operator.7.9.0.clusterserviceversion.yaml
  deploy/olm-catalog/prod/7.9.0/manifests/businessautomation-operator.7.9.0.clusterserviceversion.yaml
  pkg/apis/app/v2/kieapp_types.go
  tools/csv-gen/csv-gen.go
Labels: approved, lgtm, release-7.9.0

#509 add resource perms for metrics
  deploy/olm-catalog/dev/7.9.0/manifests/businessautomation-operator.7.9.0.clusterserviceversion.yaml
  deploy/olm-catalog/prod/7.9.0/manifests/businessautomation-operator.7.9.0.clusterserviceversion.yaml
  deploy/role.yaml
  pkg/components/components.go
Labels: approved, lgtm, release-7.9.0

#510 [KIECLOUD-432] - kubernetes.KUBE_PING warning message on logs if the …
  README.md
  config/7.9.0/common.yaml
  config/7.9.0/envs/rhdm-authoring.yaml
  config/7.9.0/envs/rhdm-trial.yaml
  config/7.9.0/envs/rhpam-authoring.yaml
  config/7.9.0/envs/rhpam-trial.yaml
  pkg/controller/kieapp/defaults/defaults_test.go
  pkg/controller/kieapp/defaults/merge_test.go
  pkg/controller/kieapp/defaults/upgrade_test.go
Labels: approved, lgtm

#511 upgrade fix: retain version from applied status
  pkg/controller/kieapp/defaults/defaults.go
  pkg/controller/kieapp/defaults/upgrade_test.go
Labels: approved, lgtm, release-7.9.0

#513 revert admin user/pass from CSV descriptors
  deploy/olm-catalog/dev/7.9.0/manifests/businessautomation-operator.7.9.0.clusterserviceversion.yaml
  deploy/olm-catalog/prod/7.9.0/manifests/businessautomation-operator.7.9.0.clusterserviceversion.yaml
  tools/csv-gen/csv-gen.go
Labels: approved, lgtm, release-7.9.0

#518 format v1beta1 crd
  deploy/crds/kieapp.crd.v1beta1.yaml
Labels: approved, lgtm

#519 fix v1beta1 crd
  deploy/crds/kieapp.crd.v1beta1.yaml
Labels: approved, lgtm

#514 readme changes for bundle test
  README.md
Labels: approved, lgtm

#515 [KIECLOUD-407] - Operator rhpam-production-immutable fails due to Bus…
  config/7.9.0/common.yaml
  config/7.9.0/envs/rhdm-production-immutable.yaml
  deploy/crs/v2/kieapp_rhdm_production-immutable-jms.yaml
  deploy/crs/v2/kieapp_rhdm_production-immutable.yaml
  deploy/crs/v2/kieapp_rhpam_production-immutable-jms.yaml
  deploy/crs/v2/kieapp_rhpam_production-immutable.yaml
  pkg/apis/app/v2/kieapp_types.go
  pkg/apis/app/v2/zz_generated.deepcopy.go
  pkg/controller/kieapp/defaults/auth_test.go
  pkg/controller/kieapp/defaults/defaults.go
  pkg/controller/kieapp/defaults/defaults_test.go
  pkg/controller/kieapp/kieapp_controller.go
  pkg/controller/kieapp/kieapp_controller_test.go
Labels: approved, do-not-merge/hold, lgtm, release-7.9.0

#520 [KIECLOUD-407] - Operator rhpam-production-immutable fails due to Bus…
  pkg/controller/kieapp/defaults/defaults.go
  pkg/controller/kieapp/defaults/defaults_test.go
Labels: approved, lgtm, release-7.9.0

#516 [Bugzilla 1880441] fix InstallModeType failures
  deploy/olm-catalog/dev/7.9.0/manifests/businessautomation-operator.7.9.0.clusterserviceversion.yaml
  deploy/olm-catalog/prod/7.9.0/manifests/businessautomation-operator.7.9.0.clusterserviceversion.yaml
  go.mod
  go.sum
  pkg/apis/addtoscheme_app_apis.go
  pkg/components/components.go
  pkg/controller/kieapp/deploy_ui.go
  pkg/controller/kieapp/deploy_ui_test.go
  pkg/controller/kieapp/kieapp_controller.go
  pkg/controller/kieapp/watch.go
  vendor/github.com/coreos/go-semver/LICENSE
  vendor/github.com/coreos/go-semver/NOTICE
  vendor/github.com/coreos/go-semver/semver/semver.go
  vendor/github.com/coreos/go-semver/semver/sort.go
  vendor/github.com/operator-framework/api/pkg/operators/v1alpha1/installplan_types.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/LICENSE
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/api/apis/operators/doc.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/api/apis/operators/register.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/api/apis/operators/v1alpha1/catalogsource_types.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/api/apis/operators/v1alpha1/clusterserviceversion.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/api/apis/operators/v1alpha1/clusterserviceversion_types.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/api/apis/operators/v1alpha1/doc.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/api/apis/operators/v1alpha1/installplan_types.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/api/apis/operators/v1alpha1/register.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/api/apis/operators/v1alpha1/subscription_types.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/api/apis/operators/v1alpha1/zz_generated.deepcopy.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/.import-restrictions
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/conversion.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/deepcopy.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/defaults.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/doc.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/generated.pb.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/generated.proto
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/marshal.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/register.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/types.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/types_jsonschema.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/zz_generated.conversion.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/zz_generated.deepcopy.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/zz_generated.defaults.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/zz_generated.prerelease-lifecycle.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/scheme/doc.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/scheme/register.go
  vendor/modules.txt
Labels: approved, lgtm, release-7.9.0
