Repository kiegroup/kie-cloud-operator, pull requests merged in 2020-06, with the labels that each got.

#440 [KIECLOUD-395] Enabling the new Simplified mode for Business Central Monitoring console for operator
  config/7.8.0/common.yaml
  pkg/apis/app/v2/kieapp_types.go
  pkg/controller/kieapp/defaults/defaults.go
  pkg/controller/kieapp/defaults/defaults_test.go
Labels: approved, lgtm, ok-to-test, release-7.8.0

#441 [RHPAM-2978] Fix PIM probes
  config/7.8.0/pim/process-migration.yaml
Labels: approved, lgtm

#436 [BAPL-1628] Metering labels for Process Automation
  go.sum
  pkg/controller/kieapp/constants/constants.go
  pkg/controller/kieapp/defaults/defaults.go
  pkg/controller/kieapp/defaults/defaults_test.go
  pkg/controller/kieapp/deploy_ui.go
Labels: approved, lgtm, release-7.8.0

#444 [RHPAM-2998] Add http route for PIM in trial environment
  config/7.8.0/pim/process-migration-trial.yaml
  config/7.8.0/pim/process-migration.yaml
  pkg/controller/kieapp/defaults/defaults.go
  pkg/controller/kieapp/defaults/defaults_test.go
Labels: approved, lgtm, release-7.8.0

#445 [RHPAM-2996] add ssh secret option to console object for githooks
  config/7.8.0/common.yaml
  deploy/crds/kieapp.crd.yaml
  deploy/crs/v2/snippets/githooks.yaml
  deploy/ui/form.json
  pkg/apis/app/v2/kieapp_types.go
  pkg/controller/kieapp/constants/constants.go
  pkg/controller/kieapp/defaults/defaults_test.go
Labels: approved, lgtm, release-7.8.0

#447 increment version to 7.8.1
  config/7.7.0/dbs/mysql.yaml
  config/7.7.0/dbs/postgresql.yaml
  config/7.8.1/common.yaml
  config/7.8.1/dbs/mysql.yaml
  config/7.8.1/dbs/pim/external.yaml
  config/7.8.1/dbs/pim/mysql.yaml
  config/7.8.1/dbs/pim/postgresql.yaml
  config/7.8.1/dbs/postgresql.yaml
  config/7.8.1/dbs/servers/external.yaml
  config/7.8.1/dbs/servers/h2.yaml
  config/7.8.1/dbs/servers/mysql.yaml
  config/7.8.1/dbs/servers/postgresql.yaml
  config/7.8.1/envs/rhdm-authoring-ha.yaml
  config/7.8.1/envs/rhdm-authoring.yaml
  config/7.8.1/envs/rhdm-production-immutable.yaml
  config/7.8.1/envs/rhdm-trial.yaml
  config/7.8.1/envs/rhpam-authoring-ha.yaml
  config/7.8.1/envs/rhpam-authoring.yaml
  config/7.8.1/envs/rhpam-production-immutable.yaml
  config/7.8.1/envs/rhpam-production.yaml
  config/7.8.1/envs/rhpam-trial.yaml
  config/7.8.1/jms/activemq-jms-config.yaml
  config/7.8.1/pim/process-migration-trial.yaml
  config/7.8.1/pim/process-migration.yaml
  deploy/catalog_resources/community/7.8/image-references
  deploy/catalog_resources/community/7.8/kiecloud-operator.7.8.1.clusterserviceversion.yaml
  deploy/catalog_resources/community/kiecloud.package.yaml
  deploy/catalog_resources/redhat/7.8/businessautomation-operator.7.8.1.clusterserviceversion.yaml
  deploy/catalog_resources/redhat/7.8/image-references
  deploy/catalog_resources/redhat/businessautomation.package.yaml
  deploy/crs/v2/snippets/prior_version.yaml
  deploy/operator.yaml
  image-metadata.yaml
  image.yaml
  pkg/controller/kieapp/constants/constants.go
  version/version.go
Labels: approved, lgtm, release-7.8.1

#443 [RHPAM-2752] Add default CPU limit for images to guarantee product performance
  deploy/ui/form.json
  pkg/controller/kieapp/constants/constants.go
  pkg/controller/kieapp/defaults/defaults.go
  pkg/controller/kieapp/defaults/defaults_test.go
Labels: approved, lgtm, release-7.8.1

#448 support ocp 4.4
  go.mod
  go.sum
  vendor/github.com/RHsyseng/operator-utils/internal/platform/platform_versioner.go
  vendor/github.com/RHsyseng/operator-utils/pkg/utils/kubernetes/utils.go
  vendor/modules.txt
Labels: approved, lgtm, release-7.8.0

#449 [cherry-pick] support ocp 4.4
  go.mod
  go.sum
  vendor/github.com/RHsyseng/operator-utils/internal/platform/platform_versioner.go
  vendor/github.com/RHsyseng/operator-utils/pkg/utils/kubernetes/utils.go
  vendor/modules.txt
Labels: approved, lgtm, release-7.8.1

#450 Revert "[RHPAM-2752] Add default CPU limit for images to guarantee product performance"
  deploy/ui/form.json
  pkg/controller/kieapp/constants/constants.go
  pkg/controller/kieapp/defaults/defaults.go
  pkg/controller/kieapp/defaults/defaults_test.go
Labels: approved, lgtm, release-7.8.1
