Repository kiegroup/kie-cloud-operator, pull requests merged in 2020-01, with the labels that each got.

#336 increment to version 7.7.0 / 1.4.0
  config/7.7.0/common.yaml
  config/7.7.0/dbs/external.yaml
  config/7.7.0/dbs/h2.yaml
  config/7.7.0/dbs/mysql.yaml
  config/7.7.0/dbs/postgresql.yaml
  config/7.7.0/envs/rhdm-authoring-ha.yaml
  config/7.7.0/envs/rhdm-authoring.yaml
  config/7.7.0/envs/rhdm-production-immutable.yaml
  config/7.7.0/envs/rhdm-trial.yaml
  config/7.7.0/envs/rhpam-authoring-ha.yaml
  config/7.7.0/envs/rhpam-authoring.yaml
  config/7.7.0/envs/rhpam-production-immutable.yaml
  config/7.7.0/envs/rhpam-production.yaml
  config/7.7.0/envs/rhpam-trial.yaml
  config/7.7.0/jms/activemq-jms-config.yaml
  deploy/catalog_resources/community/1.4.0/kieapp.crd.yaml
  deploy/catalog_resources/community/1.4.0/kiecloud-operator.1.4.0.clusterserviceversion.yaml
  deploy/catalog_resources/community/kiecloud.package.yaml
  deploy/catalog_resources/redhat/1.4.0/businessautomation-operator.1.4.0.clusterserviceversion.yaml
  deploy/catalog_resources/redhat/1.4.0/kieapp.crd.yaml
  deploy/catalog_resources/redhat/businessautomation.package.yaml
  deploy/operator.yaml
  deploy/role.yaml
  pkg/components/components.go
  pkg/controller/kieapp/constants/constants.go
  pkg/controller/kieapp/deploy_ui.go
  version/version.go
Labels: approved, lgtm, release-1.4.0, size/L

#337 mod CI script fixes
  hack/go-mod.sh
Labels: approved, release-1.4.0, size/XS

#305 [RHPAM-2175] Remove controllerUser and executionUser
  config/7.7.0/common.yaml
  deploy/crds/kieapp.crd.yaml
  deploy/examples/v2/auth_ldap_externalOnly.yaml
  deploy/ui/form.json
  pkg/apis/app/v2/kieapp_types.go
  pkg/controller/kieapp/defaults/auth.go
  pkg/controller/kieapp/defaults/auth_test.go
Labels: approved, lgtm, release-1.4.0, size/L

#342 [RHPAM-2175] Use only adminUser
  config/7.7.0/common.yaml
  deploy/crds/kieapp.crd.yaml
  deploy/ui/form.json
  pkg/apis/app/v2/kieapp_types.go
  pkg/controller/kieapp/defaults/defaults_test.go
Labels: approved, lgtm, release-1.4.0, size/M

#343 [RHPAM-2634] Remote Server is lot from the controller after Kie Server scale down and scale up
  config/7.7.0/common.yaml
Labels: approved, lgtm, ok-to-test, release-1.4.0, size/XS

#346 [RHPAM-2533] - External DB driver not working - build config required…
  config/7.7.0/dbs/external.yaml
  deploy/crds/kieapp.crd.yaml
  deploy/examples/v2/server_externaldb_extension_image.yaml
  pkg/apis/app/v2/kieapp_types.go
  pkg/controller/kieapp/constants/constants.go
  pkg/controller/kieapp/defaults/defaults.go
  pkg/controller/kieapp/defaults/defaults_test.go
Labels: approved, lgtm, release-1.4.0, size/L

#347 Merge branch 'master' into release-v1.4.x
  config/7.7.0/common.yaml
  config/7.7.0/dbs/external.yaml
  deploy/crds/kieapp.crd.yaml
  deploy/examples/v2/server_externaldb_extension_image.yaml
  deploy/ui/form.json
  pkg/apis/app/v2/kieapp_types.go
  pkg/controller/kieapp/constants/constants.go
  pkg/controller/kieapp/defaults/defaults.go
  pkg/controller/kieapp/defaults/defaults_test.go
Labels: approved, lgtm, release-1.4.0, size/L

#345 add CI that catches prior version config changes
  hack/go-test.sh
Labels: approved, lgtm, size/S

#349 [RHPAM-2658] Define value as byte
  deploy/catalog_resources/community/1.2.0/kiecloud-operator.1.2.0.clusterserviceversion.yaml
  deploy/catalog_resources/community/1.2.1/kiecloud-operator.1.2.1.clusterserviceversion.yaml
  deploy/catalog_resources/community/1.3.0/kiecloud-operator.1.3.0.clusterserviceversion.yaml
  deploy/catalog_resources/community/1.4.0/kiecloud-operator.1.4.0.clusterserviceversion.yaml
  deploy/catalog_resources/redhat/1.2.0/businessautomation-operator.1.2.0.clusterserviceversion.yaml
  deploy/catalog_resources/redhat/1.2.1/businessautomation-operator.1.2.1.clusterserviceversion.yaml
  deploy/catalog_resources/redhat/1.3.0/businessautomation-operator.1.3.0.clusterserviceversion.yaml
  deploy/catalog_resources/redhat/1.4.0/businessautomation-operator.1.4.0.clusterserviceversion.yaml
  tools/csv-gen/csv-gen.go
  tools/util/marshaller.go
Labels: approved, lgtm, release-1.4.0, size/S

#351 Revert "[RHPAM-2658] Define value as byte"
  deploy/catalog_resources/community/1.2.0/kiecloud-operator.1.2.0.clusterserviceversion.yaml
  deploy/catalog_resources/community/1.2.1/kiecloud-operator.1.2.1.clusterserviceversion.yaml
  deploy/catalog_resources/community/1.3.0/kiecloud-operator.1.3.0.clusterserviceversion.yaml
  deploy/catalog_resources/community/1.4.0/kiecloud-operator.1.4.0.clusterserviceversion.yaml
  deploy/catalog_resources/redhat/1.2.0/businessautomation-operator.1.2.0.clusterserviceversion.yaml
  deploy/catalog_resources/redhat/1.2.1/businessautomation-operator.1.2.1.clusterserviceversion.yaml
  deploy/catalog_resources/redhat/1.3.0/businessautomation-operator.1.3.0.clusterserviceversion.yaml
  deploy/catalog_resources/redhat/1.4.0/businessautomation-operator.1.4.0.clusterserviceversion.yaml
  tools/csv-gen/csv-gen.go
  tools/util/marshaller.go
Labels: approved, lgtm, release-1.4.0, size/S
