Repository kiegroup/kie-cloud-operator, pull requests merged in 2020-07, with the labels that each got.

#453 kie-cloud-operator.tar.gz .gitignore exception for release builds
  .gitignore
  Makefile
Labels: approved, lgtm, release-7.8.0

#452 kie-cloud-operator.tar.gz .gitignore exception for release builds
  .gitignore
  Makefile
Labels: approved, lgtm, release-7.8.1

#455 [KIECLOUD-398] golang 1.13
  README.md
  go.mod
  image.yaml
  vendor/golang.org/x/sys/unix/mkasm_darwin.go
  vendor/golang.org/x/sys/unix/mkpost.go
  vendor/golang.org/x/sys/unix/mksyscall.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc64.go
  vendor/golang.org/x/sys/unix/mksyscall_solaris.go
  vendor/golang.org/x/sys/unix/mksysctl_openbsd.go
  vendor/golang.org/x/sys/unix/mksysnum.go
  vendor/golang.org/x/sys/unix/types_aix.go
  vendor/golang.org/x/sys/unix/types_darwin.go
  vendor/golang.org/x/sys/unix/types_dragonfly.go
  vendor/golang.org/x/sys/unix/types_freebsd.go
  vendor/golang.org/x/sys/unix/types_netbsd.go
  vendor/golang.org/x/sys/unix/types_openbsd.go
  vendor/golang.org/x/sys/unix/types_solaris.go
  vendor/golang.org/x/text/unicode/bidi/gen.go
  vendor/golang.org/x/text/unicode/bidi/gen_ranges.go
  vendor/golang.org/x/text/unicode/bidi/gen_trieval.go
  vendor/golang.org/x/text/unicode/norm/maketables.go
  vendor/golang.org/x/text/unicode/norm/triegen.go
  vendor/golang.org/x/text/width/gen.go
  vendor/golang.org/x/text/width/gen_common.go
  vendor/golang.org/x/text/width/gen_trieval.go
  vendor/golang.org/x/tools/go/gcexportdata/main.go
  vendor/modules.txt
Labels: release-7.8.0

#456 [KIECLOUD-398] golang 1.13
  README.md
  go.mod
  image.yaml
  vendor/golang.org/x/sys/unix/mkasm_darwin.go
  vendor/golang.org/x/sys/unix/mkpost.go
  vendor/golang.org/x/sys/unix/mksyscall.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc64.go
  vendor/golang.org/x/sys/unix/mksyscall_solaris.go
  vendor/golang.org/x/sys/unix/mksysctl_openbsd.go
  vendor/golang.org/x/sys/unix/mksysnum.go
  vendor/golang.org/x/sys/unix/types_aix.go
  vendor/golang.org/x/sys/unix/types_darwin.go
  vendor/golang.org/x/sys/unix/types_dragonfly.go
  vendor/golang.org/x/sys/unix/types_freebsd.go
  vendor/golang.org/x/sys/unix/types_netbsd.go
  vendor/golang.org/x/sys/unix/types_openbsd.go
  vendor/golang.org/x/sys/unix/types_solaris.go
  vendor/golang.org/x/text/unicode/bidi/gen.go
  vendor/golang.org/x/text/unicode/bidi/gen_ranges.go
  vendor/golang.org/x/text/unicode/bidi/gen_trieval.go
  vendor/golang.org/x/text/unicode/norm/maketables.go
  vendor/golang.org/x/text/unicode/norm/triegen.go
  vendor/golang.org/x/text/width/gen.go
  vendor/golang.org/x/text/width/gen_common.go
  vendor/golang.org/x/text/width/gen_trieval.go
  vendor/golang.org/x/tools/go/gcexportdata/main.go
  vendor/modules.txt
Labels: release-7.8.1

#458 keystore patch
  pkg/controller/kieapp/constants/constants.go
  pkg/controller/kieapp/kieapp_controller.go
  pkg/controller/kieapp/kieapp_controller_test.go
  pkg/controller/kieapp/shared/utils.go
  pkg/controller/kieapp/shared/utils_test.go
Labels: approved, lgtm, release-7.8.0

#461 [cherry-pick] keystore patch
  pkg/controller/kieapp/constants/constants.go
  pkg/controller/kieapp/kieapp_controller.go
  pkg/controller/kieapp/kieapp_controller_test.go
  pkg/controller/kieapp/shared/utils.go
  pkg/controller/kieapp/shared/utils_test.go
Labels: release-7.8.1

#457 [cherry-pick] rollback multi-stage for osbs
  .gitignore
  Makefile
  README.md
  build/Dockerfile
  build/bin/entrypoint
  build/bin/user_setup
  deploy/catalog_resources/module.yaml
  hack/go-build.sh
  image.yaml
  modules/builder/install
  modules/kie-cloud-operator/install
  modules/kie-cloud-operator/module.yaml
  modules/runtime/install
  modules/runtime/module.yaml
Labels: release-7.8.1

#464 requeue reconcile on keystore secret error
  pkg/controller/kieapp/kieapp_controller.go
  pkg/controller/kieapp/kieapp_controller_test.go
Labels: release-7.8.1

#465 [cherry-pick] requeue reconcile on keystore secret error
  pkg/controller/kieapp/kieapp_controller.go
  pkg/controller/kieapp/kieapp_controller_test.go
Labels: release-7.8.0

#466 [RHPAM-3041] - In Operator UI users cannot check if they want to deploy…
  deploy/ui/form.json
Labels: approved, lgtm, release-7.8.0

#467 [RHPAM-3041][cherry-pick]-In Operator UI users cannot check if they want to deploy…
  deploy/ui/form.json
Labels: approved, lgtm, release-7.8.1

#468 [RHPAM-3055] Use CR name in the console links
  pkg/controller/kieapp/kieapp_controller.go
  pkg/controller/kieapp/kieapp_controller_test.go
Labels: release-7.8.1

#470 [RHPAM-3083] - Drop not supported External DB configuration for PIM i…
  deploy/crds/kieapp.crd.yaml
  deploy/ui/form.json
Labels: release-7.8.0

#471 [RHPAM-3083] [cherry pick] - Drop not supported External DB configuration for PIM i…
  deploy/crds/kieapp.crd.yaml
  deploy/ui/form.json
Labels: release-7.8.1

#474 move check-configs to separate test
  Makefile
  hack/go-configs.sh
  hack/go-test.sh
Labels: release-7.8.1

#473 move check-configs to separate test
  Makefile
  hack/go-configs.sh
  hack/go-test.sh
Labels: release-7.8.0

#475 move check-configs to separate test
  Makefile
  hack/go-configs.sh
  hack/go-test.sh
Labels: release-7.9.0

#478 fix configs job
  hack/go-configs.sh
Labels: approved, lgtm

#479 fix configs job
  hack/go-configs.sh
Labels: approved, lgtm

#480 Merge branch 'master' into release-v7.9.x
  hack/go-configs.sh
Labels: approved, lgtm

#483 7.8 metadata digests
  deploy/catalog_resources/community/7.8/kiecloud-operator.7.8.0.clusterserviceversion.yaml
  deploy/catalog_resources/redhat/7.8/businessautomation-operator.7.8.0.clusterserviceversion.yaml
Labels: lgtm

#484 7.8 metadata digests
  deploy/catalog_resources/community/7.8/kiecloud-operator.7.8.0.clusterserviceversion.yaml
  deploy/catalog_resources/redhat/7.8/businessautomation-operator.7.8.0.clusterserviceversion.yaml
Labels: release-7.8.1

#485 Merge branch 'master' into release-v7.8.x
  config/7.7.0/dbs/mysql.yaml
  config/7.7.0/dbs/postgresql.yaml
  config/7.8.1/common.yaml
  config/7.8.1/dbs/mysql.yaml
  config/7.8.1/dbs/pim/external.yaml
  config/7.8.1/dbs/pim/mysql.yaml
  config/7.8.1/dbs/pim/postgresql.yaml
  config/7.8.1/dbs/postgresql.yaml
  config/7.8.1/dbs/servers/external.yaml
  config/7.8.1/dbs/servers/h2.yaml
  config/7.8.1/dbs/servers/mysql.yaml
  config/7.8.1/dbs/servers/postgresql.yaml
  config/7.8.1/envs/rhdm-authoring-ha.yaml
  config/7.8.1/envs/rhdm-authoring.yaml
  config/7.8.1/envs/rhdm-production-immutable.yaml
  config/7.8.1/envs/rhdm-trial.yaml
  config/7.8.1/envs/rhpam-authoring-ha.yaml
  config/7.8.1/envs/rhpam-authoring.yaml
  config/7.8.1/envs/rhpam-production-immutable.yaml
  config/7.8.1/envs/rhpam-production.yaml
  config/7.8.1/envs/rhpam-trial.yaml
  config/7.8.1/jms/activemq-jms-config.yaml
  config/7.8.1/pim/process-migration-trial.yaml
  config/7.8.1/pim/process-migration.yaml
  deploy/catalog_resources/community/7.8/image-references
  deploy/catalog_resources/community/7.8/kiecloud-operator.7.8.1.clusterserviceversion.yaml
  deploy/catalog_resources/community/kiecloud.package.yaml
  deploy/catalog_resources/redhat/7.8/businessautomation-operator.7.8.1.clusterserviceversion.yaml
  deploy/catalog_resources/redhat/7.8/image-references
  deploy/catalog_resources/redhat/businessautomation.package.yaml
  deploy/crs/v2/snippets/prior_version.yaml
  deploy/operator.yaml
  image-metadata.yaml
  image.yaml
  pkg/controller/kieapp/constants/constants.go
  pkg/controller/kieapp/kieapp_controller.go
  pkg/controller/kieapp/kieapp_controller_test.go
  version/version.go
Labels: approved, do-not-merge/hold, release-7.8.1

#486 7.9.0 versioning
  config/7.9.0/common.yaml
  config/7.9.0/dbs/mysql.yaml
  config/7.9.0/dbs/pim/external.yaml
  config/7.9.0/dbs/pim/mysql.yaml
  config/7.9.0/dbs/pim/postgresql.yaml
  config/7.9.0/dbs/postgresql.yaml
  config/7.9.0/dbs/servers/external.yaml
  config/7.9.0/dbs/servers/h2.yaml
  config/7.9.0/dbs/servers/mysql.yaml
  config/7.9.0/dbs/servers/postgresql.yaml
  config/7.9.0/envs/rhdm-authoring-ha.yaml
  config/7.9.0/envs/rhdm-authoring.yaml
  config/7.9.0/envs/rhdm-production-immutable.yaml
  config/7.9.0/envs/rhdm-trial.yaml
  config/7.9.0/envs/rhpam-authoring-ha.yaml
  config/7.9.0/envs/rhpam-authoring.yaml
  config/7.9.0/envs/rhpam-production-immutable.yaml
  config/7.9.0/envs/rhpam-production.yaml
  config/7.9.0/envs/rhpam-trial.yaml
  config/7.9.0/jms/activemq-jms-config.yaml
  config/7.9.0/pim/process-migration-trial.yaml
  config/7.9.0/pim/process-migration.yaml
  deploy/catalog_resources/community/7.9/image-references
  deploy/catalog_resources/community/7.9/kiecloud-operator.7.9.0.clusterserviceversion.yaml
  deploy/catalog_resources/community/kiecloud.package.yaml
  deploy/catalog_resources/redhat/7.9/businessautomation-operator.7.9.0.clusterserviceversion.yaml
  deploy/catalog_resources/redhat/7.9/image-references
  deploy/catalog_resources/redhat/businessautomation.package.yaml
  deploy/crs/v2/snippets/prior_version.yaml
  deploy/operator.yaml
  image-metadata.yaml
  image.yaml
  pkg/controller/kieapp/constants/constants.go
  pkg/controller/kieapp/defaults/defaults_test.go
  pkg/controller/kieapp/defaults/upgrade_test.go
Labels: approved, lgtm, release-7.9.0

#487 remove old 7.7.1 configs
  config/7.7.1/common.yaml
  config/7.7.1/dbs/external.yaml
  config/7.7.1/dbs/h2.yaml
  config/7.7.1/dbs/mysql.yaml
  config/7.7.1/dbs/postgresql.yaml
  config/7.7.1/envs/rhdm-authoring-ha.yaml
  config/7.7.1/envs/rhdm-authoring.yaml
  config/7.7.1/envs/rhdm-production-immutable.yaml
  config/7.7.1/envs/rhdm-trial.yaml
  config/7.7.1/envs/rhpam-authoring-ha.yaml
  config/7.7.1/envs/rhpam-authoring.yaml
  config/7.7.1/envs/rhpam-production-immutable.yaml
  config/7.7.1/envs/rhpam-production.yaml
  config/7.7.1/envs/rhpam-trial.yaml
  config/7.7.1/jms/activemq-jms-config.yaml
Labels: approved, release-7.9.0

#462 Revert "rollback multi-stage for osbs"
  .gitignore
  Makefile
  README.md
  build/Dockerfile
  build/bin/entrypoint
  build/bin/user_setup
  deploy/catalog_resources/module.yaml
  hack/go-build.sh
  image.yaml
  modules/builder/install
  modules/builder/module.yaml
  modules/kie-cloud-operator/install
  modules/runtime/install
  modules/runtime/module.yaml
Labels: approved, lgtm, release-7.9.0

#451 [RHPAM-2752] Add default CPU limit for images to guarantee product performance
  deploy/ui/form.json
  pkg/controller/kieapp/constants/constants.go
  pkg/controller/kieapp/defaults/defaults.go
  pkg/controller/kieapp/defaults/defaults_test.go
Labels: approved, lgtm, release-7.9.0

#488 cekit 3.7.x required
  Makefile
  README.md
  deploy/catalog_resources/community/7.9/kieapp.crd.yaml
  deploy/catalog_resources/community/7.9/kiecloud-operator.7.9.0.clusterserviceversion.yaml
  deploy/catalog_resources/redhat/7.9/businessautomation-operator.7.9.0.clusterserviceversion.yaml
  deploy/catalog_resources/redhat/7.9/kieapp.crd.yaml
  hack/go-build-metadata.sh
  image-metadata.yaml
  image.yaml
  modules/runtime/install
  modules/runtime/module.yaml
Labels: approved, lgtm, release-7.9.0

#469 [RHPAM-2746] Set default JVM Max memory ratio to 80% in BA Operator
  pkg/controller/kieapp/defaults/defaults.go
  pkg/controller/kieapp/defaults/defaults_test.go
Labels: approved, lgtm, release-7.9.0
