Repository kiegroup/kie-cloud-operator, pull requests merged in 2020-10, with the labels that each got.

#525 OSBS fix - image build method
  image.yaml
Labels: approved, lgtm, release-7.9.0

#526 Merge branch 'master' into release-v7.9.x
  image.yaml
Labels: approved, lgtm, release-7.9.0

#528 7.9.0 digests
  deploy/olm-catalog/dev/7.9.0/manifests/businessautomation-operator.7.9.0.clusterserviceversion.yaml
  deploy/olm-catalog/prod/7.9.0/manifests/businessautomation-operator.7.9.0.clusterserviceversion.yaml
  go.sum
Labels: approved, lgtm, release-7.9.0

#529 only allow 7.9.0 in ocp4.6+
  image-bundle.yaml
Labels: approved, lgtm, release-7.9.0

#531 Update OWNERS
  OWNERS
Labels: approved, lgtm

#530 [RHDM-1488] - Crash when the console is not configured with SSO (and …
  pkg/controller/kieapp/defaults/auth.go
  pkg/controller/kieapp/defaults/auth_test.go
Labels: approved, lgtm, release-7.9.0

#534 add diff to CI
  hack/go-mod.sh
Labels: approved, lgtm

#536 4.6 index
  README.md
Labels: approved
