Repository kiegroup/kie-cloud-operator, pull requests merged in 2020-12, with the labels that each got.

#561 [RHPAM-3325] reconcile error due to mem conversion and startupProbe
  config/7.9.1/common.yaml
  pkg/controller/kieapp/constants/constants.go
Labels: approved, lgtm, release-7.9.1

#562 [RHPAM-3325] reconcile error due to mem conversion and startupProbe
  config/7.10.0/common.yaml
  config/7.9.1/common.yaml
  pkg/controller/kieapp/constants/constants.go
Labels: approved, release-7.10.0

#564 add 7.9.1 digests
  deploy/olm-catalog/dev/7.9.1/manifests/businessautomation-operator.7.9.1.clusterserviceversion.yaml
  deploy/olm-catalog/prod/7.9.1/manifests/businessautomation-operator.7.9.1.clusterserviceversion.yaml
Labels: approved, lgtm, release-7.9.1

#566 add 7.9.1 digests to master
  deploy/olm-catalog/dev/7.9.1/manifests/businessautomation-operator.7.9.1.clusterserviceversion.yaml
  deploy/olm-catalog/prod/7.9.1/manifests/businessautomation-operator.7.9.1.clusterserviceversion.yaml
Labels: approved, lgtm, release-7.10.0

#563 [RHPAM-3326] - Defaul value for MaxMetaspaceSize in Operator overried…
  pkg/controller/kieapp/defaults/defaults.go
Labels: approved, lgtm, release-7.10.0

#560 [KIECLOUD-474] increase amq version to 7.8
  deploy/olm-catalog/dev/7.10.0/manifests/businessautomation-operator.7.10.0.clusterserviceversion.yaml
  deploy/olm-catalog/prod/7.10.0/manifests/businessautomation-operator.7.10.0.clusterserviceversion.yaml
  deploy/operator.yaml
  pkg/controller/kieapp/constants/constants.go
  tools/csv-gen/csv-gen.go
Labels: approved, lgtm, release-7.10.0

#570 7.9.1 csv updates
  deploy/olm-catalog/dev/7.9.1/manifests/businessautomation-operator.7.9.1.clusterserviceversion.yaml
  deploy/olm-catalog/prod/7.9.1/manifests/businessautomation-operator.7.9.1.clusterserviceversion.yaml
Labels: approved, lgtm, release-7.9.1

#571 7.9.1 csv updates
  deploy/olm-catalog/dev/7.9.1/manifests/businessautomation-operator.7.9.1.clusterserviceversion.yaml
  deploy/olm-catalog/prod/7.9.1/manifests/businessautomation-operator.7.9.1.clusterserviceversion.yaml
Labels: approved, lgtm, release-7.9.1

#568 KIECLOUD-480 - Allowing value flag as "optional" for LdapExtended log…
  config/7.10.0/common.yaml
  deploy/crds/kieapp.crd.yaml
  deploy/ui/form.json
  pkg/apis/app/v2/kieapp_types.go
  pkg/controller/kieapp/defaults/auth_test.go
Labels: approved, lgtm, ok-to-test, release-7.10.0
