Repository kiegroup/kie-cloud-operator, pull requests merged in 2020-02, with the labels that each got.

#353 [RHPAM-2657] KieServer Scale-Up-From-Zero lifecycle hooks logic broken
  config/7.7.0/common.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#354 [BAPL-1507] Add to OpenShift images property for JVM max memory ratio configuration
  config/7.7.0/common.yaml
  deploy/crds/kieapp.crd.yaml
  deploy/examples/v2/jvm_config.yaml
  pkg/apis/app/v2/kieapp_types.go
  pkg/apis/app/v2/zz_generated.deepcopy.go
  pkg/controller/kieapp/defaults/defaults.go
  pkg/controller/kieapp/defaults/defaults_test.go
  vendor/modules.txt
Labels: approved, lgtm, release-1.4.0, size/XL

#355 [RHPAM-2175] Drop EXTERNAL_AUTH_ONLY
  config/7.7.0/common.yaml
  deploy/crds/kieapp.crd.yaml
  deploy/examples/v2/auth_ldap_externalOnly.yaml
  deploy/ui/form.json
  pkg/apis/app/v2/kieapp_types.go
  pkg/controller/kieapp/defaults/auth.go
  pkg/controller/kieapp/defaults/auth_test.go
Labels: approved, lgtm, release-1.4.0, size/L

#356 [BAPL-1507] Add to OpenShift images property for JVM max memory ratio conf
  deploy/ui/form.json
Labels: approved, lgtm, ok-to-test, size/L

#358 [RHPAM-2658] remove specDescripter value
  deploy/catalog_resources/community/1.2.0/kiecloud-operator.1.2.0.clusterserviceversion.yaml
  deploy/catalog_resources/community/1.2.1/kiecloud-operator.1.2.1.clusterserviceversion.yaml
  deploy/catalog_resources/community/1.3.0/kiecloud-operator.1.3.0.clusterserviceversion.yaml
  deploy/catalog_resources/community/1.4.0/kiecloud-operator.1.4.0.clusterserviceversion.yaml
  deploy/catalog_resources/redhat/1.2.0/businessautomation-operator.1.2.0.clusterserviceversion.yaml
  deploy/catalog_resources/redhat/1.2.1/businessautomation-operator.1.2.1.clusterserviceversion.yaml
  deploy/catalog_resources/redhat/1.3.0/businessautomation-operator.1.3.0.clusterserviceversion.yaml
  deploy/catalog_resources/redhat/1.4.0/businessautomation-operator.1.4.0.clusterserviceversion.yaml
  tools/csv-gen/csv-gen.go
Labels: approved, lgtm, release-1.4.0, size/S

#341 [KIECLOUD-358] metadata / disconnected container builds
  Makefile
  config/7.7.0/common.yaml
  config/7.7.0/dbs/mysql.yaml
  config/7.7.0/dbs/postgresql.yaml
  config/7.7.0/envs/rhdm-authoring-ha.yaml
  config/7.7.0/envs/rhpam-authoring-ha.yaml
  deploy/catalog_resources/community/1.4/image-references
  deploy/catalog_resources/community/1.4/kieapp.crd.yaml
  deploy/catalog_resources/community/1.4/kiecloud-operator.1.4.0.clusterserviceversion.yaml
  deploy/catalog_resources/community/kiecloud.package.yaml
  deploy/catalog_resources/install
  deploy/catalog_resources/module.yaml
  deploy/catalog_resources/redhat/1.4/businessautomation-operator.1.4.0.clusterserviceversion.yaml
  deploy/catalog_resources/redhat/1.4/image-references
  deploy/catalog_resources/redhat/1.4/kieapp.crd.yaml
  deploy/catalog_resources/redhat/businessautomation.package.yaml
  deploy/operator.yaml
  go.mod
  go.sum
  hack/go-build-metadata.sh
  hack/go-mod.sh
  image-metadata.yaml
  image.yaml
  modules/kie-cloud-operator/install
  pkg/apis/app/v2/kieapp_types.go
  pkg/components/components.go
  pkg/controller/kieapp/constants/constants.go
  pkg/controller/kieapp/defaults/defaults.go
  pkg/controller/kieapp/defaults/defaults_test.go
  pkg/controller/kieapp/defaults/upgrade.go
  pkg/controller/kieapp/deploy_ui.go
  pkg/controller/kieapp/deploy_ui_test.go
  tools/csv-gen/csv-gen.go
  vendor/github.com/tidwall/gjson/.travis.yml
  vendor/github.com/tidwall/gjson/LICENSE
  vendor/github.com/tidwall/gjson/README.md
  vendor/github.com/tidwall/gjson/SYNTAX.md
  vendor/github.com/tidwall/gjson/gjson.go
  vendor/github.com/tidwall/gjson/gjson_gae.go
  vendor/github.com/tidwall/gjson/gjson_ngae.go
  vendor/github.com/tidwall/gjson/go.mod
  vendor/github.com/tidwall/gjson/go.sum
  vendor/github.com/tidwall/gjson/logo.png
  vendor/github.com/tidwall/match/.travis.yml
  vendor/github.com/tidwall/match/LICENSE
  vendor/github.com/tidwall/match/README.md
  vendor/github.com/tidwall/match/match.go
  vendor/github.com/tidwall/pretty/.travis.yml
  vendor/github.com/tidwall/pretty/LICENSE
  vendor/github.com/tidwall/pretty/README.md
  vendor/github.com/tidwall/pretty/pretty.go
  vendor/github.com/tidwall/sjson/.travis.yml
  vendor/github.com/tidwall/sjson/LICENSE
  vendor/github.com/tidwall/sjson/README.md
  vendor/github.com/tidwall/sjson/logo.png
  vendor/github.com/tidwall/sjson/sjson.go
  vendor/github.com/tidwall/sjson/sjson_gae.go
  vendor/github.com/tidwall/sjson/sjson_ngae.go
  vendor/modules.txt
Labels: approved, lgtm, release-1.4.0, size/XXL

#371 change CI vendoring in script
  hack/go-mod.sh
Labels: approved, lgtm, size/XS

#372 [RHPAM-2723] - LDAP Role recursion binds to wrong variable
  deploy/ui/form.json
Labels: approved, lgtm, ok-to-test, release-1.4.0, size/XS

#373 Merge branch 'master' into release-v1.4.x
  deploy/ui/form.json
  hack/go-mod.sh
Labels: approved, lgtm, release-1.4.0, size/XS

#374 [RHPAM-2726] PersistenceDS for external DB
  config/7.7.0/dbs/external.yaml
Labels: approved, lgtm, release-1.4.0, size/XS

#375 Merge branch 'master' into release-v1.4.x
  config/7.7.0/dbs/external.yaml
Labels: approved, lgtm, release-1.4.0, size/XS

#376 [BAPL-1507] - Add to OpenShift images property for JVM configurations
  deploy/ui/form.json
Labels: approved, lgtm, ok-to-test, size/M

#377 Merge master into release-1.4.x
  deploy/ui/form.json
Labels: approved, lgtm, release-1.4.0, size/M

#378 [BAPL-1507] remove ContainerCoreLimit and ContainerMaxMemory
  config/7.7.0/common.yaml
  deploy/crds/kieapp.crd.yaml
  pkg/apis/app/v2/kieapp_types.go
  pkg/apis/app/v2/zz_generated.deepcopy.go
  pkg/controller/kieapp/defaults/defaults_test.go
Labels: approved, lgtm, size/M

#379 Merge branch 'master' into release-v1.4.x
  config/7.7.0/common.yaml
  deploy/crds/kieapp.crd.yaml
  pkg/apis/app/v2/kieapp_types.go
  pkg/apis/app/v2/zz_generated.deepcopy.go
  pkg/controller/kieapp/defaults/defaults_test.go
Labels: approved, lgtm, size/M

#381 add DIGESTS flag for make csv
  README.md
  deploy/catalog_resources/community/1.4/kiecloud-operator.1.4.0.clusterserviceversion.yaml
  deploy/catalog_resources/redhat/1.4/businessautomation-operator.1.4.0.clusterserviceversion.yaml
  tools/csv-gen/csv-gen.go
Labels: approved, lgtm, size/L

#380 [KIECLOUD-367] - Operator Hub catalog changes
  deploy/catalog_resources/community/1.4/kiecloud-operator.1.4.0.clusterserviceversion.yaml
  deploy/catalog_resources/redhat/1.4/businessautomation-operator.1.4.0.clusterserviceversion.yaml
  tools/csv-gen/csv-gen.go
Labels: approved, lgtm, ok-to-test, release-1.4.0, size/L

#382 Merge branch 'master' into release-v1.4.x
  README.md
  deploy/catalog_resources/community/1.4/kiecloud-operator.1.4.0.clusterserviceversion.yaml
  deploy/catalog_resources/redhat/1.4/businessautomation-operator.1.4.0.clusterserviceversion.yaml
  tools/csv-gen/csv-gen.go
Labels: approved, lgtm, release-1.4.0, size/L
