Repository kiegroup/kie-cloud-operator, pull requests merged in 2020-03, with the labels that each got.

#383 [RHPAM-2533] - External DB driver not working - build config required…
  config/7.7.0/dbs/external.yaml
Labels: approved, lgtm, size/XS

#384 Merge branch 'master' into release-v1.4.x
  config/7.7.0/dbs/external.yaml
Labels: approved, lgtm, release-1.4.0, size/XS

#387 [KIECLOUD-349] increment versioning and change image version format
  README.md
  config/7.8.0/common.yaml
  config/7.8.0/dbs/external.yaml
  config/7.8.0/dbs/h2.yaml
  config/7.8.0/dbs/mysql.yaml
  config/7.8.0/dbs/postgresql.yaml
  config/7.8.0/envs/rhdm-authoring-ha.yaml
  config/7.8.0/envs/rhdm-authoring.yaml
  config/7.8.0/envs/rhdm-production-immutable.yaml
  config/7.8.0/envs/rhdm-trial.yaml
  config/7.8.0/envs/rhpam-authoring-ha.yaml
  config/7.8.0/envs/rhpam-authoring.yaml
  config/7.8.0/envs/rhpam-production-immutable.yaml
  config/7.8.0/envs/rhpam-production.yaml
  config/7.8.0/envs/rhpam-trial.yaml
  config/7.8.0/jms/activemq-jms-config.yaml
  deploy/catalog_resources/community/7.8/image-references
  deploy/catalog_resources/community/7.8/kieapp.crd.yaml
  deploy/catalog_resources/community/7.8/kiecloud-operator.7.8.0.clusterserviceversion.yaml
  deploy/catalog_resources/community/kiecloud.package.yaml
  deploy/catalog_resources/redhat/7.8/businessautomation-operator.7.8.0.clusterserviceversion.yaml
  deploy/catalog_resources/redhat/7.8/image-references
  deploy/catalog_resources/redhat/7.8/kieapp.crd.yaml
  deploy/catalog_resources/redhat/businessautomation.package.yaml
  deploy/operator.yaml
  getversion.go
  hack/go-build.sh
  hack/go-test.sh
  pkg/controller/kieapp/constants/constants.go
  pkg/controller/kieapp/defaults/defaults_test.go
  version/version.go
Labels: approved, lgtm, release-7.8.0, size/XXL

#388 [KIECLOUD-349] versioning changes & remove old 7.5.1 configs
  config/7.5.1/common.yaml
  config/7.5.1/dbs/external.yaml
  config/7.5.1/dbs/h2.yaml
  config/7.5.1/dbs/mysql.yaml
  config/7.5.1/dbs/postgresql.yaml
  config/7.5.1/envs/rhdm-authoring-ha.yaml
  config/7.5.1/envs/rhdm-authoring.yaml
  config/7.5.1/envs/rhdm-production-immutable.yaml
  config/7.5.1/envs/rhdm-trial.yaml
  config/7.5.1/envs/rhpam-authoring-ha.yaml
  config/7.5.1/envs/rhpam-authoring.yaml
  config/7.5.1/envs/rhpam-production-immutable.yaml
  config/7.5.1/envs/rhpam-production.yaml
  config/7.5.1/envs/rhpam-trial.yaml
  config/7.5.1/jms/activemq-jms-config.yaml
  deploy/catalog_resources/community/7.8/kiecloud-operator.7.8.0.clusterserviceversion.yaml
  deploy/catalog_resources/redhat/7.8/businessautomation-operator.7.8.0.clusterserviceversion.yaml
  pkg/controller/kieapp/constants/constants.go
  pkg/controller/kieapp/defaults/defaults_test.go
  pkg/controller/kieapp/defaults/upgrade_test.go
Labels: approved, release-7.8.0, size/XXL

#352 [RHPAM-2694] Create ServiceMonitor for operator metrics
  cmd/manager/main.go
  pkg/apis/addtoscheme_app_apis.go
Labels: approved, lgtm, release-7.8.0, size/S

#391 [KIECLOUD-373] remove all wildcard perm references
  deploy/catalog_resources/community/7.8/kiecloud-operator.7.8.0.clusterserviceversion.yaml
  deploy/catalog_resources/redhat/7.8/businessautomation-operator.7.8.0.clusterserviceversion.yaml
  deploy/role.yaml
  pkg/components/components.go
Labels: approved, lgtm, release-7.8.0

#390 [RHPAM-2684] Adapt to operator-sdk 0.14.1 scaffolding
  cmd/manager/main.go
  cmd/ui/main.go
  vendor/github.com/operator-framework/operator-sdk/pkg/restmapper/dynamicrestmapper.go
  vendor/modules.txt
Labels: approved, lgtm, release-7.8.0

#365 [RHPAM-2684] Add NamespaceDashboard ConsoleLink
  deploy/cluster_role.yaml
  deploy/cluster_role_binding.yaml
  pkg/apis/addtoscheme_app_apis.go
  pkg/apis/app/v2/kieapp_types.go
  pkg/components/components.go
  pkg/controller/initializer.go
  pkg/controller/kieapp/constants/constants.go
  pkg/controller/kieapp/kieapp_controller.go
  pkg/controller/kieapp/kieapp_controller_test.go
  pkg/controller/kieapp/test/mock_service.go
  tools/csv-gen/csv-gen.go
  vendor/github.com/openshift/api/console/v1/0000_10_consoleclidownload.crd.yaml
  vendor/github.com/openshift/api/console/v1/0000_10_consoleexternalloglink.crd.yaml
  vendor/github.com/openshift/api/console/v1/0000_10_consolelink.crd.yaml
  vendor/github.com/openshift/api/console/v1/0000_10_consolenotification.crd.yaml
  vendor/github.com/openshift/api/console/v1/0000_10_consoleyamlsample.crd.yaml
  vendor/github.com/openshift/api/console/v1/doc.go
  vendor/github.com/openshift/api/console/v1/register.go
  vendor/github.com/openshift/api/console/v1/types.go
  vendor/github.com/openshift/api/console/v1/types_console_cli_download.go
  vendor/github.com/openshift/api/console/v1/types_console_external_log_links.go
  vendor/github.com/openshift/api/console/v1/types_console_link.go
  vendor/github.com/openshift/api/console/v1/types_console_notification.go
  vendor/github.com/openshift/api/console/v1/types_console_yaml_sample.go
  vendor/github.com/openshift/api/console/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/console/v1/zz_generated.swagger_doc_generated.go
  vendor/modules.txt
Labels: approved, lgtm, release-7.8.0, size/XXL

#392 [RHPAM-2684] add cluster role to bundle
  deploy/catalog_resources/community/7.8/kiecloud-operator.7.8.0.clusterserviceversion.yaml
  deploy/catalog_resources/redhat/7.8/businessautomation-operator.7.8.0.clusterserviceversion.yaml
Labels: approved, release-7.8.0

#395 [RCM-78012] add image digests for 7.7.0 release & remove PIM image
  deploy/catalog_resources/community/1.4/image-references
  deploy/catalog_resources/community/1.4/kiecloud-operator.1.4.0.clusterserviceversion.yaml
  deploy/catalog_resources/redhat/1.4/businessautomation-operator.1.4.0.clusterserviceversion.yaml
  deploy/catalog_resources/redhat/1.4/image-references
  deploy/operator.yaml
  pkg/controller/kieapp/constants/constants.go
Labels: approved, lgtm, release-1.4.0

#398 change metadata package name
  image-metadata.yaml
Labels: approved, release-1.4.0

#399 change metadata package name
  image-metadata.yaml
Labels: approved, lgtm

#402 BXMSPROD-708: add CVP checks configuration file
  image.yaml
  osbs-extra/gating.yaml
Labels: approved, lgtm, ok-to-test

#396 [RHPAM-2803] add image digests for 7.7.0 release & remove PIM images
  deploy/catalog_resources/community/1.4/image-references
  deploy/catalog_resources/community/1.4/kiecloud-operator.1.4.0.clusterserviceversion.yaml
  deploy/catalog_resources/redhat/1.4/businessautomation-operator.1.4.0.clusterserviceversion.yaml
  deploy/catalog_resources/redhat/1.4/image-references
  deploy/operator.yaml
  pkg/controller/kieapp/constants/constants.go
Labels: approved, lgtm, release-7.8.0

#401 fix version in cekit files
  image-metadata.yaml
  image.yaml
Labels: approved, lgtm, release-7.8.0

#404 fix csv and vendor dir
  deploy/catalog_resources/community/7.8/image-references
  deploy/catalog_resources/community/7.8/kiecloud-operator.7.8.0.clusterserviceversion.yaml
  deploy/catalog_resources/redhat/7.8/businessautomation-operator.7.8.0.clusterserviceversion.yaml
  deploy/catalog_resources/redhat/7.8/image-references
  deploy/operator.yaml
  vendor/golang.org/x/sys/unix/mkasm_darwin.go
  vendor/golang.org/x/sys/unix/mkpost.go
  vendor/golang.org/x/sys/unix/mksyscall.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc64.go
  vendor/golang.org/x/sys/unix/mksyscall_solaris.go
  vendor/golang.org/x/sys/unix/mksysctl_openbsd.go
  vendor/golang.org/x/sys/unix/mksysnum.go
  vendor/golang.org/x/sys/unix/types_aix.go
  vendor/golang.org/x/sys/unix/types_darwin.go
  vendor/golang.org/x/sys/unix/types_dragonfly.go
  vendor/golang.org/x/sys/unix/types_freebsd.go
  vendor/golang.org/x/sys/unix/types_netbsd.go
  vendor/golang.org/x/sys/unix/types_openbsd.go
  vendor/golang.org/x/sys/unix/types_solaris.go
  vendor/golang.org/x/text/unicode/bidi/gen.go
  vendor/golang.org/x/text/unicode/bidi/gen_ranges.go
  vendor/golang.org/x/text/unicode/bidi/gen_trieval.go
  vendor/golang.org/x/text/unicode/norm/maketables.go
  vendor/golang.org/x/text/unicode/norm/triegen.go
  vendor/golang.org/x/text/width/gen.go
  vendor/golang.org/x/text/width/gen_common.go
  vendor/golang.org/x/text/width/gen_trieval.go
  vendor/golang.org/x/tools/go/gcexportdata/main.go
  vendor/modules.txt
Labels: approved, lgtm, release-7.8.0

#397 [RHPAM-2684] Use same pattern as for other resources
  cmd/manager/main.go
  cmd/ui/main.go
  go.mod
  go.sum
  pkg/apis/app/v2/kieapp_types.go
  pkg/controller/initializer.go
  pkg/controller/kieapp/constants/constants.go
  pkg/controller/kieapp/kieapp_controller.go
  pkg/controller/kieapp/kieapp_controller_test.go
  vendor/github.com/RHsyseng/operator-utils/pkg/resource/write/writer.go
  vendor/github.com/RHsyseng/operator-utils/pkg/utils/kubernetes/finalizer.go
Labels: approved, release-7.8.0

#405 [KIECLOUD-373] fix console role perms
  pkg/controller/kieapp/deploy_ui.go
  pkg/controller/kieapp/kieapp_controller.go
  vendor/modules.txt
Labels: approved, lgtm, release-7.8.0

#393 [KIECLOUD-378] Increase AMQ broker version to 7.6
  deploy/catalog_resources/community/7.8/kiecloud-operator.7.8.0.clusterserviceversion.yaml
  deploy/catalog_resources/redhat/7.8/businessautomation-operator.7.8.0.clusterserviceversion.yaml
  deploy/operator.yaml
  pkg/controller/kieapp/constants/constants.go
Labels: approved, lgtm, release-7.8.0

#406 fix crd schema
  Makefile
  deploy/crds/kieapp.crd.yaml
  vendor/modules.txt
Labels: approved, lgtm, release-7.8.0

#408 [KIECLOUD-379] move to cekit 3.6.x for multi-stage builds
  README.md
  build/Dockerfile
  build/bin/entrypoint
  build/bin/user_setup
  deploy/catalog_resources/module.yaml
  hack/go-build.sh
  image.yaml
  modules/builder/install
  modules/builder/module.yaml
  modules/kie-cloud-operator/install
  modules/runtime/install
  modules/runtime/module.yaml
Labels: approved, lgtm, release-7.8.0

#410 increment release-v1.4.x to 1.4.1 / 7.7.1
  config/7.7.1/common.yaml
  config/7.7.1/dbs/external.yaml
  config/7.7.1/dbs/h2.yaml
  config/7.7.1/dbs/mysql.yaml
  config/7.7.1/dbs/postgresql.yaml
  config/7.7.1/envs/rhdm-authoring-ha.yaml
  config/7.7.1/envs/rhdm-authoring.yaml
  config/7.7.1/envs/rhdm-production-immutable.yaml
  config/7.7.1/envs/rhdm-trial.yaml
  config/7.7.1/envs/rhpam-authoring-ha.yaml
  config/7.7.1/envs/rhpam-authoring.yaml
  config/7.7.1/envs/rhpam-production-immutable.yaml
  config/7.7.1/envs/rhpam-production.yaml
  config/7.7.1/envs/rhpam-trial.yaml
  config/7.7.1/jms/activemq-jms-config.yaml
  deploy/catalog_resources/community/1.4/image-references
  deploy/catalog_resources/community/1.4/kiecloud-operator.1.4.1.clusterserviceversion.yaml
  deploy/catalog_resources/community/kiecloud.package.yaml
  deploy/catalog_resources/redhat/1.4/businessautomation-operator.1.4.1.clusterserviceversion.yaml
  deploy/catalog_resources/redhat/1.4/image-references
  deploy/catalog_resources/redhat/businessautomation.package.yaml
  deploy/operator.yaml
  image-metadata.yaml
  image.yaml
  pkg/controller/kieapp/constants/constants.go
  pkg/controller/kieapp/defaults/defaults_test.go
  version/version.go
Labels: approved, release-1.4.1
