Repository kiegroup/kie-cloud-operator, pull requests merged in 2020-08, with the labels that each got.

#495 Add disconnected annotation
  deploy/catalog_resources/community/7.9/kiecloud-operator.7.9.0.clusterserviceversion.yaml
  deploy/catalog_resources/redhat/7.9/businessautomation-operator.7.9.0.clusterserviceversion.yaml
  tools/csv-gen/csv-gen.go
Labels: approved, lgtm, release-7.9.0

#494 Add disconnected annotation
  deploy/catalog_resources/community/7.8/kiecloud-operator.7.8.1.clusterserviceversion.yaml
  deploy/catalog_resources/redhat/7.8/businessautomation-operator.7.8.1.clusterserviceversion.yaml
  tools/csv-gen/csv-gen.go
Labels: approved, lgtm, release-7.8.1

#493 [KIECLOUD-417] Use sdk to generate KieApp CRD
  .gitignore
  deploy/crds/kieapp.crd.yaml
  hack/go-sdk-gen.sh
  pkg/apis/app/v2/kieapp_types.go
  pkg/apis/app/v2/zz_generated.deepcopy.go
  pkg/controller/kieapp/defaults/auth_test.go
  pkg/controller/kieapp/defaults/defaults.go
  pkg/controller/kieapp/defaults/defaults_test.go
  pkg/controller/kieapp/kieapp_controller.go
  pkg/controller/kieapp/kieapp_controller_test.go
  pkg/controller/kieapp/test/crd_validation_test.go
Labels: approved, lgtm, release-7.9.0

#491 reconcile cleanup
  pkg/controller/kieapp/defaults/defaults.go
  pkg/controller/kieapp/defaults/defaults_test.go
  pkg/controller/kieapp/kieapp_controller.go
Labels: approved, lgtm, release-7.9.0

#497 [KIECLOUD-414] - Increase DataGrid 7.3 image tag version to 1.6
  deploy/catalog_resources/community/7.9/image-references
  deploy/catalog_resources/community/7.9/kiecloud-operator.7.9.0.clusterserviceversion.yaml
  deploy/catalog_resources/redhat/7.9/businessautomation-operator.7.9.0.clusterserviceversion.yaml
  deploy/catalog_resources/redhat/7.9/image-references
  deploy/operator.yaml
  go.sum
  pkg/controller/kieapp/constants/constants.go
  tools/csv-gen/csv-gen.go
Labels: approved, lgtm, release-7.9.0

#498 remove no longer used datagrid73-openshift:1.3 from csv
  deploy/catalog_resources/community/7.9/image-references
  deploy/catalog_resources/community/7.9/kiecloud-operator.7.9.0.clusterserviceversion.yaml
  deploy/catalog_resources/redhat/7.9/businessautomation-operator.7.9.0.clusterserviceversion.yaml
  deploy/catalog_resources/redhat/7.9/image-references
  pkg/controller/kieapp/constants/constants.go
  tools/csv-gen/csv-gen.go
Labels: approved, lgtm, release-7.9.0

#499 [KIECLOUD-413] - Increase AMQ broker version to 7.7
  deploy/catalog_resources/community/7.9/image-references
  deploy/catalog_resources/community/7.9/kiecloud-operator.7.9.0.clusterserviceversion.yaml
  deploy/catalog_resources/redhat/7.9/businessautomation-operator.7.9.0.clusterserviceversion.yaml
  deploy/catalog_resources/redhat/7.9/image-references
  deploy/operator.yaml
  pkg/controller/kieapp/constants/constants.go
  tools/csv-gen/csv-gen.go
Labels: approved, lgtm

#502 [KIECLOUD-420] - Improve the AUTH_LDAP_URL description by adding the …
  deploy/crds/kieapp.crd.yaml
  deploy/ui/form.json
  pkg/apis/app/v2/kieapp_types.go
Labels: approved, lgtm, release-7.9.0

#460 [RHPAM 2979] Add option for user set custom context image on Operator and UI
  deploy/crds/kieapp.crd.yaml
  deploy/crs/v2/snippets/custom_images_registry.yaml
  deploy/ui/form.json
  pkg/apis/app/v2/kieapp_types.go
  pkg/controller/kieapp/constants/constants.go
  pkg/controller/kieapp/defaults/defaults.go
  pkg/controller/kieapp/defaults/defaults_test.go
  pkg/controller/kieapp/kieapp_controller.go
  pkg/controller/kieapp/kieapp_controller_test.go
Labels: approved, release-7.9.0
