Repository kiegroup/kie-cloud-operator, pull requests merged in 2020-04, with the labels that each got.

#409 [RHPAM-2724] - Increase DataGrid 7.3 image tag version to 1.5
  deploy/catalog_resources/community/1.4/image-references
  deploy/catalog_resources/community/1.4/kiecloud-operator.1.4.1.clusterserviceversion.yaml
  deploy/catalog_resources/redhat/1.4/businessautomation-operator.1.4.1.clusterserviceversion.yaml
  deploy/catalog_resources/redhat/1.4/image-references
  deploy/operator.yaml
  pkg/controller/kieapp/constants/constants.go
  tools/csv-gen/csv-gen.go
Labels: approved, lgtm, release-1.4.1

#407 [RHPAM-2724] - Increase DataGrid 7.3 image tag version to 1.5
  deploy/catalog_resources/community/7.8/image-references
  deploy/catalog_resources/community/7.8/kiecloud-operator.7.8.0.clusterserviceversion.yaml
  deploy/catalog_resources/redhat/7.8/businessautomation-operator.7.8.0.clusterserviceversion.yaml
  deploy/catalog_resources/redhat/7.8/image-references
  deploy/operator.yaml
  pkg/controller/kieapp/constants/constants.go
  tools/csv-gen/csv-gen.go
Labels: approved, lgtm, release-7.8.0

#412 [RHPAM-2750] fix oauth proxy versioning/errors and add ocp version detection
  deploy/catalog_resources/community/7.8/image-references
  deploy/catalog_resources/community/7.8/kiecloud-operator.7.8.0.clusterserviceversion.yaml
  deploy/catalog_resources/redhat/7.8/businessautomation-operator.7.8.0.clusterserviceversion.yaml
  deploy/catalog_resources/redhat/7.8/image-references
  deploy/operator.yaml
  go.mod
  go.sum
  pkg/apis/app/v2/kieapp_types.go
  pkg/components/components.go
  pkg/controller/initializer.go
  pkg/controller/kieapp/constants/constants.go
  pkg/controller/kieapp/defaults/defaults.go
  pkg/controller/kieapp/deploy_ui.go
  pkg/controller/kieapp/deploy_ui_test.go
  pkg/controller/kieapp/kieapp_controller.go
  tools/csv-gen/csv-gen.go
  vendor/github.com/RHsyseng/operator-utils/pkg/utils/openshift/utils.go
  vendor/modules.txt
Labels: approved, lgtm, release-7.8.0

#414 [RHPAM-2750] additional tests and service annotation fix
  pkg/controller/initializer.go
  pkg/controller/kieapp/deploy_ui.go
  pkg/controller/kieapp/deploy_ui_test.go
  pkg/controller/kieapp/shared/utils.go
  tools/csv-gen/csv-gen.go
Labels: approved, lgtm, release-7.8.0

#413 [KIECLOUD-382] modify brew digest retrieval to use stage registry
  README.md
  deploy/catalog_resources/community/7.8/kiecloud-operator.7.8.0.clusterserviceversion.yaml
  deploy/catalog_resources/redhat/7.8/businessautomation-operator.7.8.0.clusterserviceversion.yaml
  tools/csv-gen/csv-gen.go
Labels: approved, lgtm, release-7.8.0

#416 add storageClassName to console
  deploy/ui/form.json
Labels: approved, lgtm

#418 VersionCheck for YAML Samples
  go.mod
  go.sum
  pkg/controller/initializer.go
  vendor/github.com/RHsyseng/operator-utils/internal/platform/platform_versioner.go
  vendor/github.com/RHsyseng/operator-utils/internal/platform/types.go
  vendor/github.com/RHsyseng/operator-utils/pkg/utils/openshift/utils.go
  vendor/modules.txt
Labels: approved, lgtm, ok-to-test

#324 [RHPAM-2435] PIM - Operator Integration
  config/7.8.0/dbs/mysql.yaml
  config/7.8.0/dbs/pim/external.yaml
  config/7.8.0/dbs/pim/mysql.yaml
  config/7.8.0/dbs/pim/postgresql.yaml
  config/7.8.0/dbs/postgresql.yaml
  config/7.8.0/dbs/servers/external.yaml
  config/7.8.0/dbs/servers/h2.yaml
  config/7.8.0/dbs/servers/mysql.yaml
  config/7.8.0/dbs/servers/postgresql.yaml
  config/7.8.0/pim/process-migration.yaml
  deploy/catalog_resources/community/7.8/image-references
  deploy/catalog_resources/community/7.8/kiecloud-operator.7.8.0.clusterserviceversion.yaml
  deploy/catalog_resources/redhat/7.8/businessautomation-operator.7.8.0.clusterserviceversion.yaml
  deploy/catalog_resources/redhat/7.8/image-references
  deploy/crds/kieapp.crd.yaml
  deploy/examples/v2/process_migration.yaml
  deploy/examples/v2/process_migration_externaldb.yaml
  deploy/operator.yaml
  pkg/apis/app/v2/kieapp_types.go
  pkg/apis/app/v2/zz_generated.deepcopy.go
  pkg/controller/kieapp/constants/constants.go
  pkg/controller/kieapp/defaults/defaults.go
  pkg/controller/kieapp/defaults/defaults_test.go
  pkg/controller/kieapp/defaults/merge.go
  pkg/controller/kieapp/defaults/merge_test.go
  pkg/controller/kieapp/kieapp_controller.go
  pkg/controller/kieapp/kieapp_controller_test.go
  pkg/controller/kieapp/test/mock_service.go
Labels: approved, lgtm, ok-to-test, release-7.8.0, size/XXL

#420 [RHPAM-2497] - PIM - Operator console integration
  deploy/ui/form.json
Labels: approved, lgtm, ok-to-test

#421 [KIECLOUD-376] add generated section to KieApp status
  README.md
  config/7.8.0/common.yaml
  deploy/catalog_resources/community/7.8/kiecloud-operator.7.8.0.clusterserviceversion.yaml
  deploy/catalog_resources/redhat/7.8/businessautomation-operator.7.8.0.clusterserviceversion.yaml
  deploy/crds/kieapp.crd.yaml
  go.sum
  hack/go-fmt.sh
  pkg/apis/app/v2/kieapp_types.go
  pkg/apis/app/v2/status.go
  pkg/apis/app/v2/zz_generated.deepcopy.go
  pkg/components/components.go
  pkg/controller/kieapp/defaults/auth.go
  pkg/controller/kieapp/defaults/auth_test.go
  pkg/controller/kieapp/defaults/defaults.go
  pkg/controller/kieapp/defaults/defaults_test.go
  pkg/controller/kieapp/defaults/merge_test.go
  pkg/controller/kieapp/defaults/upgrade.go
  pkg/controller/kieapp/defaults/upgrade_test.go
  pkg/controller/kieapp/deploy_ui_test.go
  pkg/controller/kieapp/kieapp_controller.go
  pkg/controller/kieapp/kieapp_controller_test.go
  pkg/controller/kieapp/status/status.go
  pkg/controller/kieapp/status/status_test.go
  tools/csv-gen/csv-gen.go
  vendor/modules.txt
Labels: approved, lgtm, release-7.8.0

#422 add default apiversion to fieldRef
  config/7.7.1/common.yaml
Labels: approved, lgtm

#423 cherry-pick: add default apiversion to fieldRef
  config/7.7.1/common.yaml
Labels: approved, lgtm

#424 [KIECLOUD-376] move to status.applied
  pkg/apis/app/v2/status.go
  pkg/apis/app/v2/zz_generated.deepcopy.go
  pkg/controller/kieapp/defaults/auth.go
  pkg/controller/kieapp/defaults/defaults.go
  pkg/controller/kieapp/defaults/defaults_test.go
  pkg/controller/kieapp/defaults/merge_test.go
  pkg/controller/kieapp/defaults/upgrade.go
  pkg/controller/kieapp/defaults/upgrade_test.go
  pkg/controller/kieapp/kieapp_controller.go
  pkg/controller/kieapp/kieapp_controller_test.go
  pkg/controller/kieapp/status/status.go
  pkg/controller/kieapp/status/status_test.go
Labels: approved, lgtm, release-7.8.0
