Repository kiegroup/kie-cloud-operator, pull requests merged in 2020-11, with the labels that each got.

#538 7.9.0CR2 digests
  deploy/olm-catalog/dev/7.9.0/manifests/businessautomation-operator.7.9.0.clusterserviceversion.yaml
  deploy/olm-catalog/prod/7.9.0/manifests/businessautomation-operator.7.9.0.clusterserviceversion.yaml
Labels: approved, release-7.9.0

#539 Merge branch 'master' into release-v7.9.x
  deploy/olm-catalog/dev/7.9.0/manifests/businessautomation-operator.7.9.0.clusterserviceversion.yaml
  deploy/olm-catalog/prod/7.9.0/manifests/businessautomation-operator.7.9.0.clusterserviceversion.yaml
Labels: approved, release-7.9.0

#535 7.9.1 version
  config/7.9.1/common.yaml
  config/7.9.1/dbs/mysql.yaml
  config/7.9.1/dbs/pim/external.yaml
  config/7.9.1/dbs/pim/mysql.yaml
  config/7.9.1/dbs/pim/postgresql.yaml
  config/7.9.1/dbs/postgresql.yaml
  config/7.9.1/dbs/servers/external.yaml
  config/7.9.1/dbs/servers/h2.yaml
  config/7.9.1/dbs/servers/mysql.yaml
  config/7.9.1/dbs/servers/postgresql.yaml
  config/7.9.1/envs/rhdm-authoring-ha.yaml
  config/7.9.1/envs/rhdm-authoring.yaml
  config/7.9.1/envs/rhdm-production-immutable.yaml
  config/7.9.1/envs/rhdm-trial.yaml
  config/7.9.1/envs/rhpam-authoring-ha.yaml
  config/7.9.1/envs/rhpam-authoring.yaml
  config/7.9.1/envs/rhpam-production-immutable.yaml
  config/7.9.1/envs/rhpam-production.yaml
  config/7.9.1/envs/rhpam-trial.yaml
  config/7.9.1/jms/activemq-jms-config.yaml
  config/7.9.1/pim/process-migration-trial.yaml
  config/7.9.1/pim/process-migration.yaml
  deploy/crs/v2/snippets/prior_version.yaml
  deploy/olm-catalog/dev/7.9.1/manifests/businessautomation-operator.7.9.1.clusterserviceversion.yaml
  deploy/olm-catalog/dev/7.9.1/manifests/kieapp.crd.yaml
  deploy/olm-catalog/dev/7.9.1/metadata/annotations.yaml
  deploy/olm-catalog/prod/7.9.1/manifests/businessautomation-operator.7.9.1.clusterserviceversion.yaml
  deploy/olm-catalog/prod/7.9.1/manifests/kieapp.crd.yaml
  deploy/olm-catalog/prod/7.9.1/metadata/annotations.yaml
  deploy/operator.yaml
  go.sum
  pkg/controller/kieapp/constants/constants.go
Labels: approved, lgtm, release-7.9.1

#540 remove 7.8.0 configs
  config/7.8.0/common.yaml
  config/7.8.0/dbs/mysql.yaml
  config/7.8.0/dbs/pim/external.yaml
  config/7.8.0/dbs/pim/mysql.yaml
  config/7.8.0/dbs/pim/postgresql.yaml
  config/7.8.0/dbs/postgresql.yaml
  config/7.8.0/dbs/servers/external.yaml
  config/7.8.0/dbs/servers/h2.yaml
  config/7.8.0/dbs/servers/mysql.yaml
  config/7.8.0/dbs/servers/postgresql.yaml
  config/7.8.0/envs/rhdm-authoring-ha.yaml
  config/7.8.0/envs/rhdm-authoring.yaml
  config/7.8.0/envs/rhdm-production-immutable.yaml
  config/7.8.0/envs/rhdm-trial.yaml
  config/7.8.0/envs/rhpam-authoring-ha.yaml
  config/7.8.0/envs/rhpam-authoring.yaml
  config/7.8.0/envs/rhpam-production-immutable.yaml
  config/7.8.0/envs/rhpam-production.yaml
  config/7.8.0/envs/rhpam-trial.yaml
  config/7.8.0/jms/activemq-jms-config.yaml
  config/7.8.0/pim/process-migration-trial.yaml
  config/7.8.0/pim/process-migration.yaml
Labels: approved, lgtm, release-7.9.1

#533 [RHPAM-3245] - Change resource requirements for BC and KIE Server
  deploy/crds/kieapp.crd.yaml
  deploy/ui/form.json
  pkg/apis/app/v2/kieapp_types.go
  pkg/apis/app/v2/zz_generated.deepcopy.go
  pkg/controller/kieapp/constants/constants.go
  pkg/controller/kieapp/defaults/defaults.go
  pkg/controller/kieapp/defaults/defaults_test.go
  pkg/controller/kieapp/test/crd_validation_test.go
Labels: approved, lgtm, ok-to-test, release-7.9.1

#542 Remove default resource limits from template except for trial envs
  config/7.9.1/common.yaml
  config/7.9.1/envs/rhdm-trial.yaml
  config/7.9.1/envs/rhpam-trial.yaml
Labels: approved, lgtm, release-7.9.1

#543 [RHPAM-3296] console ownerRef fix for ocp 4.6.1+
  pkg/controller/kieapp/deploy_ui.go
Labels: approved, bug, lgtm, release-7.9.0

#541 [RHPAM-3296] console ownerRef fix for ocp 4.6.1+
  pkg/controller/kieapp/deploy_ui.go
Labels: approved, bug, lgtm, release-7.9.1

#544 generate csv for 7.9.0 bug fix
  deploy/olm-catalog/dev/7.9.0-2/manifests/businessautomation-operator.7.9.0-2.clusterserviceversion.yaml
  deploy/olm-catalog/dev/7.9.0-2/manifests/kieapp.crd.yaml
  deploy/olm-catalog/dev/7.9.0-2/metadata/annotations.yaml
  deploy/olm-catalog/prod/7.9.0-2/manifests/businessautomation-operator.7.9.0-2.clusterserviceversion.yaml
  deploy/olm-catalog/prod/7.9.0-2/manifests/kieapp.crd.yaml
  deploy/olm-catalog/prod/7.9.0-2/metadata/annotations.yaml
  hack/go-build-bundle.sh
  hack/go-build.sh
  hack/go-csv.sh
  tools/csv-gen/csv-gen.go
Labels: approved, lgtm, release-7.9.0

#546 Revert GcMaxMetaspaceSize CRD to accept the int
  deploy/crds/kieapp.crd.yaml
  deploy/ui/form.json
  pkg/apis/app/v2/kieapp_types.go
  pkg/apis/app/v2/zz_generated.deepcopy.go
  pkg/controller/kieapp/defaults/defaults.go
  pkg/controller/kieapp/defaults/defaults_test.go
  pkg/controller/kieapp/test/crd_validation_test.go
Labels: approved, lgtm, release-7.9.1

#545 [RHDM-1499] - Missing Kie Server BuildConfig env configuration in Ope…
  deploy/ui/form.json
Labels: approved, lgtm, release-7.9.1

#548 UI reconcile improvements
  pkg/controller/kieapp/deploy_ui.go
  pkg/controller/kieapp/kieapp_controller.go
  pkg/controller/kieapp/watch.go
Labels: approved, lgtm, release-7.9.1

#552 move master to version 7.10.0
  config/7.10.0/common.yaml
  config/7.10.0/dbs/mysql.yaml
  config/7.10.0/dbs/pim/external.yaml
  config/7.10.0/dbs/pim/mysql.yaml
  config/7.10.0/dbs/pim/postgresql.yaml
  config/7.10.0/dbs/postgresql.yaml
  config/7.10.0/dbs/servers/external.yaml
  config/7.10.0/dbs/servers/h2.yaml
  config/7.10.0/dbs/servers/mysql.yaml
  config/7.10.0/dbs/servers/postgresql.yaml
  config/7.10.0/envs/rhdm-authoring-ha.yaml
  config/7.10.0/envs/rhdm-authoring.yaml
  config/7.10.0/envs/rhdm-production-immutable.yaml
  config/7.10.0/envs/rhdm-trial.yaml
  config/7.10.0/envs/rhpam-authoring-ha.yaml
  config/7.10.0/envs/rhpam-authoring.yaml
  config/7.10.0/envs/rhpam-production-immutable.yaml
  config/7.10.0/envs/rhpam-production.yaml
  config/7.10.0/envs/rhpam-trial.yaml
  config/7.10.0/jms/activemq-jms-config.yaml
  config/7.10.0/pim/process-migration-trial.yaml
  config/7.10.0/pim/process-migration.yaml
  deploy/crs/v2/snippets/prior_version.yaml
  deploy/olm-catalog/dev/7.10.0/manifests/businessautomation-operator.7.10.0.clusterserviceversion.yaml
  deploy/olm-catalog/dev/7.10.0/manifests/kieapp.crd.yaml
  deploy/olm-catalog/dev/7.10.0/metadata/annotations.yaml
  deploy/olm-catalog/prod/7.10.0/manifests/businessautomation-operator.7.10.0.clusterserviceversion.yaml
  deploy/olm-catalog/prod/7.10.0/manifests/kieapp.crd.yaml
  deploy/olm-catalog/prod/7.10.0/metadata/annotations.yaml
  deploy/operator.yaml
  hack/go-csv.sh
  pkg/controller/kieapp/constants/constants.go
Labels: approved, lgtm, release-7.10.0

#553 remove 7.8.1 configs
  config/7.8.1/common.yaml
  config/7.8.1/dbs/mysql.yaml
  config/7.8.1/dbs/pim/external.yaml
  config/7.8.1/dbs/pim/mysql.yaml
  config/7.8.1/dbs/pim/postgresql.yaml
  config/7.8.1/dbs/postgresql.yaml
  config/7.8.1/dbs/servers/external.yaml
  config/7.8.1/dbs/servers/h2.yaml
  config/7.8.1/dbs/servers/mysql.yaml
  config/7.8.1/dbs/servers/postgresql.yaml
  config/7.8.1/envs/rhdm-authoring-ha.yaml
  config/7.8.1/envs/rhdm-authoring.yaml
  config/7.8.1/envs/rhdm-production-immutable.yaml
  config/7.8.1/envs/rhdm-trial.yaml
  config/7.8.1/envs/rhpam-authoring-ha.yaml
  config/7.8.1/envs/rhpam-authoring.yaml
  config/7.8.1/envs/rhpam-production-immutable.yaml
  config/7.8.1/envs/rhpam-production.yaml
  config/7.8.1/envs/rhpam-trial.yaml
  config/7.8.1/jms/activemq-jms-config.yaml
  config/7.8.1/pim/process-migration-trial.yaml
  config/7.8.1/pim/process-migration.yaml
Labels: approved, release-7.10.0

#523 [RHPAM-3297] Update metering labels
  pkg/controller/kieapp/constants/constants.go
  pkg/controller/kieapp/defaults/defaults.go
  pkg/controller/kieapp/defaults/defaults_test.go
Labels: approved, lgtm, release-7.10.0

#554 [KIECLOUD-438] - DeploymentConfig probes for BusinessCentral too shor…
  config/7.10.0/common.yaml
  config/7.9.1/common.yaml
Labels: approved, lgtm, release-7.10.0

#557 [KIECLOUD-438] - DeploymentConfig probes for BusinessCentral too shor…
  config/7.9.1/common.yaml
Labels: approved, lgtm, release-7.9.1

#555 [KIECLOUD-463] fix metrics list & watch errors
  cmd/manager/main.go
  deploy/olm-catalog/dev/7.9.1/manifests/businessautomation-operator.7.9.1.clusterserviceversion.yaml
  deploy/olm-catalog/prod/7.9.1/manifests/businessautomation-operator.7.9.1.clusterserviceversion.yaml
  deploy/role.yaml
  pkg/components/components.go
Labels: approved, lgtm, release-7.9.1

#556 [KIECLOUD-463] cherry-pick to master
  cmd/manager/main.go
  deploy/olm-catalog/dev/7.10.0/manifests/businessautomation-operator.7.10.0.clusterserviceversion.yaml
  deploy/olm-catalog/dev/7.9.1/manifests/businessautomation-operator.7.9.1.clusterserviceversion.yaml
  deploy/olm-catalog/prod/7.10.0/manifests/businessautomation-operator.7.10.0.clusterserviceversion.yaml
  deploy/olm-catalog/prod/7.9.1/manifests/businessautomation-operator.7.9.1.clusterserviceversion.yaml
  deploy/role.yaml
  pkg/components/components.go
Labels: approved, lgtm, release-7.10.0

#559 [RHPAM-3056] Business Central remains "Container Creating" if missing known_hosts file in the githooks configuration
  deploy/crds/kieapp.crd.yaml
  deploy/ui/form.json
  pkg/apis/app/v2/kieapp_types.go
Labels: approved, lgtm, release-7.10.0
