Repository kiegroup/kie-cloud-operator, pull requests merged in 2021-12, with the labels that each got.

#699 [RHPAM-3541] - Rectified different default request values in Template and Operator
  pkg/controller/kieapp/constants/constants.go
  pkg/controller/kieapp/defaults/defaults_test.go
Labels: approved, lgtm, release-7.12.1

#712 [CVE-2021-43527] - update bundle version due cve respin
  deploy/olm-catalog/dev/7.11.1-3/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/dev/7.11.1-3/manifests/kieapp.crd.yaml
  deploy/olm-catalog/dev/7.11.1-3/metadata/annotations.yaml
  deploy/olm-catalog/prod/7.11.1-3/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/prod/7.11.1-3/manifests/kieapp.crd.yaml
  deploy/olm-catalog/prod/7.11.1-3/metadata/annotations.yaml
  deploy/olm-catalog/test/7.11.1-3/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/test/7.11.1-3/manifests/kieapp.crd.yaml
  deploy/olm-catalog/test/7.11.1-3/metadata/annotations.yaml
  version/version.go
Labels: approved, lgtm, release-7.11.1

#708 [RHPAM-4064] BC HA does not start because of outdated configuration
  config/7.12.0/envs/rhdm-authoring-ha.yaml
  config/7.12.0/envs/rhpam-authoring-ha.yaml
  deploy/crds/kieapp.crd.yaml
  deploy/olm-catalog/dev/7.12.0-1/manifests/kieapp.crd.yaml
  deploy/olm-catalog/prod/7.12.0-1/manifests/kieapp.crd.yaml
  deploy/olm-catalog/test/7.12.0-1/manifests/kieapp.crd.yaml
  deploy/ui/form.json
  pkg/apis/app/v2/kieapp_types.go
  pkg/apis/app/v2/zz_generated.deepcopy.go
  pkg/controller/kieapp/constants/constants.go
  pkg/controller/kieapp/defaults/defaults.go
  pkg/controller/kieapp/defaults/defaults_test.go
Labels: approved, lgtm, release-7.12.0

#714 [RHPAM-4064] BC HA does not start because of outdated configuration
  deploy/crds/kieapp.crd.yaml
  deploy/olm-catalog/dev/7.12.0-1/manifests/kieapp.crd.yaml
  deploy/olm-catalog/dev/7.12.1-1/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/dev/7.12.1-1/manifests/kieapp.crd.yaml
  deploy/olm-catalog/prod/7.12.0-1/manifests/kieapp.crd.yaml
  deploy/olm-catalog/prod/7.12.1-1/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/prod/7.12.1-1/manifests/kieapp.crd.yaml
  deploy/olm-catalog/test/7.12.0-1/manifests/kieapp.crd.yaml
  deploy/olm-catalog/test/7.12.1-1/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/test/7.12.1-1/manifests/kieapp.crd.yaml
  deploy/ui/form.json
  pkg/apis/app/v2/kieapp_types.go
  pkg/apis/app/v2/zz_generated.deepcopy.go
  pkg/controller/kieapp/constants/constants.go
  pkg/controller/kieapp/defaults/defaults.go
  pkg/controller/kieapp/defaults/defaults_test.go
  rhpam-config/7.12.0/envs/rhdm-authoring-ha.yaml
  rhpam-config/7.12.0/envs/rhpam-authoring-ha.yaml
  rhpam-config/7.12.1/envs/rhdm-authoring-ha.yaml
  rhpam-config/7.12.1/envs/rhpam-authoring-ha.yaml
Labels: approved, release-7.12.1

#716 [KIECLOUD-613] [ELYTRON] - replaceRoles not fully removed from operat…
  deploy/ui/form.json
Labels: approved, release-7.12.0, needs-cherry-pick :cherries:

#717 [KIECLOUD-613] [ELYTRON] - replaceRoles not fully removed from operat…
  deploy/ui/form.json
Labels: approved, release-7.12.1
