Repository kiegroup/kie-cloud-operator, pull requests merged in 2021-01, with the labels that each got.

#575 [KIECLOUD-482] switch to build version for csv release
  README.md
  deploy/olm-catalog/dev/7.9.1-1/manifests/businessautomation-operator.7.9.1-1.clusterserviceversion.yaml
  deploy/olm-catalog/dev/7.9.1-1/manifests/kieapp.crd.yaml
  deploy/olm-catalog/dev/7.9.1-1/metadata/annotations.yaml
  deploy/olm-catalog/prod/7.9.1-1/manifests/businessautomation-operator.7.9.1-1.clusterserviceversion.yaml
  deploy/olm-catalog/prod/7.9.1-1/manifests/kieapp.crd.yaml
  deploy/olm-catalog/prod/7.9.1-1/metadata/annotations.yaml
  getversion.go
  go.sum
  hack/go-build-bundle.sh
  hack/go-csv.sh
  pkg/controller/kieapp/deploy_ui_test.go
  tools/csv-gen/csv-gen.go
  version/version.go
Labels: approved, lgtm, release-7.9.1

#576 [KIECLOUD-482] switch to build version for csv release
  README.md
  deploy/olm-catalog/dev/7.10.0-1/manifests/businessautomation-operator.7.10.0-1.clusterserviceversion.yaml
  deploy/olm-catalog/dev/7.10.0-1/manifests/kieapp.crd.yaml
  deploy/olm-catalog/dev/7.10.0-1/metadata/annotations.yaml
  deploy/olm-catalog/dev/7.9.1-1/manifests/businessautomation-operator.7.9.1-1.clusterserviceversion.yaml
  deploy/olm-catalog/dev/7.9.1-1/manifests/kieapp.crd.yaml
  deploy/olm-catalog/dev/7.9.1-1/metadata/annotations.yaml
  deploy/olm-catalog/prod/7.10.0-1/manifests/businessautomation-operator.7.10.0-1.clusterserviceversion.yaml
  deploy/olm-catalog/prod/7.10.0-1/manifests/kieapp.crd.yaml
  deploy/olm-catalog/prod/7.10.0-1/metadata/annotations.yaml
  deploy/olm-catalog/prod/7.9.1-1/manifests/businessautomation-operator.7.9.1-1.clusterserviceversion.yaml
  deploy/olm-catalog/prod/7.9.1-1/manifests/kieapp.crd.yaml
  deploy/olm-catalog/prod/7.9.1-1/metadata/annotations.yaml
  deploy/olm-catalog/test/7.10.0-1/manifests/businessautomation-operator.7.10.0-1.clusterserviceversion.yaml
  deploy/olm-catalog/test/7.10.0-1/manifests/kieapp.crd.yaml
  deploy/olm-catalog/test/7.10.0-1/metadata/annotations.yaml
  getversion.go
  go.sum
  hack/go-build-bundle.sh
  hack/go-csv.sh
  pkg/controller/kieapp/deploy_ui_test.go
  tools/csv-gen/csv-gen.go
  version/version.go
Labels: approved, lgtm, release-7.10.0

#572 [RHPAM-3320] - Business Central PV size is not configurable in Operator
  config/7.10.0/common.yaml
  config/7.10.0/envs/rhdm-authoring-ha.yaml
  config/7.10.0/envs/rhdm-authoring.yaml
  config/7.10.0/envs/rhpam-authoring-ha.yaml
  config/7.10.0/envs/rhpam-authoring.yaml
  deploy/crds/kieapp.crd.yaml
  deploy/olm-catalog/dev/7.10.0-1/manifests/businessautomation-operator.7.10.0-1.clusterserviceversion.yaml
  deploy/olm-catalog/prod/7.10.0-1/manifests/businessautomation-operator.7.10.0-1.clusterserviceversion.yaml
  deploy/olm-catalog/test/7.10.0-1/manifests/businessautomation-operator.7.10.0-1.clusterserviceversion.yaml
  deploy/ui/form.json
  pkg/apis/app/v2/kieapp_types.go
  pkg/controller/kieapp/constants/constants.go
  pkg/controller/kieapp/defaults/defaults.go
  pkg/controller/kieapp/defaults/defaults_test.go
Labels: approved, lgtm, release-7.10.0

#569 [RHPAM-3248] - Provision Dashbuilder image with operator
  config/7.10.0/common.yaml
  config/7.10.0/dashbuilder/rhpam-standalone-dashbuilder.yaml
  config/7.10.0/envs/rhpam-standalone-dashbuilder.yaml
  deploy/crds/kieapp.crd.yaml
  deploy/crs/v2/kieapp_rhpam_standalone_dashbuilder.yaml
  deploy/olm-catalog/dev/7.10.0-1/manifests/businessautomation-operator.7.10.0-1.clusterserviceversion.yaml
  deploy/olm-catalog/prod/7.10.0-1/manifests/businessautomation-operator.7.10.0-1.clusterserviceversion.yaml
  deploy/olm-catalog/test/7.10.0-1/manifests/businessautomation-operator.7.10.0-1.clusterserviceversion.yaml
  deploy/operator.yaml
  deploy/ui/form.json
  pkg/apis/app/v2/kieapp_types.go
  pkg/apis/app/v2/zz_generated.deepcopy.go
  pkg/components/components.go
  pkg/controller/kieapp/constants/constants.go
  pkg/controller/kieapp/defaults/defaults.go
  pkg/controller/kieapp/defaults/defaults_test.go
  pkg/controller/kieapp/defaults/merge.go
  pkg/controller/kieapp/kieapp_controller.go
Labels: approved, lgtm, release-7.10.0

#574 [KIECLOUD-480] - Execute and Fix Unit Tests
  pkg/controller/kieapp/defaults/auth_test.go
Labels: approved, lgtm, release-7.10.0

#577 generate 7.9.1-1 csvs w/ digest
  deploy/olm-catalog/dev/7.9.1-1/manifests/businessautomation-operator.7.9.1-1.clusterserviceversion.yaml
  deploy/olm-catalog/prod/7.9.1-1/manifests/businessautomation-operator.7.9.1-1.clusterserviceversion.yaml
Labels: approved, lgtm, release-7.9.1

#579 fix image version for OSBS
  hack/go-build-bundle.sh
Labels: approved, lgtm, release-7.9.1

#578 cherry-pick: generate 7.9.1-1 csvs w/ digest
  deploy/olm-catalog/dev/7.9.1-1/manifests/businessautomation-operator.7.9.1-1.clusterserviceversion.yaml
  deploy/olm-catalog/prod/7.9.1-1/manifests/businessautomation-operator.7.9.1-1.clusterserviceversion.yaml
  hack/go-build-bundle.sh
Labels: approved, lgtm, release-7.10.0

#583 fix bundle build script
  hack/go-build-bundle.sh
Labels: approved, lgtm, release-7.10.0

#584 Merge branch 'master' into release-v7.10.x
  hack/go-build-bundle.sh
Labels: approved, lgtm, release-7.10.0

#582 7.10.1 version
  config/7.10.1/common.yaml
  config/7.10.1/dashbuilder/rhpam-standalone-dashbuilder.yaml
  config/7.10.1/dbs/mysql.yaml
  config/7.10.1/dbs/pim/external.yaml
  config/7.10.1/dbs/pim/mysql.yaml
  config/7.10.1/dbs/pim/postgresql.yaml
  config/7.10.1/dbs/postgresql.yaml
  config/7.10.1/dbs/servers/external.yaml
  config/7.10.1/dbs/servers/h2.yaml
  config/7.10.1/dbs/servers/mysql.yaml
  config/7.10.1/dbs/servers/postgresql.yaml
  config/7.10.1/envs/rhdm-authoring-ha.yaml
  config/7.10.1/envs/rhdm-authoring.yaml
  config/7.10.1/envs/rhdm-production-immutable.yaml
  config/7.10.1/envs/rhdm-trial.yaml
  config/7.10.1/envs/rhpam-authoring-ha.yaml
  config/7.10.1/envs/rhpam-authoring.yaml
  config/7.10.1/envs/rhpam-production-immutable.yaml
  config/7.10.1/envs/rhpam-production.yaml
  config/7.10.1/envs/rhpam-standalone-dashbuilder.yaml
  config/7.10.1/envs/rhpam-trial.yaml
  config/7.10.1/jms/activemq-jms-config.yaml
  config/7.10.1/pim/process-migration-trial.yaml
  config/7.10.1/pim/process-migration.yaml
  deploy/crs/v2/snippets/prior_version.yaml
  deploy/olm-catalog/dev/7.10.1-1/manifests/businessautomation-operator.7.10.1-1.clusterserviceversion.yaml
  deploy/olm-catalog/dev/7.10.1-1/manifests/kieapp.crd.yaml
  deploy/olm-catalog/dev/7.10.1-1/metadata/annotations.yaml
  deploy/olm-catalog/prod/7.10.1-1/manifests/businessautomation-operator.7.10.1-1.clusterserviceversion.yaml
  deploy/olm-catalog/prod/7.10.1-1/manifests/kieapp.crd.yaml
  deploy/olm-catalog/prod/7.10.1-1/metadata/annotations.yaml
  deploy/olm-catalog/test/7.10.1-1/manifests/businessautomation-operator.7.10.1-1.clusterserviceversion.yaml
  deploy/olm-catalog/test/7.10.1-1/manifests/kieapp.crd.yaml
  deploy/olm-catalog/test/7.10.1-1/metadata/annotations.yaml
  deploy/operator.yaml
  pkg/controller/kieapp/constants/constants.go
Labels: approved, lgtm, release-7.10.1

#585 remove 7.9.0 configs
  config/7.9.0/common.yaml
  config/7.9.0/dbs/mysql.yaml
  config/7.9.0/dbs/pim/external.yaml
  config/7.9.0/dbs/pim/mysql.yaml
  config/7.9.0/dbs/pim/postgresql.yaml
  config/7.9.0/dbs/postgresql.yaml
  config/7.9.0/dbs/servers/external.yaml
  config/7.9.0/dbs/servers/h2.yaml
  config/7.9.0/dbs/servers/mysql.yaml
  config/7.9.0/dbs/servers/postgresql.yaml
  config/7.9.0/envs/rhdm-authoring-ha.yaml
  config/7.9.0/envs/rhdm-authoring.yaml
  config/7.9.0/envs/rhdm-production-immutable.yaml
  config/7.9.0/envs/rhdm-trial.yaml
  config/7.9.0/envs/rhpam-authoring-ha.yaml
  config/7.9.0/envs/rhpam-authoring.yaml
  config/7.9.0/envs/rhpam-production-immutable.yaml
  config/7.9.0/envs/rhpam-production.yaml
  config/7.9.0/envs/rhpam-trial.yaml
  config/7.9.0/jms/activemq-jms-config.yaml
  config/7.9.0/pim/process-migration-trial.yaml
  config/7.9.0/pim/process-migration.yaml
Labels: approved, release-7.10.1

#573 [RHPAM-3319] - hard to deploy immutable kie-server with pre-built kja…
  config/7.10.1/envs/rhdm-production-immutable.yaml
  config/7.10.1/envs/rhpam-production-immutable.yaml
  pkg/controller/kieapp/defaults/defaults_test.go
  pkg/controller/kieapp/defaults/merge_test.go
Labels: approved, lgtm, release-7.10.1

#587 [RHPAM-3403] - Wrong default type of Console CPU request in Operator
  pkg/controller/kieapp/constants/constants.go
Labels: approved, lgtm, release-7.10.0

#586 [RHPAM-3403] - Wrong default type of Console CPU request in Operator
  pkg/controller/kieapp/constants/constants.go
Labels: approved, lgtm, release-7.10.1
