Repository kiegroup/kie-cloud-operator, pull requests merged in 2021-11, with the labels that each got.

#695 [KIECLOUD-593] Update BA Operator Docs about OLM
  README.md
  hack/go-build-bundle.sh
Labels: approved, lgtm, release-7.12.1

#697 [RHPAM-4019] - BC HA not started in OpenShift because of datagrid rea…
  config/7.12.0/envs/rhdm-authoring-ha.yaml
  config/7.12.0/envs/rhpam-authoring-ha.yaml
  deploy/olm-catalog/dev/7.12.0-1/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/prod/7.12.0-1/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/test/7.12.0-1/manifests/businessautomation-operator.clusterserviceversion.yaml
Labels: approved, lgtm, release-7.12.0

#698 [RHPAM-4019] - BC HA not started in OpenShift because of datagrid rea…
  deploy/crds/kieapp.crd.yaml
  deploy/olm-catalog/dev/7.12.1-1/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/dev/7.12.1-1/manifests/kieapp.crd.yaml
  deploy/olm-catalog/prod/7.12.1-1/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/prod/7.12.1-1/manifests/kieapp.crd.yaml
  deploy/olm-catalog/test/7.12.1-1/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/test/7.12.1-1/manifests/kieapp.crd.yaml
  rhpam-config/7.12.0/envs/rhdm-authoring-ha.yaml
  rhpam-config/7.12.0/envs/rhpam-authoring-ha.yaml
  rhpam-config/7.12.1/envs/rhdm-authoring-ha.yaml
  rhpam-config/7.12.1/envs/rhpam-authoring-ha.yaml
Labels: approved, lgtm, release-7.12.1

#701 [rhpam-3279] 7.12.x Configure CORS automatically through a flag or environment variable
  deploy/ui/form.json
Labels: approved, lgtm

#703 [RHPAM-4044] BA Operator UI generate startup strategy in wrong place
  deploy/ui/form.json
Labels: approved, lgtm

#700 [RHPAM-4044] BA Operator UI generate startup strategy in wrong place
  deploy/ui/form.json
Labels: approved, lgtm, release-7.12.0

#704 [RHPAM-3279] Configure CORS automatically through a flag or environment variable
  deploy/ui/form.json
Labels: approved, lgtm

#702 [RHPAM-4045] - Missing description in KieApp for Kie Server persistRe…
  deploy/crds/kieapp.crd.yaml
  deploy/olm-catalog/dev/7.12.0-1/manifests/kieapp.crd.yaml
  deploy/olm-catalog/prod/7.12.0-1/manifests/kieapp.crd.yaml
  deploy/olm-catalog/test/7.12.0-1/manifests/kieapp.crd.yaml
  pkg/apis/app/v2/kieapp_types.go
Labels: approved, lgtm, release-7.12.0

#705 [RHPAM-4045] - Missing description in KieApp for Kie Server persistRe…
  deploy/crds/kieapp.crd.yaml
  deploy/olm-catalog/dev/7.12.0-1/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/dev/7.12.0-1/manifests/kieapp.crd.yaml
  deploy/olm-catalog/dev/7.12.1-1/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/dev/7.12.1-1/manifests/kieapp.crd.yaml
  deploy/olm-catalog/prod/7.12.0-1/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/prod/7.12.0-1/manifests/kieapp.crd.yaml
  deploy/olm-catalog/prod/7.12.1-1/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/prod/7.12.1-1/manifests/kieapp.crd.yaml
  deploy/olm-catalog/test/7.12.0-1/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/test/7.12.0-1/manifests/kieapp.crd.yaml
  deploy/olm-catalog/test/7.12.1-1/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/test/7.12.1-1/manifests/kieapp.crd.yaml
  pkg/apis/app/v2/kieapp_types.go
Labels: approved, lgtm, release-7.12.1

#706 7.11.1-2 respin
  deploy/olm-catalog/dev/7.11.1-2/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/dev/7.11.1-2/manifests/kieapp.crd.yaml
  deploy/olm-catalog/dev/7.11.1-2/metadata/annotations.yaml
  deploy/olm-catalog/prod/7.11.1-2/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/prod/7.11.1-2/manifests/kieapp.crd.yaml
  deploy/olm-catalog/prod/7.11.1-2/metadata/annotations.yaml
  deploy/olm-catalog/test/7.11.1-2/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/test/7.11.1-2/manifests/kieapp.crd.yaml
  deploy/olm-catalog/test/7.11.1-2/metadata/annotations.yaml
  version/version.go
Labels: approved, lgtm, release-7.11.1
