Repository kiegroup/kie-cloud-operator, pull requests merged in 2021-04, with the labels that each got.

#624 [RHPAM-3331] Operator for AMQ Streams (Kafka) integration
  config/7.11.0/common.yaml
  pkg/controller/kieapp/defaults/defaults_test.go
Labels: approved, lgtm, release-7.11.0

#623 cekit 3.11 bundle build improvements
  README.md
  hack/go-build-bundle.sh
Labels: approved, lgtm, release-7.11.0

#626 Merge branch 'main' into release-v7.11.x
  README.md
  hack/go-build-bundle.sh
Labels: lgtm, release-7.11.0

#627 increment version to 7.11.1
  config/7.11.1/common.yaml
  config/7.11.1/dashbuilder/rhpam-standalone-dashbuilder.yaml
  config/7.11.1/dbs/mysql.yaml
  config/7.11.1/dbs/pim/external.yaml
  config/7.11.1/dbs/pim/mysql.yaml
  config/7.11.1/dbs/pim/postgresql.yaml
  config/7.11.1/dbs/postgresql.yaml
  config/7.11.1/dbs/servers/external.yaml
  config/7.11.1/dbs/servers/h2.yaml
  config/7.11.1/dbs/servers/mysql.yaml
  config/7.11.1/dbs/servers/postgresql.yaml
  config/7.11.1/envs/rhdm-authoring-ha.yaml
  config/7.11.1/envs/rhdm-authoring.yaml
  config/7.11.1/envs/rhdm-production-immutable.yaml
  config/7.11.1/envs/rhdm-trial.yaml
  config/7.11.1/envs/rhpam-authoring-ha.yaml
  config/7.11.1/envs/rhpam-authoring.yaml
  config/7.11.1/envs/rhpam-production-immutable.yaml
  config/7.11.1/envs/rhpam-production.yaml
  config/7.11.1/envs/rhpam-standalone-dashbuilder.yaml
  config/7.11.1/envs/rhpam-trial.yaml
  config/7.11.1/jms/activemq-jms-config.yaml
  config/7.11.1/pim/process-migration-trial.yaml
  config/7.11.1/pim/process-migration.yaml
  deploy/crs/v2/snippets/prior_version.yaml
  deploy/olm-catalog/dev/7.11.1-1/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/dev/7.11.1-1/manifests/kieapp.crd.yaml
  deploy/olm-catalog/dev/7.11.1-1/metadata/annotations.yaml
  deploy/olm-catalog/prod/7.11.1-1/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/prod/7.11.1-1/manifests/kieapp.crd.yaml
  deploy/olm-catalog/prod/7.11.1-1/metadata/annotations.yaml
  deploy/olm-catalog/test/7.11.1-1/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/test/7.11.1-1/manifests/kieapp.crd.yaml
  deploy/olm-catalog/test/7.11.1-1/metadata/annotations.yaml
  deploy/operator.yaml
  hack/go-sdk-gen.sh
  pkg/controller/kieapp/constants/constants.go
  pkg/controller/kieapp/defaults/defaults_test.go
  pkg/controller/kieapp/defaults/upgrade_test.go
Labels: approved, lgtm, release-7.11.1

#628 remove old 7.10.x configs
  config/7.10.0/common.yaml
  config/7.10.0/dashbuilder/rhpam-standalone-dashbuilder.yaml
  config/7.10.0/dbs/mysql.yaml
  config/7.10.0/dbs/pim/external.yaml
  config/7.10.0/dbs/pim/mysql.yaml
  config/7.10.0/dbs/pim/postgresql.yaml
  config/7.10.0/dbs/postgresql.yaml
  config/7.10.0/dbs/servers/external.yaml
  config/7.10.0/dbs/servers/h2.yaml
  config/7.10.0/dbs/servers/mysql.yaml
  config/7.10.0/dbs/servers/postgresql.yaml
  config/7.10.0/envs/rhdm-authoring-ha.yaml
  config/7.10.0/envs/rhdm-authoring.yaml
  config/7.10.0/envs/rhdm-production-immutable.yaml
  config/7.10.0/envs/rhdm-trial.yaml
  config/7.10.0/envs/rhpam-authoring-ha.yaml
  config/7.10.0/envs/rhpam-authoring.yaml
  config/7.10.0/envs/rhpam-production-immutable.yaml
  config/7.10.0/envs/rhpam-production.yaml
  config/7.10.0/envs/rhpam-standalone-dashbuilder.yaml
  config/7.10.0/envs/rhpam-trial.yaml
  config/7.10.0/jms/activemq-jms-config.yaml
  config/7.10.0/pim/process-migration-trial.yaml
  config/7.10.0/pim/process-migration.yaml
  config/7.10.1/common.yaml
  config/7.10.1/dashbuilder/rhpam-standalone-dashbuilder.yaml
  config/7.10.1/dbs/mysql.yaml
  config/7.10.1/dbs/pim/external.yaml
  config/7.10.1/dbs/pim/mysql.yaml
  config/7.10.1/dbs/pim/postgresql.yaml
  config/7.10.1/dbs/postgresql.yaml
  config/7.10.1/dbs/servers/external.yaml
  config/7.10.1/dbs/servers/h2.yaml
  config/7.10.1/dbs/servers/mysql.yaml
  config/7.10.1/dbs/servers/postgresql.yaml
  config/7.10.1/envs/rhdm-authoring-ha.yaml
  config/7.10.1/envs/rhdm-authoring.yaml
  config/7.10.1/envs/rhdm-production-immutable.yaml
  config/7.10.1/envs/rhdm-trial.yaml
  config/7.10.1/envs/rhpam-authoring-ha.yaml
  config/7.10.1/envs/rhpam-authoring.yaml
  config/7.10.1/envs/rhpam-production-immutable.yaml
  config/7.10.1/envs/rhpam-production.yaml
  config/7.10.1/envs/rhpam-standalone-dashbuilder.yaml
  config/7.10.1/envs/rhpam-trial.yaml
  config/7.10.1/jms/activemq-jms-config.yaml
  config/7.10.1/pim/process-migration-trial.yaml
  config/7.10.1/pim/process-migration.yaml
Labels: approved, release-7.11.1

#630 7.10.1-2 bundle
  deploy/olm-catalog/dev/7.10.1-2/manifests/businessautomation-operator.7.10.1-2.clusterserviceversion.yaml
  deploy/olm-catalog/dev/7.10.1-2/manifests/kieapp.crd.yaml
  deploy/olm-catalog/dev/7.10.1-2/metadata/annotations.yaml
  deploy/olm-catalog/prod/7.10.1-2/manifests/businessautomation-operator.7.10.1-2.clusterserviceversion.yaml
  deploy/olm-catalog/prod/7.10.1-2/manifests/kieapp.crd.yaml
  deploy/olm-catalog/prod/7.10.1-2/metadata/annotations.yaml
  deploy/olm-catalog/test/7.10.1-2/manifests/businessautomation-operator.7.10.1-2.clusterserviceversion.yaml
  deploy/olm-catalog/test/7.10.1-2/manifests/kieapp.crd.yaml
  deploy/olm-catalog/test/7.10.1-2/metadata/annotations.yaml
  version/version.go
Labels: approved, lgtm, release-7.10.1

#632 [RHPAM-3319] - hard to deploy immutable kie-server with pre-built kja…
  pkg/controller/kieapp/defaults/defaults.go
  pkg/controller/kieapp/defaults/defaults_test.go
Labels: approved, lgtm, release-7.11.0

#633 [RHPAM-3319] - hard to deploy immutable kie-server with pre-built kja…
  pkg/controller/kieapp/defaults/defaults.go
  pkg/controller/kieapp/defaults/defaults_test.go
Labels: approved, lgtm, release-7.11.1

#635 update OWNERS file
  OWNERS
Labels: approved, lgtm

#636 update OWNERS file
  OWNERS
Labels: approved, lgtm

#638 changes to account for 7.10.1-3 bundle
  deploy/olm-catalog/dev/7.10.1-3/manifests/businessautomation-operator.7.10.1-3.clusterserviceversion.yaml
  deploy/olm-catalog/dev/7.10.1-3/manifests/kieapp.crd.yaml
  deploy/olm-catalog/dev/7.10.1-3/metadata/annotations.yaml
  deploy/olm-catalog/prod/7.10.1-3/manifests/businessautomation-operator.7.10.1-3.clusterserviceversion.yaml
  deploy/olm-catalog/prod/7.10.1-3/manifests/kieapp.crd.yaml
  deploy/olm-catalog/prod/7.10.1-3/metadata/annotations.yaml
  deploy/olm-catalog/test/7.10.1-3/manifests/businessautomation-operator.7.10.1-3.clusterserviceversion.yaml
  deploy/olm-catalog/test/7.10.1-3/manifests/kieapp.crd.yaml
  deploy/olm-catalog/test/7.10.1-3/metadata/annotations.yaml
  version/version.go
Labels: approved, lgtm

#642 Revert "changes to account for 7.10.1-3 bundle"
  deploy/olm-catalog/dev/7.10.0-2/manifests/kieapp.crd.yaml
  deploy/olm-catalog/dev/7.10.1-3/manifests/businessautomation-operator.7.10.1-3.clusterserviceversion.yaml
  deploy/olm-catalog/dev/7.10.1-3/manifests/kieapp.crd.yaml
  deploy/olm-catalog/dev/7.10.1-3/metadata/annotations.yaml
  deploy/olm-catalog/dev/7.11.0-1/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/prod/7.10.0-2/manifests/kieapp.crd.yaml
  deploy/olm-catalog/prod/7.10.1-3/manifests/businessautomation-operator.7.10.1-3.clusterserviceversion.yaml
  deploy/olm-catalog/prod/7.10.1-3/manifests/kieapp.crd.yaml
  deploy/olm-catalog/prod/7.10.1-3/metadata/annotations.yaml
  deploy/olm-catalog/prod/7.11.0-1/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/test/7.10.0-2/manifests/kieapp.crd.yaml
  deploy/olm-catalog/test/7.10.1-3/manifests/businessautomation-operator.7.10.1-3.clusterserviceversion.yaml
  deploy/olm-catalog/test/7.10.1-3/manifests/kieapp.crd.yaml
  deploy/olm-catalog/test/7.10.1-3/metadata/annotations.yaml
  deploy/olm-catalog/test/7.11.0-1/manifests/businessautomation-operator.clusterserviceversion.yaml
  version/version.go
Labels: approved, lgtm, release-7.11.0
