Repository kiegroup/kie-cloud-operator, pull requests merged in 2021-02, with the labels that each got.

#591 [RHPAM-3297] Update metering labels 7.10.x
  pkg/controller/kieapp/constants/constants.go
Labels: approved, lgtm, release-7.10.0

#593 [RHPAM-3297] Update metering labels - main
  pkg/controller/kieapp/constants/constants.go
Labels: approved, lgtm, release-7.10.1

#597 [RHPAM-3471] remove offending label & increment csv version
  deploy/olm-catalog/dev/7.10.0-2/manifests/businessautomation-operator.7.10.0-2.clusterserviceversion.yaml
  deploy/olm-catalog/dev/7.10.0-2/manifests/kieapp.crd.yaml
  deploy/olm-catalog/dev/7.10.0-2/metadata/annotations.yaml
  deploy/olm-catalog/prod/7.10.0-2/manifests/businessautomation-operator.7.10.0-2.clusterserviceversion.yaml
  deploy/olm-catalog/prod/7.10.0-2/manifests/kieapp.crd.yaml
  deploy/olm-catalog/prod/7.10.0-2/metadata/annotations.yaml
  deploy/olm-catalog/test/7.10.0-2/manifests/businessautomation-operator.7.10.0-2.clusterserviceversion.yaml
  deploy/olm-catalog/test/7.10.0-2/manifests/kieapp.crd.yaml
  deploy/olm-catalog/test/7.10.0-2/metadata/annotations.yaml
  pkg/controller/kieapp/defaults/defaults.go
  version/version.go
Labels: approved, lgtm, release-7.10.0

#595 [RHPAM-3460] - LDAP login module flag for Kie Server is not set in Op…
  config/7.10.1/common.yaml
  pkg/controller/kieapp/defaults/auth_test.go
Labels: approved, lgtm, ok-to-test, release-7.10.1

#599 improve operator patch build logic
  README.md
  hack/go-build.sh
Labels: approved, lgtm, release-7.10.0

#600 cherry-pick: improve operator patch build logic
  README.md
  hack/go-build.sh
Labels: approved, lgtm, release-7.10.1

#594 use lookaside cache with local builds only
  deploy/olm-catalog/dev/7.10.0-1/manifests/businessautomation-operator.7.10.0-1.clusterserviceversion.yaml
  deploy/olm-catalog/dev/7.10.0-2/manifests/businessautomation-operator.7.10.0-2.clusterserviceversion.yaml
  deploy/olm-catalog/dev/7.10.0-2/manifests/kieapp.crd.yaml
  deploy/olm-catalog/module.yaml
  deploy/olm-catalog/prod/7.10.0-1/manifests/businessautomation-operator.7.10.0-1.clusterserviceversion.yaml
  deploy/olm-catalog/prod/7.10.0-1/manifests/kieapp.crd.yaml
  deploy/olm-catalog/prod/7.10.0-2/manifests/businessautomation-operator.7.10.0-2.clusterserviceversion.yaml
  deploy/olm-catalog/prod/7.10.0-2/manifests/kieapp.crd.yaml
  deploy/olm-catalog/test/7.10.0-1/manifests/businessautomation-operator.7.10.0-1.clusterserviceversion.yaml
  deploy/olm-catalog/test/7.10.0-2/manifests/businessautomation-operator.7.10.0-2.clusterserviceversion.yaml
  deploy/olm-catalog/test/7.10.0-2/manifests/kieapp.crd.yaml
  hack/go-build-bundle.sh
  image-bundle.yaml
  tools/csv-gen/csv-gen.go
Labels: approved, lgtm, release-7.10.0

#601 cherry-pick: only use lookaside cache with local builds
  deploy/olm-catalog/dev/7.10.0-1/manifests/businessautomation-operator.7.10.0-1.clusterserviceversion.yaml
  deploy/olm-catalog/dev/7.10.1-1/manifests/kieapp.crd.yaml
  deploy/olm-catalog/module.yaml
  deploy/olm-catalog/prod/7.10.0-1/manifests/businessautomation-operator.7.10.0-1.clusterserviceversion.yaml
  deploy/olm-catalog/prod/7.10.0-1/manifests/kieapp.crd.yaml
  deploy/olm-catalog/prod/7.10.1-1/manifests/kieapp.crd.yaml
  deploy/olm-catalog/test/7.10.0-1/manifests/businessautomation-operator.7.10.0-1.clusterserviceversion.yaml
  deploy/olm-catalog/test/7.10.1-1/manifests/kieapp.crd.yaml
  hack/go-build-bundle.sh
  image-bundle.yaml
  tools/csv-gen/csv-gen.go
Labels: approved, lgtm, release-7.10.1

#602 ensure crd generates before csv
  Makefile
Labels: approved, lgtm, release-7.10.1

#588 [RHPAM-3420] - Wrong image pulled for rhdm-production-immutable envir…
  config/7.10.1/envs/rhdm-production-immutable.yaml
  config/7.10.1/envs/rhpam-production-immutable.yaml
  pkg/controller/kieapp/defaults/defaults_test.go
  pkg/controller/kieapp/defaults/merge_test.go
Labels: approved, lgtm, release-7.10.1

#607 increment product version to 7.11.0
  config/7.11.0/common.yaml
  config/7.11.0/dashbuilder/rhpam-standalone-dashbuilder.yaml
  config/7.11.0/dbs/mysql.yaml
  config/7.11.0/dbs/pim/external.yaml
  config/7.11.0/dbs/pim/mysql.yaml
  config/7.11.0/dbs/pim/postgresql.yaml
  config/7.11.0/dbs/postgresql.yaml
  config/7.11.0/dbs/servers/external.yaml
  config/7.11.0/dbs/servers/h2.yaml
  config/7.11.0/dbs/servers/mysql.yaml
  config/7.11.0/dbs/servers/postgresql.yaml
  config/7.11.0/envs/rhdm-authoring-ha.yaml
  config/7.11.0/envs/rhdm-authoring.yaml
  config/7.11.0/envs/rhdm-production-immutable.yaml
  config/7.11.0/envs/rhdm-trial.yaml
  config/7.11.0/envs/rhpam-authoring-ha.yaml
  config/7.11.0/envs/rhpam-authoring.yaml
  config/7.11.0/envs/rhpam-production-immutable.yaml
  config/7.11.0/envs/rhpam-production.yaml
  config/7.11.0/envs/rhpam-standalone-dashbuilder.yaml
  config/7.11.0/envs/rhpam-trial.yaml
  config/7.11.0/jms/activemq-jms-config.yaml
  config/7.11.0/pim/process-migration-trial.yaml
  config/7.11.0/pim/process-migration.yaml
  deploy/crs/v2/snippets/prior_version.yaml
  deploy/olm-catalog/dev/7.11.0-1/manifests/businessautomation-operator.7.11.0-1.clusterserviceversion.yaml
  deploy/olm-catalog/dev/7.11.0-1/manifests/kieapp.crd.yaml
  deploy/olm-catalog/dev/7.11.0-1/metadata/annotations.yaml
  deploy/olm-catalog/prod/7.11.0-1/manifests/businessautomation-operator.7.11.0-1.clusterserviceversion.yaml
  deploy/olm-catalog/prod/7.11.0-1/manifests/kieapp.crd.yaml
  deploy/olm-catalog/prod/7.11.0-1/metadata/annotations.yaml
  deploy/olm-catalog/test/7.11.0-1/manifests/businessautomation-operator.7.11.0-1.clusterserviceversion.yaml
  deploy/olm-catalog/test/7.11.0-1/manifests/kieapp.crd.yaml
  deploy/olm-catalog/test/7.11.0-1/metadata/annotations.yaml
  deploy/operator.yaml
  pkg/controller/kieapp/constants/constants.go
  version/version.go
Labels: approved, lgtm, release-7.11.0

#608 remove old 7.9.1 configs
  config/7.9.1/common.yaml
  config/7.9.1/dbs/mysql.yaml
  config/7.9.1/dbs/pim/external.yaml
  config/7.9.1/dbs/pim/mysql.yaml
  config/7.9.1/dbs/pim/postgresql.yaml
  config/7.9.1/dbs/postgresql.yaml
  config/7.9.1/dbs/servers/external.yaml
  config/7.9.1/dbs/servers/h2.yaml
  config/7.9.1/dbs/servers/mysql.yaml
  config/7.9.1/dbs/servers/postgresql.yaml
  config/7.9.1/envs/rhdm-authoring-ha.yaml
  config/7.9.1/envs/rhdm-authoring.yaml
  config/7.9.1/envs/rhdm-production-immutable.yaml
  config/7.9.1/envs/rhdm-trial.yaml
  config/7.9.1/envs/rhpam-authoring-ha.yaml
  config/7.9.1/envs/rhpam-authoring.yaml
  config/7.9.1/envs/rhpam-production-immutable.yaml
  config/7.9.1/envs/rhpam-production.yaml
  config/7.9.1/envs/rhpam-trial.yaml
  config/7.9.1/jms/activemq-jms-config.yaml
  config/7.9.1/pim/process-migration-trial.yaml
  config/7.9.1/pim/process-migration.yaml
Labels: approved, lgtm, release-7.11.0
