Repository kiegroup/kie-cloud-operator, pull requests merged in 2021-03, with the labels that each got.

#604 [RHPAM-3481] Label for subcomp is wrongly set in Operator for images with digest
  pkg/controller/kieapp/constants/constants.go
  pkg/controller/kieapp/defaults/defaults.go
  pkg/controller/kieapp/defaults/defaults_test.go
Labels: approved, lgtm, release-7.10.1

#609 [RHPAM-3481] Label for subcomp is wrongly set in Operator for images with digest
  pkg/controller/kieapp/constants/constants.go
  pkg/controller/kieapp/defaults/defaults.go
  pkg/controller/kieapp/defaults/defaults_test.go
Labels: approved, lgtm, release-7.11.0

#567 [RHPAM-3181] Update the openshift.PING to kubernetes.PING
  config/7.11.0/common.yaml
  config/7.11.0/dashbuilder/rhpam-standalone-dashbuilder.yaml
  pkg/controller/kieapp/constants/constants.go
  pkg/controller/kieapp/defaults/defaults_test.go
  pkg/controller/kieapp/defaults/merge_test.go
Labels: approved, lgtm, release-7.11.0

#611 [KIECLOUD-495] reduce product version support to 2 per operator release
  deploy/olm-catalog/dev/7.11.0-1/manifests/businessautomation-operator.7.11.0-1.clusterserviceversion.yaml
  deploy/olm-catalog/prod/7.11.0-1/manifests/businessautomation-operator.7.11.0-1.clusterserviceversion.yaml
  deploy/olm-catalog/test/7.11.0-1/manifests/businessautomation-operator.7.11.0-1.clusterserviceversion.yaml
  deploy/operator.yaml
  pkg/controller/kieapp/constants/constants.go
  pkg/controller/kieapp/defaults/defaults_test.go
  pkg/controller/kieapp/defaults/upgrade_test.go
  pkg/controller/kieapp/status/status_test.go
  tools/csv-gen/csv-gen.go
  version/version.go
Labels: approved, lgtm, release-7.11.0

#612 [RHPAM-3494] - Make pulling of dependencies and kjar validation skipp…
  config/7.10.1/common.yaml
  deploy/crds/kieapp.crd.yaml
  deploy/olm-catalog/dev/7.10.1-1/manifests/businessautomation-operator.7.10.1-1.clusterserviceversion.yaml
  deploy/olm-catalog/dev/7.10.1-1/manifests/kieapp.crd.yaml
  deploy/olm-catalog/prod/7.10.1-1/manifests/businessautomation-operator.7.10.1-1.clusterserviceversion.yaml
  deploy/olm-catalog/prod/7.10.1-1/manifests/kieapp.crd.yaml
  deploy/olm-catalog/test/7.10.1-1/manifests/businessautomation-operator.7.10.1-1.clusterserviceversion.yaml
  deploy/olm-catalog/test/7.10.1-1/manifests/kieapp.crd.yaml
  deploy/ui/form.json
  pkg/apis/app/v2/kieapp_types.go
  pkg/controller/kieapp/defaults/defaults.go
  pkg/controller/kieapp/defaults/defaults_test.go
Labels: approved, lgtm, release-7.10.1

#610 [RHPAM-3494] - Make pulling of dependencies and kjar validation skipp…
  config/7.11.0/common.yaml
  deploy/crds/kieapp.crd.yaml
  deploy/olm-catalog/dev/7.10.1-1/manifests/businessautomation-operator.7.10.1-1.clusterserviceversion.yaml
  deploy/olm-catalog/dev/7.10.1-1/manifests/kieapp.crd.yaml
  deploy/olm-catalog/dev/7.11.0-1/manifests/businessautomation-operator.7.11.0-1.clusterserviceversion.yaml
  deploy/olm-catalog/dev/7.11.0-1/manifests/kieapp.crd.yaml
  deploy/olm-catalog/prod/7.10.1-1/manifests/businessautomation-operator.7.10.1-1.clusterserviceversion.yaml
  deploy/olm-catalog/prod/7.10.1-1/manifests/kieapp.crd.yaml
  deploy/olm-catalog/prod/7.11.0-1/manifests/businessautomation-operator.7.11.0-1.clusterserviceversion.yaml
  deploy/olm-catalog/prod/7.11.0-1/manifests/kieapp.crd.yaml
  deploy/olm-catalog/test/7.10.1-1/manifests/businessautomation-operator.7.10.1-1.clusterserviceversion.yaml
  deploy/olm-catalog/test/7.10.1-1/manifests/kieapp.crd.yaml
  deploy/olm-catalog/test/7.11.0-1/manifests/businessautomation-operator.7.11.0-1.clusterserviceversion.yaml
  deploy/olm-catalog/test/7.11.0-1/manifests/kieapp.crd.yaml
  deploy/ui/form.json
  pkg/apis/app/v2/kieapp_types.go
  pkg/controller/kieapp/defaults/defaults.go
  pkg/controller/kieapp/defaults/defaults_test.go
Labels: approved, lgtm, release-7.11.0

#615 fix reconcile errors due to RHPAM-3181 PR
  config/7.11.0/common.yaml
Labels: approved, lgtm, release-7.11.0

#616 cekit upgrade for pushing bundle manifests via extra_dir
  README.md
Labels: approved, lgtm, release-7.11.0

#617 change csv file name to bypass cekit issue
  deploy/olm-catalog/dev/7.11.0-1/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/prod/7.11.0-1/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/test/7.11.0-1/manifests/businessautomation-operator.clusterserviceversion.yaml
  hack/go-build-bundle.sh
  pkg/controller/kieapp/deploy_ui_test.go
  tools/csv-gen/csv-gen.go
Labels: approved, lgtm, release-7.11.0

#618 [RHPAM-3504] remove several ocp3 specific lines and configs
  config/7.10.1/envs/rhdm-authoring-ha.yaml
  config/7.10.1/envs/rhpam-authoring-ha.yaml
  deploy/olm-catalog/dev/7.10.1-1/manifests/businessautomation-operator.7.10.1-1.clusterserviceversion.yaml
  deploy/olm-catalog/prod/7.10.1-1/manifests/businessautomation-operator.7.10.1-1.clusterserviceversion.yaml
  deploy/olm-catalog/test/7.10.1-1/manifests/businessautomation-operator.7.10.1-1.clusterserviceversion.yaml
  deploy/operator.yaml
  pkg/components/components.go
  pkg/controller/kieapp/constants/constants.go
  pkg/controller/kieapp/deploy_ui.go
  pkg/controller/kieapp/deploy_ui_test.go
Labels: approved, lgtm, release-7.10.1

#619 Revert "[RHPAM-3504] remove several ocp3 specific lines and configs"
  config/7.10.1/envs/rhdm-authoring-ha.yaml
  config/7.10.1/envs/rhpam-authoring-ha.yaml
  deploy/olm-catalog/dev/7.10.1-1/manifests/businessautomation-operator.7.10.1-1.clusterserviceversion.yaml
  deploy/olm-catalog/prod/7.10.1-1/manifests/businessautomation-operator.7.10.1-1.clusterserviceversion.yaml
  deploy/olm-catalog/test/7.10.1-1/manifests/businessautomation-operator.7.10.1-1.clusterserviceversion.yaml
  deploy/operator.yaml
  pkg/components/components.go
  pkg/controller/kieapp/constants/constants.go
  pkg/controller/kieapp/deploy_ui.go
  pkg/controller/kieapp/deploy_ui_test.go
Labels: approved, do-not-merge/hold

#589 [RHPAM-3330] Operator/Image support for Kie-Server Cluster support
  config/7.11.0/common.yaml
  deploy/crds/kieapp.crd.yaml
  deploy/ui/form.json
  pkg/apis/app/v2/kieapp_types.go
  pkg/controller/kieapp/defaults/defaults.go
  pkg/controller/kieapp/defaults/defaults_test.go
Labels: approved, lgtm, release-7.11.0

#620 [RHPAM-3504] remove several ocp3 specific lines and configs
  deploy/olm-catalog/dev/7.11.0-1/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/dev/7.11.0-1/manifests/kieapp.crd.yaml
  deploy/olm-catalog/prod/7.11.0-1/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/prod/7.11.0-1/manifests/kieapp.crd.yaml
  deploy/olm-catalog/test/7.11.0-1/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/test/7.11.0-1/manifests/kieapp.crd.yaml
  deploy/operator.yaml
  pkg/components/components.go
  pkg/controller/kieapp/constants/constants.go
  pkg/controller/kieapp/deploy_ui.go
  pkg/controller/kieapp/deploy_ui_test.go
Labels: approved, lgtm, release-7.11.0

#492 [RHPAM-3476] use openshift CA for truststore generation
  config/7.11.0/common.yaml
  config/7.11.0/dashbuilder/rhpam-standalone-dashbuilder.yaml
  deploy/crds/kieapp.crd.yaml
  deploy/crs/v2/snippets/ocp_trust.yaml
  deploy/olm-catalog/dev/7.11.0-1/manifests/kieapp.crd.yaml
  deploy/olm-catalog/prod/7.11.0-1/manifests/kieapp.crd.yaml
  deploy/olm-catalog/test/7.11.0-1/manifests/kieapp.crd.yaml
  deploy/ui/form.json
  go.mod
  go.sum
  hack/go-sdk-gen.sh
  pkg/apis/app/v2/kieapp_types.go
  pkg/apis/app/v2/zz_generated.deepcopy.go
  pkg/controller/kieapp/constants/constants.go
  pkg/controller/kieapp/defaults/defaults.go
  pkg/controller/kieapp/defaults/defaults_test.go
  pkg/controller/kieapp/deploy_ui.go
  pkg/controller/kieapp/kieapp_controller.go
  pkg/controller/kieapp/kieapp_controller_test.go
  pkg/controller/kieapp/shared/test-ca-bundle.crt
  pkg/controller/kieapp/shared/utils.go
  pkg/controller/kieapp/shared/utils_test.go
  tools/csv-gen/csv-gen.go
  vendor/github.com/pavel-v-chernykh/keystore-go/decoder.go
  vendor/github.com/pavel-v-chernykh/keystore-go/encoder.go
  vendor/github.com/pavel-v-chernykh/keystore-go/keyprotector.go
  vendor/github.com/pavel-v-chernykh/keystore-go/keystore.go
  vendor/github.com/pavel-v-chernykh/keystore-go/v4/.gitignore
  vendor/github.com/pavel-v-chernykh/keystore-go/v4/.gitpod.Dockerfile
  vendor/github.com/pavel-v-chernykh/keystore-go/v4/.gitpod.yml
  vendor/github.com/pavel-v-chernykh/keystore-go/v4/.golangci.yaml
  vendor/github.com/pavel-v-chernykh/keystore-go/v4/LICENSE
  vendor/github.com/pavel-v-chernykh/keystore-go/v4/Makefile
  vendor/github.com/pavel-v-chernykh/keystore-go/v4/README.md
  vendor/github.com/pavel-v-chernykh/keystore-go/v4/common.go
  vendor/github.com/pavel-v-chernykh/keystore-go/v4/decoder.go
  vendor/github.com/pavel-v-chernykh/keystore-go/v4/encoder.go
  vendor/github.com/pavel-v-chernykh/keystore-go/v4/go.mod
  vendor/github.com/pavel-v-chernykh/keystore-go/v4/keyprotector.go
  vendor/github.com/pavel-v-chernykh/keystore-go/v4/keystore.go
  vendor/modules.txt
Labels: approved, lgtm, release-7.11.0

#621 cleanup references to older ocp versions
  deploy/olm-catalog/dev/7.11.0-1/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/prod/7.11.0-1/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/test/7.11.0-1/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/operator.yaml
  image-bundle.yaml
  pkg/controller/kieapp/constants/constants.go
Labels: approved, lgtm, release-7.11.0

#622 [RHPAM-3476] add new unit test and fix func return
  pkg/controller/kieapp/shared/utils.go
  pkg/controller/kieapp/shared/utils_test.go
Labels: approved, lgtm, release-7.11.0

#614 [RHPAM-3331] Operator for AMQ Streams (Kafka) integration
  config/7.11.0/common.yaml
  deploy/crds/kieapp.crd.yaml
  deploy/crs/v2/snippets/kafka_config.yaml
  deploy/olm-catalog/dev/7.11.0-1/manifests/kieapp.crd.yaml
  deploy/olm-catalog/prod/7.11.0-1/manifests/kieapp.crd.yaml
  deploy/olm-catalog/test/7.11.0-1/manifests/kieapp.crd.yaml
  deploy/ui/form.json
  pkg/apis/app/v2/kieapp_types.go
  pkg/apis/app/v2/zz_generated.deepcopy.go
  pkg/controller/kieapp/constants/constants.go
  pkg/controller/kieapp/defaults/defaults.go
  pkg/controller/kieapp/defaults/defaults_test.go
Labels: approved, lgtm, release-7.11.0
