Repository kiegroup/kie-cloud-operator, pull requests merged in 2021-06, with the labels that each got.

#655 [KIECLOUD-542] Conscious Language on KieCloud repos
  deploy/crs/v2/kieapp_rhdm_production-immutable-jms.yaml
  deploy/crs/v2/kieapp_rhdm_production-immutable.yaml
  deploy/crs/v2/kieapp_rhpam_production-immutable-jms.yaml
  deploy/crs/v2/kieapp_rhpam_production-immutable.yaml
  deploy/crs/v2/snippets/immutable_s2i.yaml
  deploy/crs/v2/snippets/immutable_s2i_extra_buildconfig_envs.yaml
  deploy/ui/form.json
Labels: approved, lgtm

#658 move main branch to 7.12.0
  config/7.12.0/common.yaml
  config/7.12.0/dashbuilder/rhpam-standalone-dashbuilder.yaml
  config/7.12.0/dbs/mysql.yaml
  config/7.12.0/dbs/pim/external.yaml
  config/7.12.0/dbs/pim/mysql.yaml
  config/7.12.0/dbs/pim/postgresql.yaml
  config/7.12.0/dbs/postgresql.yaml
  config/7.12.0/dbs/servers/external.yaml
  config/7.12.0/dbs/servers/h2.yaml
  config/7.12.0/dbs/servers/mysql.yaml
  config/7.12.0/dbs/servers/postgresql.yaml
  config/7.12.0/envs/rhdm-authoring-ha.yaml
  config/7.12.0/envs/rhdm-authoring.yaml
  config/7.12.0/envs/rhdm-production-immutable.yaml
  config/7.12.0/envs/rhdm-trial.yaml
  config/7.12.0/envs/rhpam-authoring-ha.yaml
  config/7.12.0/envs/rhpam-authoring.yaml
  config/7.12.0/envs/rhpam-production-immutable.yaml
  config/7.12.0/envs/rhpam-production.yaml
  config/7.12.0/envs/rhpam-standalone-dashbuilder.yaml
  config/7.12.0/envs/rhpam-trial.yaml
  config/7.12.0/jms/activemq-jms-config.yaml
  config/7.12.0/pim/process-migration-trial.yaml
  config/7.12.0/pim/process-migration.yaml
  deploy/crs/v2/snippets/prior_version.yaml
  deploy/olm-catalog/dev/7.12.0-1/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/dev/7.12.0-1/manifests/kieapp.crd.yaml
  deploy/olm-catalog/dev/7.12.0-1/metadata/annotations.yaml
  deploy/olm-catalog/prod/7.12.0-1/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/prod/7.12.0-1/manifests/kieapp.crd.yaml
  deploy/olm-catalog/prod/7.12.0-1/metadata/annotations.yaml
  deploy/olm-catalog/test/7.12.0-1/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/test/7.12.0-1/manifests/kieapp.crd.yaml
  deploy/olm-catalog/test/7.12.0-1/metadata/annotations.yaml
  deploy/operator.yaml
  pkg/controller/kieapp/constants/constants.go
Labels: approved, lgtm, release-7.12.0

#660 [RHPAM-3763] - Endless updating loop in Kie operator
  deploy/olm-catalog/dev/7.11.0-2/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/dev/7.11.0-2/manifests/kieapp.crd.yaml
  deploy/olm-catalog/dev/7.11.0-2/metadata/annotations.yaml
  deploy/olm-catalog/prod/7.11.0-2/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/prod/7.11.0-2/manifests/kieapp.crd.yaml
  deploy/olm-catalog/prod/7.11.0-2/metadata/annotations.yaml
  deploy/olm-catalog/test/7.11.0-2/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/test/7.11.0-2/manifests/kieapp.crd.yaml
  deploy/olm-catalog/test/7.11.0-2/metadata/annotations.yaml
  version/version.go
Labels: approved, lgtm, release-7.11.0

#659 [RHPAM-3763] - Endless updating loop in Kie operator
  README.md
  hack/go-build-bundle.sh
  pkg/controller/kieapp/deploy_ui.go
Labels: approved, lgtm, release-7.11.0

#661 [RHPAM-3763] - Endless updating loop in Kie operator
  README.md
  hack/go-build-bundle.sh
  pkg/controller/kieapp/deploy_ui.go
Labels: approved, lgtm, release-7.11.1

#662 [RHPAM-3763] - Endless updating loop in Kie operator
  README.md
  hack/go-build-bundle.sh
  pkg/controller/kieapp/deploy_ui.go
Labels: approved, lgtm, release-7.12.0

#663 remove previous tag files
  config/7.11.0/common.yaml
  config/7.11.0/dashbuilder/rhpam-standalone-dashbuilder.yaml
  config/7.11.0/dbs/mysql.yaml
  config/7.11.0/dbs/pim/external.yaml
  config/7.11.0/dbs/pim/mysql.yaml
  config/7.11.0/dbs/pim/postgresql.yaml
  config/7.11.0/dbs/postgresql.yaml
  config/7.11.0/dbs/servers/external.yaml
  config/7.11.0/dbs/servers/h2.yaml
  config/7.11.0/dbs/servers/mysql.yaml
  config/7.11.0/dbs/servers/postgresql.yaml
  config/7.11.0/envs/rhdm-authoring-ha.yaml
  config/7.11.0/envs/rhdm-authoring.yaml
  config/7.11.0/envs/rhdm-production-immutable.yaml
  config/7.11.0/envs/rhdm-trial.yaml
  config/7.11.0/envs/rhpam-authoring-ha.yaml
  config/7.11.0/envs/rhpam-authoring.yaml
  config/7.11.0/envs/rhpam-production-immutable.yaml
  config/7.11.0/envs/rhpam-production.yaml
  config/7.11.0/envs/rhpam-standalone-dashbuilder.yaml
  config/7.11.0/envs/rhpam-trial.yaml
  config/7.11.0/jms/activemq-jms-config.yaml
  config/7.11.0/pim/process-migration-trial.yaml
  config/7.11.0/pim/process-migration.yaml
  deploy/olm-catalog/dev/7.12.0-1/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/prod/7.12.0-1/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/test/7.12.0-1/manifests/businessautomation-operator.clusterserviceversion.yaml
Labels: approved, lgtm, release-7.12.0
