Repository kiegroup/kie-cloud-operator, pull requests merged in 2021-08, with the labels that each got.

#674 [RHPAM-3475] - Make possible to user do completely disable SSL using …
  config/7.12.0/common.yaml
  config/7.12.0/dashbuilder/rhpam-standalone-dashbuilder.yaml
  config/7.12.0/envs/rhdm-trial.yaml
  config/7.12.0/envs/rhpam-trial.yaml
  config/7.12.0/pim/process-migration-trial.yaml
  config/7.12.0/pim/process-migration.yaml
  deploy/crds/kieapp.crd.yaml
  deploy/crs/v2/snippets/disable-ssl.yaml
  deploy/olm-catalog/dev/7.12.0-1/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/dev/7.12.0-1/manifests/kieapp.crd.yaml
  deploy/olm-catalog/prod/7.12.0-1/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/prod/7.12.0-1/manifests/kieapp.crd.yaml
  deploy/olm-catalog/test/7.12.0-1/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/test/7.12.0-1/manifests/kieapp.crd.yaml
  deploy/ui/form.json
  pkg/apis/app/v2/kieapp_types.go
  pkg/controller/kieapp/constants/constants.go
  pkg/controller/kieapp/defaults/defaults.go
  pkg/controller/kieapp/defaults/defaults_test.go
  pkg/controller/kieapp/kieapp_controller.go
Labels: approved, lgtm, release-7.12.0

#634 [RHPAM-3279] Configure CORS automatically through a flag or environment variable
  config/7.12.0/common.yaml
  config/7.12.0/dashbuilder/rhpam-standalone-dashbuilder.yaml
  config/7.12.0/envs/rhdm-trial.yaml
  config/7.12.0/envs/rhpam-trial.yaml
  deploy/crds/kieapp.crd.yaml
  deploy/olm-catalog/dev/7.12.0-1/manifests/kieapp.crd.yaml
  deploy/olm-catalog/prod/7.12.0-1/manifests/kieapp.crd.yaml
  deploy/olm-catalog/test/7.12.0-1/manifests/kieapp.crd.yaml
  deploy/ui/form.json
  pkg/apis/app/v2/kieapp_types.go
  pkg/apis/app/v2/zz_generated.deepcopy.go
  pkg/controller/kieapp/constants/constants.go
  pkg/controller/kieapp/defaults/defaults.go
  pkg/controller/kieapp/defaults/defaults_test.go
Labels: approved, lgtm, release-7.12.0

#645 [RHPAM-3623] Turn the StartupStrategy configurable on BA Operator
  config/7.12.0/common.yaml
  deploy/crds/kieapp.crd.yaml
  deploy/crs/v2/snippets/common_config_controller_based_startup_strategy.yaml
  deploy/olm-catalog/dev/7.12.0-1/manifests/kieapp.crd.yaml
  deploy/olm-catalog/prod/7.12.0-1/manifests/kieapp.crd.yaml
  deploy/olm-catalog/test/7.12.0-1/manifests/kieapp.crd.yaml
  deploy/ui/form.json
  pkg/apis/app/v2/kieapp_types.go
  pkg/apis/app/v2/zz_generated.deepcopy.go
  pkg/controller/kieapp/defaults/defaults.go
  pkg/controller/kieapp/defaults/defaults_test.go
Labels: approved, lgtm, release-7.12.0

#675 [KIECLOUD-569] - Route name is not exposed in operator CR
  config/7.12.0/common.yaml
  config/7.12.0/dashbuilder/rhpam-standalone-dashbuilder.yaml
  config/7.12.0/pim/process-migration.yaml
  deploy/crds/kieapp.crd.yaml
  deploy/crs/v2/snippets/controller_based_startup_strategy.yaml
  deploy/crs/v2/snippets/custom-route-hostname.yaml
  deploy/crs/v2/snippets/disable-ssl.yaml
  deploy/olm-catalog/dev/7.12.0-1/manifests/kieapp.crd.yaml
  deploy/olm-catalog/prod/7.12.0-1/manifests/kieapp.crd.yaml
  deploy/olm-catalog/test/7.12.0-1/manifests/kieapp.crd.yaml
  deploy/ui/form.json
  pkg/apis/app/v2/kieapp_types.go
  pkg/controller/kieapp/constants/constants.go
  pkg/controller/kieapp/defaults/defaults.go
  pkg/controller/kieapp/defaults/defaults_test.go
  pkg/controller/kieapp/shared/utils.go
Labels: approved, lgtm, release-7.12.0

#676 7.11.1-2 respin
  .gitignore
  deploy/olm-catalog/dev/7.11.1-2/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/dev/7.11.1-2/manifests/kieapp.crd.yaml
  deploy/olm-catalog/dev/7.11.1-2/metadata/annotations.yaml
  deploy/olm-catalog/prod/7.11.1-2/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/prod/7.11.1-2/manifests/kieapp.crd.yaml
  deploy/olm-catalog/prod/7.11.1-2/metadata/annotations.yaml
  deploy/olm-catalog/test/7.11.1-2/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/test/7.11.1-2/manifests/kieapp.crd.yaml
  deploy/olm-catalog/test/7.11.1-2/metadata/annotations.yaml
  version/version.go
Labels: approved, release-7.11.1

#677 Revert "7.11.1-2 respin"
  .gitignore
  deploy/olm-catalog/dev/7.11.1-2/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/dev/7.11.1-2/manifests/kieapp.crd.yaml
  deploy/olm-catalog/dev/7.11.1-2/metadata/annotations.yaml
  deploy/olm-catalog/prod/7.11.1-2/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/prod/7.11.1-2/manifests/kieapp.crd.yaml
  deploy/olm-catalog/prod/7.11.1-2/metadata/annotations.yaml
  deploy/olm-catalog/test/7.11.1-2/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/test/7.11.1-2/manifests/kieapp.crd.yaml
  deploy/olm-catalog/test/7.11.1-2/metadata/annotations.yaml
  version/version.go
Labels: approved
