Repository kiegroup/kie-cloud-operator, pull requests merged in 2022-03, with the labels that each got.

#744 [KIECLOUD-631] - Prepare kie-cloud-operator for 7.12.1 and 7.13.0
  deploy/crs/v2/snippets/prior_version.yaml
  deploy/olm-catalog/dev/7.13.0-1/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/dev/7.13.0-1/manifests/kieapp.crd.yaml
  deploy/olm-catalog/dev/7.13.0-1/metadata/annotations.yaml
  deploy/olm-catalog/prod/7.13.0-1/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/prod/7.13.0-1/manifests/kieapp.crd.yaml
  deploy/olm-catalog/prod/7.13.0-1/metadata/annotations.yaml
  deploy/olm-catalog/test/7.13.0-1/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/test/7.13.0-1/manifests/kieapp.crd.yaml
  deploy/olm-catalog/test/7.13.0-1/metadata/annotations.yaml
  deploy/operator.yaml
  pkg/controller/kieapp/constants/constants.go
  pkg/controller/kieapp/defaults/upgrade_test.go
  rhpam-config/7.13.0/common.yaml
  rhpam-config/7.13.0/dashbuilder/rhpam-standalone-dashbuilder.yaml
  rhpam-config/7.13.0/dbs/mysql.yaml
  rhpam-config/7.13.0/dbs/pim/external.yaml
  rhpam-config/7.13.0/dbs/pim/mysql.yaml
  rhpam-config/7.13.0/dbs/pim/postgresql.yaml
  rhpam-config/7.13.0/dbs/postgresql.yaml
  rhpam-config/7.13.0/dbs/servers/external.yaml
  rhpam-config/7.13.0/dbs/servers/h2.yaml
  rhpam-config/7.13.0/dbs/servers/mysql.yaml
  rhpam-config/7.13.0/dbs/servers/postgresql.yaml
  rhpam-config/7.13.0/envs/rhdm-authoring-ha.yaml
  rhpam-config/7.13.0/envs/rhdm-authoring.yaml
  rhpam-config/7.13.0/envs/rhdm-production-immutable.yaml
  rhpam-config/7.13.0/envs/rhdm-trial.yaml
  rhpam-config/7.13.0/envs/rhpam-authoring-ha.yaml
  rhpam-config/7.13.0/envs/rhpam-authoring.yaml
  rhpam-config/7.13.0/envs/rhpam-production-immutable.yaml
  rhpam-config/7.13.0/envs/rhpam-production.yaml
  rhpam-config/7.13.0/envs/rhpam-standalone-dashbuilder.yaml
  rhpam-config/7.13.0/envs/rhpam-trial.yaml
  rhpam-config/7.13.0/jms/activemq-jms-config.yaml
  rhpam-config/7.13.0/pim/process-migration.yaml
Labels: approved, lgtm, release-7.13.0

#745 [KIECLOUD-631] - Prepare kie-cloud-operator for 7.12.1 and 7.13.0
  rhpam-config/7.12.0/common.yaml
  rhpam-config/7.12.0/dashbuilder/rhpam-standalone-dashbuilder.yaml
  rhpam-config/7.12.0/dbs/mysql.yaml
  rhpam-config/7.12.0/dbs/pim/external.yaml
  rhpam-config/7.12.0/dbs/pim/mysql.yaml
  rhpam-config/7.12.0/dbs/pim/postgresql.yaml
  rhpam-config/7.12.0/dbs/postgresql.yaml
  rhpam-config/7.12.0/dbs/servers/external.yaml
  rhpam-config/7.12.0/dbs/servers/h2.yaml
  rhpam-config/7.12.0/dbs/servers/mysql.yaml
  rhpam-config/7.12.0/dbs/servers/postgresql.yaml
  rhpam-config/7.12.0/envs/rhdm-authoring-ha.yaml
  rhpam-config/7.12.0/envs/rhdm-authoring.yaml
  rhpam-config/7.12.0/envs/rhdm-production-immutable.yaml
  rhpam-config/7.12.0/envs/rhdm-trial.yaml
  rhpam-config/7.12.0/envs/rhpam-authoring-ha.yaml
  rhpam-config/7.12.0/envs/rhpam-authoring.yaml
  rhpam-config/7.12.0/envs/rhpam-production-immutable.yaml
  rhpam-config/7.12.0/envs/rhpam-production.yaml
  rhpam-config/7.12.0/envs/rhpam-standalone-dashbuilder.yaml
  rhpam-config/7.12.0/envs/rhpam-trial.yaml
  rhpam-config/7.12.0/jms/activemq-jms-config.yaml
  rhpam-config/7.12.0/pim/process-migration.yaml
Labels: approved, lgtm, release-7.13.0

#747 [KIECLOUD-628] - Update rhdm quickstarts references on operator
  deploy/crds/kieapp.crd.v1beta1.yaml
  deploy/crds/kieapp.crd.yaml
  deploy/crs/v2/kieapp_rhdm_production-immutable-jms.yaml
  deploy/crs/v2/kieapp_rhdm_production-immutable.yaml
  deploy/crs/v2/snippets/immutable_deployment.yaml
  deploy/crs/v2/snippets/immutable_s2i.yaml
  deploy/crs/v2/snippets/immutable_s2i_extra_buildconfig_envs.yaml
  deploy/olm-catalog/dev/7.13.0-1/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/dev/7.13.0-1/manifests/kieapp.crd.yaml
  deploy/olm-catalog/prod/7.13.0-1/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/prod/7.13.0-1/manifests/kieapp.crd.yaml
  deploy/olm-catalog/test/7.13.0-1/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/test/7.13.0-1/manifests/kieapp.crd.yaml
  deploy/ui/form.json
  pkg/apis/app/v2/kieapp_types.go
  pkg/controller/kieapp/defaults/defaults_test.go
Labels: approved, lgtm, release-7.13.0

#755 [RHPAM-4218] - Matching the description in Operator UI and KieApp CRD for persistRepos
  deploy/crds/kieapp.crd.yaml
  deploy/olm-catalog/dev/7.13.0-1/manifests/kieapp.crd.yaml
  deploy/olm-catalog/prod/7.13.0-1/manifests/kieapp.crd.yaml
  deploy/olm-catalog/test/7.13.0-1/manifests/kieapp.crd.yaml
  pkg/apis/app/v2/kieapp_types.go
Labels: approved, lgtm, release-7.13.0

#752 [KIECLOUD-605] In Operator use Kie Server's RHDM mode
  deploy/crds/kieapp.crd.yaml
  deploy/olm-catalog/dev/7.13.0-1/manifests/kieapp.crd.yaml
  deploy/olm-catalog/prod/7.13.0-1/manifests/kieapp.crd.yaml
  deploy/olm-catalog/test/7.13.0-1/manifests/kieapp.crd.yaml
  deploy/ui/form.json
  pkg/apis/app/v2/kieapp_types.go
  pkg/apis/app/v2/zz_generated.deepcopy.go
  pkg/controller/kieapp/defaults/defaults.go
  pkg/controller/kieapp/defaults/defaults_test.go
  pkg/controller/kieapp/defaults/upgrade_test.go
  rhpam-config/7.13.0/common.yaml
Labels: approved, lgtm, release-7.13.0

#750 [RHPAM-3528] Increase KieExecutorMDB threads in RHPAM image
  deploy/crds/kieapp.crd.yaml
  deploy/olm-catalog/dev/7.12.1-1/manifests/kieapp.crd.yaml
  deploy/olm-catalog/prod/7.12.1-1/manifests/kieapp.crd.yaml
  deploy/olm-catalog/test/7.12.1-1/manifests/kieapp.crd.yaml
  deploy/ui/form.json
  pkg/apis/app/v2/kieapp_types.go
  pkg/apis/app/v2/zz_generated.deepcopy.go
  pkg/controller/kieapp/defaults/defaults.go
  pkg/controller/kieapp/defaults/defaults_test.go
  rhpam-config/7.12.1/common.yaml
Labels: approved, lgtm, release-7.12.1, needs-cherry-pick :cherries:

#756 [RHPAM-3528] Increase KieExecutorMDB threads in RHPAM image
  deploy/crds/kieapp.crd.yaml
  deploy/olm-catalog/dev/7.12.1-1/manifests/kieapp.crd.yaml
  deploy/olm-catalog/dev/7.13.0-1/manifests/kieapp.crd.yaml
  deploy/olm-catalog/prod/7.12.1-1/manifests/kieapp.crd.yaml
  deploy/olm-catalog/prod/7.13.0-1/manifests/kieapp.crd.yaml
  deploy/olm-catalog/test/7.12.1-1/manifests/kieapp.crd.yaml
  deploy/olm-catalog/test/7.13.0-1/manifests/kieapp.crd.yaml
  deploy/ui/form.json
  pkg/apis/app/v2/kieapp_types.go
  pkg/apis/app/v2/zz_generated.deepcopy.go
  pkg/controller/kieapp/defaults/defaults.go
  pkg/controller/kieapp/defaults/defaults_test.go
  rhpam-config/7.12.1/common.yaml
  rhpam-config/7.13.0/common.yaml
Labels: approved, release-7.13.0

#757 [KIECLOUD-605] - In Operator use Kie Server's RHDM mode
  pkg/controller/kieapp/defaults/defaults.go
  pkg/controller/kieapp/defaults/defaults_test.go
  rhpam-config/7.13.0/common.yaml
Labels: approved, lgtm, release-7.13.0

#760 [RHPAM-3528] Increase KieExecutorMDB threads in RHPAM image
  pkg/apis/app/v2/kieapp_types.go
Labels: approved, lgtm, release-7.13.0

#759 [RHPAM-3528] Increase KieExecutorMDB threads in RHPAM image
  pkg/apis/app/v2/kieapp_types.go
Labels: approved, lgtm, release-7.12.1

#758 [RHPAM-4140] Hide adminPassword from Business automation operator
  deploy/crds/kieapp.crd.yaml
  deploy/crs/v2/snippets/auth_secret.yaml
  deploy/olm-catalog/dev/7.13.0-1/manifests/kieapp.crd.yaml
  deploy/olm-catalog/prod/7.13.0-1/manifests/kieapp.crd.yaml
  deploy/olm-catalog/test/7.13.0-1/manifests/kieapp.crd.yaml
  deploy/ui/form.json
  pkg/apis/app/v2/kieapp_types.go
  pkg/controller/kieapp/constants/constants.go
  pkg/controller/kieapp/defaults/defaults.go
  pkg/controller/kieapp/defaults/defaults_test.go
  rhpam-config/7.13.0/common.yaml
  rhpam-config/7.13.0/dashbuilder/rhpam-standalone-dashbuilder.yaml
Labels: approved, lgtm, release-7.13.0

#767 [KIECLOUD-627] 7.13 Checkpoint - Increase JDG version to 8.3.3
  deploy/olm-catalog/dev/7.13.0-1/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/prod/7.13.0-1/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/test/7.13.0-1/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/operator.yaml
  pkg/controller/kieapp/constants/constants.go
Labels: approved, lgtm, release-7.13.0

#764 [RHPAM-4125] Add capability to configure Route termination
  deploy/crds/kieapp.crd.yaml
  deploy/olm-catalog/dev/7.13.0-1/manifests/kieapp.crd.yaml
  deploy/olm-catalog/prod/7.13.0-1/manifests/kieapp.crd.yaml
  deploy/olm-catalog/test/7.13.0-1/manifests/kieapp.crd.yaml
  deploy/ui/form.json
  pkg/apis/app/v2/kieapp_types.go
  pkg/apis/app/v2/zz_generated.deepcopy.go
  pkg/controller/kieapp/defaults/defaults.go
  pkg/controller/kieapp/defaults/defaults_test.go
  rhpam-config/7.13.0/common.yaml
  rhpam-config/7.13.0/dashbuilder/rhpam-standalone-dashbuilder.yaml
  rhpam-config/7.13.0/pim/process-migration.yaml
Labels: approved, lgtm, release-7.13.0

#766 [RHPAM-4239] KieExecutorMDB property in Operator UI use wrong name
  deploy/ui/form.json
Labels: approved, lgtm, release-7.13.0

#768 [KIECLOUD-626] - 7.13.0 Checkpoint - Increase AMQ broker version to 7…
  deploy/olm-catalog/dev/7.13.0-1/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/prod/7.13.0-1/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/test/7.13.0-1/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/operator.yaml
  pkg/controller/kieapp/constants/constants.go
  pkg/controller/kieapp/defaults/defaults_test.go
Labels: approved, lgtm, release-7.13.0
