Repository kiegroup/kie-cloud-operator, pull requests merged in 2022-06, with the labels that each got.

#791 [KIECLOUD-640] - Fix naming of deploy yaml files
  deploy/cluster_role.yaml
  deploy/cluster_role_binding.yaml
  deploy/olm-catalog/dev/7.13.1-1/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/prod/7.13.1-1/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/test/7.13.1-1/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/role_binding.yaml
  deploy/service_account.yaml
  pkg/components/components.go
  tools/csv-gen/csv-gen.go
Labels: approved, lgtm, release-7.13.1

#795 [RHPAM-4167] Name of the property is wrongly set from console cr form
  deploy/ui/form.json
Labels: bug, approved, lgtm, needs-review, needs-cherry-pick :cherries:

#797 [RHPAM-4167] Name of the property is wrongly set from console cr form
  deploy/ui/form.json
Labels: approved, lgtm, release-7.13.1, cherry-pick :cherries:
