Repository kiegroup/kie-cloud-operator, pull requests merged in 2022-07, with the labels that each got.

#802 [KIECLOUD-646] - Rebranding changes on the kie-cloud-operator reposit…
  image-bundle.yaml
  image.yaml
Labels: approved, lgtm

#801 [KIECLOUD-646] - remove prior version configuration
  deploy/olm-catalog/dev/7.13.0-1/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/dev/7.13.0-1/manifests/kieapp.crd.yaml
  deploy/olm-catalog/dev/7.13.0-1/metadata/annotations.yaml
  deploy/olm-catalog/dev/8.0.0-1/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/dev/manifests/kieapp.crd.yaml
  deploy/olm-catalog/prod/7.13.0-1/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/prod/7.13.0-1/manifests/kieapp.crd.yaml
  deploy/olm-catalog/prod/7.13.0-1/metadata/annotations.yaml
  deploy/olm-catalog/prod/8.0.0-1/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/prod/manifests/kieapp.crd.yaml
  deploy/olm-catalog/test/7.13.0-1/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/test/7.13.0-1/manifests/kieapp.crd.yaml
  deploy/olm-catalog/test/7.13.0-1/metadata/annotations.yaml
  deploy/olm-catalog/test/8.0.0-1/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/test/manifests/kieapp.crd.yaml
  deploy/operator.yaml
  getversion.go
  pkg/controller/kieapp/constants/constants.go
  pkg/controller/kieapp/defaults/defaults_test.go
  pkg/controller/kieapp/defaults/upgrade_test.go
  pkg/controller/kieapp/status/status_test.go
  rhpam-config/7.13.0/common.yaml
  rhpam-config/7.13.0/dashbuilder/rhpam-standalone-dashbuilder.yaml
  rhpam-config/7.13.0/dbs/mysql.yaml
  rhpam-config/7.13.0/dbs/pim/external.yaml
  rhpam-config/7.13.0/dbs/pim/mysql.yaml
  rhpam-config/7.13.0/dbs/pim/postgresql.yaml
  rhpam-config/7.13.0/dbs/postgresql.yaml
  rhpam-config/7.13.0/dbs/servers/external.yaml
  rhpam-config/7.13.0/dbs/servers/h2.yaml
  rhpam-config/7.13.0/dbs/servers/mysql.yaml
  rhpam-config/7.13.0/dbs/servers/postgresql.yaml
  rhpam-config/7.13.0/envs/rhdm-authoring-ha.yaml
  rhpam-config/7.13.0/envs/rhdm-authoring.yaml
  rhpam-config/7.13.0/envs/rhdm-production-immutable.yaml
  rhpam-config/7.13.0/envs/rhdm-trial.yaml
  rhpam-config/7.13.0/envs/rhpam-authoring-ha.yaml
  rhpam-config/7.13.0/envs/rhpam-authoring.yaml
  rhpam-config/7.13.0/envs/rhpam-production-immutable.yaml
  rhpam-config/7.13.0/envs/rhpam-production.yaml
  rhpam-config/7.13.0/envs/rhpam-standalone-dashbuilder.yaml
  rhpam-config/7.13.0/envs/rhpam-trial.yaml
  rhpam-config/7.13.0/jms/activemq-jms-config.yaml
  rhpam-config/7.13.0/pim/process-migration.yaml
  tools/csv-gen/csv-gen.go
  version/version.go
Labels: approved, lgtm, release-7.13.0-blue

#806 replace prod with staging registry for prod csv
  deploy/olm-catalog/dev/8.0.0-1/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/prod/8.0.0-1/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/test/8.0.0-1/manifests/businessautomation-operator.clusterserviceversion.yaml
  pkg/controller/kieapp/constants/constants.go
  tools/csv-gen/csv-gen.go
Labels: approved, release-bamoe-8.0.0

#811 add capabilities label to pass cvp tests
  deploy/olm-catalog/dev/8.0.0-1/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/prod/8.0.0-1/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/test/8.0.0-1/manifests/businessautomation-operator.clusterserviceversion.yaml
  tools/csv-gen/csv-gen.go
Labels: approved

#812 [7.13.x-blue] sync operators channels.v1 from image-bundle with metadata/annotations.yaml
  image-bundle.yaml
Labels: approved, lgtm, release-bamoe-8.0.0

#815 [KIECLOUD-650] - Error Package businessautomation-operator already ex…
  README.md
  deploy/olm-catalog/dev/8.0.0-1/manifests/bamoe-businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/dev/8.0.0-1/metadata/annotations.yaml
  deploy/olm-catalog/prod/8.0.0-1/manifests/bamoe-businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/prod/8.0.0-1/metadata/annotations.yaml
  deploy/olm-catalog/test/8.0.0-1/manifests/bamoe-businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/test/8.0.0-1/metadata/annotations.yaml
  deploy/operator.yaml
  deploy/role.yaml
  hack/go-build-bundle.sh
  image-bundle.yaml
  pkg/controller/kieapp/deploy_ui_test.go
  tools/csv-gen/csv-gen.go
Labels: approved, lgtm, release-bamoe-8.0.0

#816 [KIECLOUD-653] - Rename documentation and Product page links on opera…
  deploy/olm-catalog/dev/8.0.0-1/manifests/bamoe-businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/prod/8.0.0-1/manifests/bamoe-businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/test/8.0.0-1/manifests/bamoe-businessautomation-operator.clusterserviceversion.yaml
  tools/csv-gen/csv-gen.go
Labels: approved, lgtm, release-bamoe-8.0.0

#817 [KIECLOUD-653] - Rename documentation and Product page links on opera…
  deploy/olm-catalog/dev/8.0.0-1/manifests/bamoe-businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/prod/8.0.0-1/manifests/bamoe-businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/test/8.0.0-1/manifests/bamoe-businessautomation-operator.clusterserviceversion.yaml
  image-bundle.yaml
  image.yaml
  tools/csv-gen/csv-gen.go
Labels: approved, release-bamoe-8.0.0

#818 [RHPAM-4463] - BAMOE Operator bundle image description contians Red H…
  deploy/olm-catalog/dev/8.0.0-1/manifests/bamoe-businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/prod/8.0.0-1/manifests/bamoe-businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/test/8.0.0-1/manifests/bamoe-businessautomation-operator.clusterserviceversion.yaml
  tools/csv-gen/csv-gen.go
Labels: approved, lgtm, release-bamoe-8.0.0

#819 [RHPAM-4463] - Operator bundle image description contians Red Hat Dec…
  deploy/olm-catalog/dev/7.13.1-1/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/prod/7.13.1-1/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/test/7.13.1-1/manifests/businessautomation-operator.clusterserviceversion.yaml
  tools/csv-gen/csv-gen.go
Labels: approved, lgtm, release-7.13.1

#820 [RHPAM-4463] - Operator bundle image description contians Red Hat Dec…
  deploy/olm-catalog/dev/7.13.0-1/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/prod/7.13.0-1/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/test/7.13.0-1/manifests/businessautomation-operator.clusterserviceversion.yaml
  tools/csv-gen/csv-gen.go
Labels: approved, lgtm, release-7.13.0

#821 fix typo, extra space
  deploy/olm-catalog/dev/8.0.0-1/manifests/bamoe-businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/prod/8.0.0-1/manifests/bamoe-businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/test/8.0.0-1/manifests/bamoe-businessautomation-operator.clusterserviceversion.yaml
  tools/csv-gen/csv-gen.go
Labels: approved
