Repository kiegroup/kie-cloud-operator, pull requests merged in 2022-08, with the labels that each got.

#822 [RHPAM-4438] Sensitive Information In ENV And Pod Logs
  go.mod
  go.sum
  pkg/controller/kieapp/kieapp_controller.go
  vendor/github.com/RHsyseng/operator-utils/internal/platform/platform_versioner.go
  vendor/github.com/RHsyseng/operator-utils/pkg/logs/logs.go
  vendor/github.com/RHsyseng/operator-utils/pkg/resource/compare/defaults.go
  vendor/github.com/RHsyseng/operator-utils/pkg/resource/compare/map.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1/thanos_types.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1/types.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: approved, lgtm, release-7.13.1, needs-cherry-pick :cherries:

#823 [RHPAM-4492] - BAMOE pam operator - enable back the seamless upgrade …
  deploy/crs/v2/snippets/prior_version.yaml
  deploy/olm-catalog/dev/8.0.1-1/manifests/bamoe-businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/dev/8.0.1-1/manifests/kieapp.crd.yaml
  deploy/olm-catalog/dev/8.0.1-1/metadata/annotations.yaml
  deploy/olm-catalog/prod/8.0.1-1/manifests/bamoe-businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/prod/8.0.1-1/manifests/kieapp.crd.yaml
  deploy/olm-catalog/prod/8.0.1-1/metadata/annotations.yaml
  deploy/olm-catalog/test/8.0.1-1/manifests/bamoe-businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/test/8.0.1-1/manifests/kieapp.crd.yaml
  deploy/olm-catalog/test/8.0.1-1/metadata/annotations.yaml
  deploy/operator.yaml
  getversion.go
  pkg/controller/kieapp/constants/constants.go
  pkg/controller/kieapp/defaults/defaults_test.go
  pkg/controller/kieapp/defaults/upgrade_test.go
  pkg/controller/kieapp/status/status_test.go
  rhpam-config/8.0.1/common.yaml
  rhpam-config/8.0.1/dashbuilder/rhpam-standalone-dashbuilder.yaml
  rhpam-config/8.0.1/dbs/mysql.yaml
  rhpam-config/8.0.1/dbs/pim/external.yaml
  rhpam-config/8.0.1/dbs/pim/mysql.yaml
  rhpam-config/8.0.1/dbs/pim/postgresql.yaml
  rhpam-config/8.0.1/dbs/postgresql.yaml
  rhpam-config/8.0.1/dbs/servers/external.yaml
  rhpam-config/8.0.1/dbs/servers/h2.yaml
  rhpam-config/8.0.1/dbs/servers/mysql.yaml
  rhpam-config/8.0.1/dbs/servers/postgresql.yaml
  rhpam-config/8.0.1/envs/rhdm-authoring-ha.yaml
  rhpam-config/8.0.1/envs/rhdm-authoring.yaml
  rhpam-config/8.0.1/envs/rhdm-production-immutable.yaml
  rhpam-config/8.0.1/envs/rhdm-trial.yaml
  rhpam-config/8.0.1/envs/rhpam-authoring-ha.yaml
  rhpam-config/8.0.1/envs/rhpam-authoring.yaml
  rhpam-config/8.0.1/envs/rhpam-production-immutable.yaml
  rhpam-config/8.0.1/envs/rhpam-production.yaml
  rhpam-config/8.0.1/envs/rhpam-standalone-dashbuilder.yaml
  rhpam-config/8.0.1/envs/rhpam-trial.yaml
  rhpam-config/8.0.1/jms/activemq-jms-config.yaml
  rhpam-config/8.0.1/pim/process-migration.yaml
  tools/csv-gen/csv-gen.go
  version/version.go
Labels: approved, lgtm

#808 [RHPAM-4439] Vulnerable Version Of PostgreSQL Found
  deploy/olm-catalog/dev/7.13.1-1/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/prod/7.13.1-1/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/test/7.13.1-1/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/operator.yaml
  pkg/controller/kieapp/constants/constants.go
  pkg/controller/kieapp/kieapp_controller.go
Labels: approved, lgtm, release-7.13.1

#810 [RHPAM-4439] Vulnerable Version Of PostgreSQL Found
  deploy/olm-catalog/dev/8.0.0-1/manifests/bamoe-businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/prod/8.0.0-1/manifests/bamoe-businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/test/8.0.0-1/manifests/bamoe-businessautomation-operator.clusterserviceversion.yaml
  deploy/operator.yaml
  pkg/controller/kieapp/constants/constants.go
  pkg/controller/kieapp/kieapp_controller.go
Labels: approved, lgtm, release-bamoe-8.0.1
