Repository kiegroup/kie-cloud-operator, pull requests merged in 2022-04, with the labels that each got.

#772 [KIECLOUD-636] - Prepare kie-cloud-operator for 7.13.0 and 7.13.1 rel…
  deploy/crs/v2/snippets/prior_version.yaml
  deploy/olm-catalog/dev/7.13.1-1/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/dev/7.13.1-1/manifests/kieapp.crd.yaml
  deploy/olm-catalog/dev/7.13.1-1/metadata/annotations.yaml
  deploy/olm-catalog/prod/7.13.1-1/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/prod/7.13.1-1/manifests/kieapp.crd.yaml
  deploy/olm-catalog/prod/7.13.1-1/metadata/annotations.yaml
  deploy/olm-catalog/test/7.13.1-1/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/test/7.13.1-1/manifests/kieapp.crd.yaml
  deploy/olm-catalog/test/7.13.1-1/metadata/annotations.yaml
  deploy/operator.yaml
  pkg/controller/kieapp/constants/constants.go
  pkg/controller/kieapp/defaults/defaults_test.go
  pkg/controller/kieapp/defaults/upgrade_test.go
  pkg/controller/kieapp/kieapp_controller_test.go
  rhpam-config/7.13.1/common.yaml
  rhpam-config/7.13.1/dashbuilder/rhpam-standalone-dashbuilder.yaml
  rhpam-config/7.13.1/dbs/mysql.yaml
  rhpam-config/7.13.1/dbs/pim/external.yaml
  rhpam-config/7.13.1/dbs/pim/mysql.yaml
  rhpam-config/7.13.1/dbs/pim/postgresql.yaml
  rhpam-config/7.13.1/dbs/postgresql.yaml
  rhpam-config/7.13.1/dbs/servers/external.yaml
  rhpam-config/7.13.1/dbs/servers/h2.yaml
  rhpam-config/7.13.1/dbs/servers/mysql.yaml
  rhpam-config/7.13.1/dbs/servers/postgresql.yaml
  rhpam-config/7.13.1/envs/rhdm-authoring-ha.yaml
  rhpam-config/7.13.1/envs/rhdm-authoring.yaml
  rhpam-config/7.13.1/envs/rhdm-production-immutable.yaml
  rhpam-config/7.13.1/envs/rhdm-trial.yaml
  rhpam-config/7.13.1/envs/rhpam-authoring-ha.yaml
  rhpam-config/7.13.1/envs/rhpam-authoring.yaml
  rhpam-config/7.13.1/envs/rhpam-production-immutable.yaml
  rhpam-config/7.13.1/envs/rhpam-production.yaml
  rhpam-config/7.13.1/envs/rhpam-standalone-dashbuilder.yaml
  rhpam-config/7.13.1/envs/rhpam-trial.yaml
  rhpam-config/7.13.1/jms/activemq-jms-config.yaml
  rhpam-config/7.13.1/pim/process-migration.yaml
Labels: approved, lgtm, release-7.13.1

#773 [KIECLOUD-636] - Prepare kie-cloud-operator for 7.13.0 and 7.13.1
  rhpam-config/7.12.1/common.yaml
  rhpam-config/7.12.1/dashbuilder/rhpam-standalone-dashbuilder.yaml
  rhpam-config/7.12.1/dbs/mysql.yaml
  rhpam-config/7.12.1/dbs/pim/external.yaml
  rhpam-config/7.12.1/dbs/pim/mysql.yaml
  rhpam-config/7.12.1/dbs/pim/postgresql.yaml
  rhpam-config/7.12.1/dbs/postgresql.yaml
  rhpam-config/7.12.1/dbs/servers/external.yaml
  rhpam-config/7.12.1/dbs/servers/h2.yaml
  rhpam-config/7.12.1/dbs/servers/mysql.yaml
  rhpam-config/7.12.1/dbs/servers/postgresql.yaml
  rhpam-config/7.12.1/envs/rhdm-authoring-ha.yaml
  rhpam-config/7.12.1/envs/rhdm-authoring.yaml
  rhpam-config/7.12.1/envs/rhdm-production-immutable.yaml
  rhpam-config/7.12.1/envs/rhdm-trial.yaml
  rhpam-config/7.12.1/envs/rhpam-authoring-ha.yaml
  rhpam-config/7.12.1/envs/rhpam-authoring.yaml
  rhpam-config/7.12.1/envs/rhpam-production-immutable.yaml
  rhpam-config/7.12.1/envs/rhpam-production.yaml
  rhpam-config/7.12.1/envs/rhpam-standalone-dashbuilder.yaml
  rhpam-config/7.12.1/envs/rhpam-trial.yaml
  rhpam-config/7.12.1/jms/activemq-jms-config.yaml
  rhpam-config/7.12.1/pim/process-migration.yaml
Labels: approved, release-7.13.1

#774 bump bundle version to 7.12.1-2
  deploy/olm-catalog/dev/7.12.1-2/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/dev/7.12.1-2/manifests/kieapp.crd.yaml
  deploy/olm-catalog/dev/7.12.1-2/metadata/annotations.yaml
  deploy/olm-catalog/prod/7.12.1-2/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/prod/7.12.1-2/manifests/kieapp.crd.yaml
  deploy/olm-catalog/prod/7.12.1-2/metadata/annotations.yaml
  deploy/olm-catalog/test/7.12.1-2/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/test/7.12.1-2/manifests/kieapp.crd.yaml
  deploy/olm-catalog/test/7.12.1-2/metadata/annotations.yaml
  deploy/operator.yaml
  version/version.go
Labels: approved, lgtm

#776 Removing sa from operator.yaml to avoid CVP pipiline failures
  deploy/operator.yaml
  pkg/apis/app/v2/zz_generated.deepcopy.go
Labels: approved, lgtm

#775 bump bundle prior version to 7.12.1-2
  deploy/olm-catalog/dev/7.13.0-1/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/prod/7.13.0-1/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/test/7.13.0-1/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/operator.yaml
  version/version.go
Labels: approved, lgtm

#777 Added 7.12.1-2 olm-catalog files
  deploy/olm-catalog/dev/7.12.1-2/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/dev/7.12.1-2/manifests/kieapp.crd.yaml
  deploy/olm-catalog/dev/7.12.1-2/metadata/annotations.yaml
  deploy/olm-catalog/prod/7.12.1-2/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/prod/7.12.1-2/manifests/kieapp.crd.yaml
  deploy/olm-catalog/prod/7.12.1-2/metadata/annotations.yaml
  deploy/olm-catalog/test/7.12.1-2/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/test/7.12.1-2/manifests/kieapp.crd.yaml
  deploy/olm-catalog/test/7.12.1-2/metadata/annotations.yaml
Labels: approved, lgtm

#778 [KIECLOUD-606] - Remove from olm catalog manifest RHDM images references
  deploy/olm-catalog/dev/7.13.1-1/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/prod/7.13.1-1/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/test/7.13.1-1/manifests/businessautomation-operator.clusterserviceversion.yaml
  pkg/controller/kieapp/constants/constants.go
  pkg/controller/kieapp/defaults/defaults.go
Labels: approved, lgtm, release-7.13.1
