Repository kiegroup/kie-cloud-operator, pull requests merged in 2022-02, with the labels that each got.

#735 [RHPAM-4075] - Kie repository persistence is disabled in rhpam-trial
  deploy/ui/form.json
  pkg/controller/kieapp/defaults/defaults.go
  pkg/controller/kieapp/defaults/defaults_test.go
Labels: approved, lgtm

#734 [RHPAM-4158] - CRD conflicts when installing different version of ope…
  deploy/crds/kieapp.crd.yaml
  deploy/olm-catalog/dev/7.12.0-1/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/dev/7.12.0-1/manifests/kieapp.crd.yaml
  deploy/olm-catalog/prod/7.12.0-1/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/prod/7.12.0-1/manifests/kieapp.crd.yaml
  deploy/olm-catalog/test/7.12.0-1/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/test/7.12.0-1/manifests/kieapp.crd.yaml
  pkg/apis/app/v2/kieapp_types.go
Labels: approved, lgtm, release-7.12.0, needs-cherry-pick :cherries:

#739 [RHPAM-4158] - CRD conflicts when installing different version of
  deploy/olm-catalog/dev/7.12.0-2/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/dev/7.12.0-2/manifests/kieapp.crd.yaml
  deploy/olm-catalog/dev/7.12.0-2/metadata/annotations.yaml
  deploy/olm-catalog/prod/7.12.0-2/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/prod/7.12.0-2/manifests/kieapp.crd.yaml
  deploy/olm-catalog/prod/7.12.0-2/metadata/annotations.yaml
  deploy/olm-catalog/test/7.12.0-2/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/test/7.12.0-2/manifests/kieapp.crd.yaml
  deploy/olm-catalog/test/7.12.0-2/metadata/annotations.yaml
  version/version.go
Labels: approved, lgtm, release-7.12.0
