Repository kiegroup/kie-cloud-operator, pull requests merged in 2022-01, with the labels that each got.

#719 [RHPAM-4109] Cannot open created project - FileSystem Index fails - Nullpointer
  deploy/olm-catalog/dev/7.12.0-1/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/prod/7.12.0-1/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/test/7.12.0-1/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/operator.yaml
  pkg/controller/kieapp/constants/constants.go
Labels: approved, lgtm

#720 [RHPAM-4109] Cannot open created project - FileSystem Index fails - Nullpointer
  deploy/olm-catalog/dev/7.12.0-1/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/dev/7.12.1-1/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/prod/7.12.0-1/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/prod/7.12.1-1/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/test/7.12.0-1/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/test/7.12.1-1/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/operator.yaml
  pkg/controller/kieapp/constants/constants.go
Labels: approved, lgtm, release-7.12.1, cherry-pick :cherries:

#721 [RHPAM-4115] Missing routes/custom-host permision for BA Operator
  deploy/olm-catalog/dev/7.12.0-1/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/prod/7.12.0-1/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/test/7.12.0-1/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/role.yaml
  pkg/components/components.go
Labels: approved, lgtm, release-7.12.0, needs-cherry-pick :cherries:

#722 [RHPAM-4115] Missing routes/custom-host permision for BA Operator
  deploy/olm-catalog/dev/7.12.1-1/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/prod/7.12.1-1/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/test/7.12.1-1/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/role.yaml
  pkg/components/components.go
Labels: approved, lgtm, release-7.12.1, cherry-pick :cherries:

#724 [KIECLOUD-616] - uptade go-toolset image to 1.16
  image.yaml
Labels: approved, lgtm, release-7.12.0, needs-cherry-pick :cherries:

#725 [KIECLOUD-616] - uptade go-toolset image to 1.16
  image.yaml
Labels: approved, release-7.12.1, cherry-pick :cherries:

#728 Updated Reviewers file to include davidesalerno
  OWNERS
Labels: approved, lgtm

#730 [RHPAM-4128] Fix label and description for routeHostname in Operator UI
  deploy/ui/form.json
Labels: approved, lgtm, release-7.12.1

#731 [RHPAM-3787] - DockerImage kind is not accepted in Business Automatio…
  deploy/olm-catalog/dev/7.12.1-1/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/prod/7.12.1-1/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/test/7.12.1-1/manifests/businessautomation-operator.clusterserviceversion.yaml
  pkg/controller/kieapp/defaults/defaults.go
  pkg/controller/kieapp/defaults/defaults_test.go
Labels: approved, lgtm, release-7.12.1
