Repository kiegroup/kie-cloud-operator, pull requests merged in 2022-05, with the labels that each got.

#779 [RHPAM-4140] Hide adminPassword from Business automation operator kieapp instance
  pkg/controller/kieapp/defaults/defaults.go
Labels: lgtm, release-7.13.1

#783 [RHPAM-4140-7.13] Hide adminPassword from Business automation operator kieapp instance
  pkg/controller/kieapp/defaults/defaults.go
Labels: lgtm

#784 [KIECLOUD-634] Revert used RHDG version to 8.1
  deploy/olm-catalog/dev/7.13.0-1/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/prod/7.13.0-1/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/test/7.13.0-1/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/operator.yaml
  pkg/controller/kieapp/constants/constants.go
Labels: lgtm

#786 [RHPAM-4224] - Installer generates wrong Min/Max connection pool size
  deploy/ui/form.json
Labels: lgtm

#790 update go-toolset image to 1.17.7
  image.yaml
Labels: approved, lgtm, release-7.13.0

#792 update go-toolset image to 1.17.7
  image.yaml
Labels: approved, lgtm, release-7.13.1, cherry-pick :cherries:
