Repository kiegroup/kie-cloud-operator, pull requests merged in 2023-08, with the labels that each got.

#904 [RHPAM-4704] - NoSuchMethodException: Method setURL not found
  pkg/controller/kieapp/defaults/defaults.go
  pkg/controller/kieapp/defaults/defaults_test.go
  rhpam-config/8.0.3/dbs/servers/external.yaml
Labels: approved, cherry-pick :cherries:, release-bamoe-8.0.4

#905 [RHPAM-4713] - Do not set URL envs if jdbcUrl property is not set
  pkg/controller/kieapp/defaults/defaults_test.go
  rhpam-config/7.13.3/dbs/servers/external.yaml
Labels: approved, needs-cherry-pick :cherries:, release-7.13.4

#906 [RHPAM-4713] - Do not set URL envs if jdbcUrl property is not set
  pkg/controller/kieapp/defaults/defaults_test.go
  rhpam-config/8.0.3/dbs/servers/external.yaml
Labels: approved, cherry-pick :cherries:

#907 Update RHPAM and BAMOE bundle for CVE respin
  deploy/olm-catalog/dev/7.13.3-5/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/dev/7.13.3-5/manifests/kieapp.crd.yaml
  deploy/olm-catalog/dev/7.13.3-5/metadata/annotations.yaml
  deploy/olm-catalog/prod/7.13.3-5/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/prod/7.13.3-5/manifests/kieapp.crd.yaml
  deploy/olm-catalog/prod/7.13.3-5/metadata/annotations.yaml
  deploy/olm-catalog/test/7.13.3-5/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/test/7.13.3-5/manifests/kieapp.crd.yaml
  deploy/olm-catalog/test/7.13.3-5/metadata/annotations.yaml
  version/version.go
Labels: approved, lgtm, release-7.13.3, needs-cherry-pick :cherries:

#908 Update RHPAM and BAMOE bundle for CVE respin
  deploy/olm-catalog/dev/8.0.3-4/manifests/bamoe-businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/dev/8.0.3-4/manifests/kieapp.crd.yaml
  deploy/olm-catalog/dev/8.0.3-4/metadata/annotations.yaml
  deploy/olm-catalog/prod/8.0.3-4/manifests/bamoe-businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/prod/8.0.3-4/manifests/kieapp.crd.yaml
  deploy/olm-catalog/prod/8.0.3-4/metadata/annotations.yaml
  deploy/olm-catalog/test/8.0.3-4/manifests/bamoe-businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/test/8.0.3-4/manifests/kieapp.crd.yaml
  deploy/olm-catalog/test/8.0.3-4/metadata/annotations.yaml
  version/version.go
Labels: approved, lgtm

#911 [KIECLOUD-731] - Bump RHPAM and BAMOE version in the next branch
  deploy/crs/v2/snippets/prior_version.yaml
  deploy/olm-catalog/dev/7.13.4-1/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/dev/7.13.4-1/manifests/kieapp.crd.yaml
  deploy/olm-catalog/dev/7.13.4-1/metadata/annotations.yaml
  deploy/olm-catalog/prod/7.13.4-1/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/prod/7.13.4-1/manifests/kieapp.crd.yaml
  deploy/olm-catalog/prod/7.13.4-1/metadata/annotations.yaml
  deploy/olm-catalog/test/7.13.4-1/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/test/7.13.4-1/manifests/kieapp.crd.yaml
  deploy/olm-catalog/test/7.13.4-1/metadata/annotations.yaml
  deploy/operator.yaml
  pkg/controller/kieapp/constants/constants.go
  rhpam-config/7.13.4/common.yaml
  rhpam-config/7.13.4/dashbuilder/rhpam-standalone-dashbuilder.yaml
  rhpam-config/7.13.4/dbs/mysql.yaml
  rhpam-config/7.13.4/dbs/pim/external.yaml
  rhpam-config/7.13.4/dbs/pim/mysql.yaml
  rhpam-config/7.13.4/dbs/pim/postgresql.yaml
  rhpam-config/7.13.4/dbs/postgresql.yaml
  rhpam-config/7.13.4/dbs/servers/external.yaml
  rhpam-config/7.13.4/dbs/servers/h2.yaml
  rhpam-config/7.13.4/dbs/servers/mysql.yaml
  rhpam-config/7.13.4/dbs/servers/postgresql.yaml
  rhpam-config/7.13.4/envs/rhdm-authoring-ha.yaml
  rhpam-config/7.13.4/envs/rhdm-authoring.yaml
  rhpam-config/7.13.4/envs/rhdm-production-immutable.yaml
  rhpam-config/7.13.4/envs/rhdm-trial.yaml
  rhpam-config/7.13.4/envs/rhpam-authoring-ha.yaml
  rhpam-config/7.13.4/envs/rhpam-authoring.yaml
  rhpam-config/7.13.4/envs/rhpam-production-immutable.yaml
  rhpam-config/7.13.4/envs/rhpam-production.yaml
  rhpam-config/7.13.4/envs/rhpam-standalone-dashbuilder.yaml
  rhpam-config/7.13.4/envs/rhpam-trial.yaml
  rhpam-config/7.13.4/jms/activemq-jms-config.yaml
  rhpam-config/7.13.4/pim/process-migration.yaml
  version/version.go
Labels: approved, release-7.13.4

#912 [KIECLOUD-731] - Bump RHPAM and BAMOE version in the next branch
  deploy/crs/v2/snippets/prior_version.yaml
  deploy/olm-catalog/dev/8.0.4-1/manifests/bamoe-businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/dev/8.0.4-1/manifests/kieapp.crd.yaml
  deploy/olm-catalog/dev/8.0.4-1/metadata/annotations.yaml
  deploy/olm-catalog/prod/8.0.4-1/manifests/bamoe-businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/prod/8.0.4-1/manifests/kieapp.crd.yaml
  deploy/olm-catalog/prod/8.0.4-1/metadata/annotations.yaml
  deploy/olm-catalog/test/8.0.4-1/manifests/bamoe-businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/test/8.0.4-1/manifests/kieapp.crd.yaml
  deploy/olm-catalog/test/8.0.4-1/metadata/annotations.yaml
  deploy/operator.yaml
  pkg/apis/app/v2/zz_generated.deepcopy.go
  pkg/controller/kieapp/constants/constants.go
  rhpam-config/8.0.4/common.yaml
  rhpam-config/8.0.4/dashbuilder/rhpam-standalone-dashbuilder.yaml
  rhpam-config/8.0.4/dbs/mysql.yaml
  rhpam-config/8.0.4/dbs/pim/external.yaml
  rhpam-config/8.0.4/dbs/pim/mysql.yaml
  rhpam-config/8.0.4/dbs/pim/postgresql.yaml
  rhpam-config/8.0.4/dbs/postgresql.yaml
  rhpam-config/8.0.4/dbs/servers/external.yaml
  rhpam-config/8.0.4/dbs/servers/h2.yaml
  rhpam-config/8.0.4/dbs/servers/mysql.yaml
  rhpam-config/8.0.4/dbs/servers/postgresql.yaml
  rhpam-config/8.0.4/envs/rhdm-authoring-ha.yaml
  rhpam-config/8.0.4/envs/rhdm-authoring.yaml
  rhpam-config/8.0.4/envs/rhdm-production-immutable.yaml
  rhpam-config/8.0.4/envs/rhdm-trial.yaml
  rhpam-config/8.0.4/envs/rhpam-authoring-ha.yaml
  rhpam-config/8.0.4/envs/rhpam-authoring.yaml
  rhpam-config/8.0.4/envs/rhpam-production-immutable.yaml
  rhpam-config/8.0.4/envs/rhpam-production.yaml
  rhpam-config/8.0.4/envs/rhpam-standalone-dashbuilder.yaml
  rhpam-config/8.0.4/envs/rhpam-trial.yaml
  rhpam-config/8.0.4/jms/activemq-jms-config.yaml
  rhpam-config/8.0.4/pim/process-migration.yaml
  version/version.go
Labels: approved

#914 [RHPAM-4754] - Unable to set direct-verification=true individually in…
  deploy/crds/kieapp.crd.yaml
  deploy/olm-catalog/dev/8.0.4-1/manifests/bamoe-businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/dev/8.0.4-1/manifests/kieapp.crd.yaml
  deploy/olm-catalog/prod/8.0.4-1/manifests/bamoe-businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/prod/8.0.4-1/manifests/kieapp.crd.yaml
  deploy/olm-catalog/test/8.0.4-1/manifests/bamoe-businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/test/8.0.4-1/manifests/kieapp.crd.yaml
  pkg/apis/app/v2/kieapp_types.go
  pkg/apis/app/v2/zz_generated.deepcopy.go
  pkg/controller/kieapp/defaults/auth_test.go
  pkg/controller/kieapp/defaults/defaults.go
  pkg/controller/kieapp/defaults/upgrade_test.go
  rhpam-config/8.0.4/common.yaml
  rhpam-config/8.0.4/dashbuilder/rhpam-standalone-dashbuilder.yaml
Labels: approved, release-bamoe-8.0.4

#913 [RHPAM-4754] - Unable to set direct-verification=true individually in LDAP realm by operator
  deploy/crds/kieapp.crd.yaml
  deploy/olm-catalog/dev/7.13.4-1/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/dev/7.13.4-1/manifests/kieapp.crd.yaml
  deploy/olm-catalog/prod/7.13.4-1/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/prod/7.13.4-1/manifests/kieapp.crd.yaml
  deploy/olm-catalog/test/7.13.4-1/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/test/7.13.4-1/manifests/kieapp.crd.yaml
  pkg/apis/app/v2/kieapp_types.go
  pkg/controller/kieapp/defaults/auth_test.go
  pkg/controller/kieapp/defaults/defaults.go
  pkg/controller/kieapp/defaults/upgrade_test.go
  rhpam-config/7.13.4/common.yaml
  rhpam-config/7.13.4/dashbuilder/rhpam-standalone-dashbuilder.yaml
Labels: approved, needs-cherry-pick :cherries:, release-7.13.4

#915 [release-v7.13.x-blue][KIECLOUD-732] update bamoe subscription
  deploy/olm-catalog/dev/8.0.3-4/manifests/bamoe-businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/prod/8.0.3-4/manifests/bamoe-businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/test/8.0.3-4/manifests/bamoe-businessautomation-operator.clusterserviceversion.yaml
  tools/csv-gen/csv-gen.go
Labels: approved

#916 [release-v7.13.x-blue-next][KIECLOUD-732] update bamoe subscription
  deploy/olm-catalog/dev/8.0.3-4/manifests/bamoe-businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/prod/8.0.3-4/manifests/bamoe-businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/test/8.0.3-4/manifests/bamoe-businessautomation-operator.clusterserviceversion.yaml
  tools/csv-gen/csv-gen.go
Labels: approved
