Repository kiegroup/kie-cloud-operator, pull requests merged in 2023-02, with the labels that each got.

#844 [KIECLOUD-687] - Prepare the BAMOE branches for the 8.0.3 release
  deploy/crs/v2/snippets/prior_version.yaml
  deploy/olm-catalog/dev/8.0.3-1/manifests/bamoe-businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/dev/8.0.3-1/manifests/kieapp.crd.yaml
  deploy/olm-catalog/dev/8.0.3-1/metadata/annotations.yaml
  deploy/olm-catalog/prod/8.0.3-1/manifests/bamoe-businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/prod/8.0.3-1/manifests/kieapp.crd.yaml
  deploy/olm-catalog/prod/8.0.3-1/metadata/annotations.yaml
  deploy/olm-catalog/test/8.0.3-1/manifests/bamoe-businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/test/8.0.3-1/manifests/kieapp.crd.yaml
  deploy/olm-catalog/test/8.0.3-1/metadata/annotations.yaml
  deploy/operator.yaml
  pkg/apis/app/v2/zz_generated.deepcopy.go
  pkg/controller/kieapp/constants/constants.go
  rhpam-config/8.0.3/common.yaml
  rhpam-config/8.0.3/dashbuilder/rhpam-standalone-dashbuilder.yaml
  rhpam-config/8.0.3/dbs/mysql.yaml
  rhpam-config/8.0.3/dbs/pim/external.yaml
  rhpam-config/8.0.3/dbs/pim/mysql.yaml
  rhpam-config/8.0.3/dbs/pim/postgresql.yaml
  rhpam-config/8.0.3/dbs/postgresql.yaml
  rhpam-config/8.0.3/dbs/servers/external.yaml
  rhpam-config/8.0.3/dbs/servers/h2.yaml
  rhpam-config/8.0.3/dbs/servers/mysql.yaml
  rhpam-config/8.0.3/dbs/servers/postgresql.yaml
  rhpam-config/8.0.3/envs/rhdm-authoring-ha.yaml
  rhpam-config/8.0.3/envs/rhdm-authoring.yaml
  rhpam-config/8.0.3/envs/rhdm-production-immutable.yaml
  rhpam-config/8.0.3/envs/rhdm-trial.yaml
  rhpam-config/8.0.3/envs/rhpam-authoring-ha.yaml
  rhpam-config/8.0.3/envs/rhpam-authoring.yaml
  rhpam-config/8.0.3/envs/rhpam-production-immutable.yaml
  rhpam-config/8.0.3/envs/rhpam-production.yaml
  rhpam-config/8.0.3/envs/rhpam-standalone-dashbuilder.yaml
  rhpam-config/8.0.3/envs/rhpam-trial.yaml
  rhpam-config/8.0.3/jms/activemq-jms-config.yaml
  rhpam-config/8.0.3/pim/process-migration.yaml
  version/version.go
Labels: approved, release-bamoe-8.0.x

#843 [KIECLOUD-659] Added first version of build-osbs.sh script for nightl…
  hack/build-osbs.sh
  hack/go-build.sh
  hack/image-osbs.patch
Labels: approved, lgtm

#845 [KIECLOUD-660] Add nightly build for bamoe-operator
  hack/build-osbs.sh
  hack/go-build.sh
  hack/image-osbs.patch
Labels: approved, lgtm

#847 [KIECLOUD-692] - Update the target dist-git branch with the new ones
  Makefile
  hack/build-osbs.sh
  hack/go-build.sh
  hack/image-osbs.patch
  image.yaml
Labels: approved

#848 [KIECLOUD-692] - Update the target dist-git branch with the new ones
  Makefile
  hack/build-osbs.sh
  hack/go-build.sh
  hack/image-osbs.patch
Labels: approved
