Repository kiegroup/kie-cloud-operator, pull requests merged in 2023-04, with the labels that each got.

#877 [KIECLOUD-711] - Add retry mechanism when trying to create the kerber…
  hack/build-osbs.sh
Labels: approved, release-7.13.3, needs-cherry-pick :cherries:

#878 [KIECLOUD-711] - Add retry mechanism when trying to create the kerber…
  hack/build-osbs.sh
Labels: approved, cherry-pick :cherries:, release-bamoe-8.0.3

#883 [release-v7.13.x-blue-next][KIECLOUD-707] - Enable dependabot for rel…
  .github/dependabot.yml
Labels: approved, lgtm, release-bamoe-8.0.x

#884 [KIECLOUD-716] - Prepare RHPAM BA Operator for 7.13.3 release
  deploy/crs/v2/snippets/prior_version.yaml
  deploy/olm-catalog/dev/7.13.3-1/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/dev/7.13.3-1/manifests/kieapp.crd.yaml
  deploy/olm-catalog/dev/7.13.3-1/metadata/annotations.yaml
  deploy/olm-catalog/prod/7.13.3-1/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/prod/7.13.3-1/manifests/kieapp.crd.yaml
  deploy/olm-catalog/prod/7.13.3-1/metadata/annotations.yaml
  deploy/olm-catalog/test/7.13.3-1/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/test/7.13.3-1/manifests/kieapp.crd.yaml
  deploy/olm-catalog/test/7.13.3-1/metadata/annotations.yaml
  deploy/operator.yaml
  pkg/controller/kieapp/constants/constants.go
  rhpam-config/7.13.3/common.yaml
  rhpam-config/7.13.3/dashbuilder/rhpam-standalone-dashbuilder.yaml
  rhpam-config/7.13.3/dbs/mysql.yaml
  rhpam-config/7.13.3/dbs/pim/external.yaml
  rhpam-config/7.13.3/dbs/pim/mysql.yaml
  rhpam-config/7.13.3/dbs/pim/postgresql.yaml
  rhpam-config/7.13.3/dbs/postgresql.yaml
  rhpam-config/7.13.3/dbs/servers/external.yaml
  rhpam-config/7.13.3/dbs/servers/h2.yaml
  rhpam-config/7.13.3/dbs/servers/mysql.yaml
  rhpam-config/7.13.3/dbs/servers/postgresql.yaml
  rhpam-config/7.13.3/envs/rhdm-authoring-ha.yaml
  rhpam-config/7.13.3/envs/rhdm-authoring.yaml
  rhpam-config/7.13.3/envs/rhdm-production-immutable.yaml
  rhpam-config/7.13.3/envs/rhdm-trial.yaml
  rhpam-config/7.13.3/envs/rhpam-authoring-ha.yaml
  rhpam-config/7.13.3/envs/rhpam-authoring.yaml
  rhpam-config/7.13.3/envs/rhpam-production-immutable.yaml
  rhpam-config/7.13.3/envs/rhpam-production.yaml
  rhpam-config/7.13.3/envs/rhpam-standalone-dashbuilder.yaml
  rhpam-config/7.13.3/envs/rhpam-trial.yaml
  rhpam-config/7.13.3/jms/activemq-jms-config.yaml
  rhpam-config/7.13.3/pim/process-migration.yaml
  version/version.go
Labels: approved, lgtm, release-7.13.3

#885 add rgdoliveira as part of reviewers
  OWNERS
Labels: lgtm

#887 [KIECLOUD-716] - remove old configuration files
  rhpam-config/7.13.1/common.yaml
  rhpam-config/7.13.1/dashbuilder/rhpam-standalone-dashbuilder.yaml
  rhpam-config/7.13.1/dbs/mysql.yaml
  rhpam-config/7.13.1/dbs/pim/external.yaml
  rhpam-config/7.13.1/dbs/pim/mysql.yaml
  rhpam-config/7.13.1/dbs/pim/postgresql.yaml
  rhpam-config/7.13.1/dbs/postgresql.yaml
  rhpam-config/7.13.1/dbs/servers/external.yaml
  rhpam-config/7.13.1/dbs/servers/h2.yaml
  rhpam-config/7.13.1/dbs/servers/mysql.yaml
  rhpam-config/7.13.1/dbs/servers/postgresql.yaml
  rhpam-config/7.13.1/envs/rhdm-authoring-ha.yaml
  rhpam-config/7.13.1/envs/rhdm-authoring.yaml
  rhpam-config/7.13.1/envs/rhdm-production-immutable.yaml
  rhpam-config/7.13.1/envs/rhdm-trial.yaml
  rhpam-config/7.13.1/envs/rhpam-authoring-ha.yaml
  rhpam-config/7.13.1/envs/rhpam-authoring.yaml
  rhpam-config/7.13.1/envs/rhpam-production-immutable.yaml
  rhpam-config/7.13.1/envs/rhpam-production.yaml
  rhpam-config/7.13.1/envs/rhpam-standalone-dashbuilder.yaml
  rhpam-config/7.13.1/envs/rhpam-trial.yaml
  rhpam-config/7.13.1/jms/activemq-jms-config.yaml
  rhpam-config/7.13.1/pim/process-migration.yaml
Labels: approved, lgtm

#889 [KIECLOUD-716] - Align the components version
  deploy/olm-catalog/dev/7.13.3-1/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/prod/7.13.3-1/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/test/7.13.3-1/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/operator.yaml
  pkg/controller/kieapp/constants/constants.go
Labels: approved, lgtm

#886 add rgdoliveira as part of reviewers
  OWNERS
Labels: approved, lgtm

#892 [release-v7.13.x-blue-next] add rgdoliveira as part of reviewers
  OWNERS
Labels: approved, lgtm
