Repository kiegroup/kie-cloud-operator, pull requests merged in 2023-03, with the labels that each got.

#853 [KIECLOUD][RHPAM-4609] Setting up Cachito tool.
  image-prod.yaml
  modules/builder-prod/install
  modules/builder-prod/module.yaml
Labels: approved, lgtm

#854 [release-v7.13.x-blue][KIECLOUD][RHPAM-4609] Setting up Cachito tool.
  image-prod.yaml
  modules/builder-prod/install
  modules/builder-prod/module.yaml
Labels: approved, lgtm

#856 KIECLOUD-659 - Add nightly build for ba-operator /2
  hack/build-osbs.sh
  hack/go-build.sh
  hack/image-osbs.patch
  modules/builder-prod/install
Labels: approved, lgtm

#855 [KIECLOUD-696] - Unable to upgrade BA operator from version 7.13.1-2 …
  deploy/olm-catalog/dev/7.13.2-1/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/dev/7.13.2-2/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/dev/7.13.2-2/manifests/kieapp.crd.yaml
  deploy/olm-catalog/dev/7.13.2-2/metadata/annotations.yaml
  deploy/olm-catalog/prod/7.13.2-1/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/prod/7.13.2-2/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/prod/7.13.2-2/manifests/kieapp.crd.yaml
  deploy/olm-catalog/prod/7.13.2-2/metadata/annotations.yaml
  deploy/olm-catalog/test/7.13.2-1/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/test/7.13.2-2/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/test/7.13.2-2/manifests/kieapp.crd.yaml
  deploy/olm-catalog/test/7.13.2-2/metadata/annotations.yaml
  version/version.go
Labels: approved, lgtm

#860 [KIECLOUD-699] - Override the commit reference in the rhpam/bamoe ope…
  Makefile
  hack/build-osbs.sh
  hack/go-build.sh
Labels: approved, lgtm

#862 [KIECLOUD-697] - Bump BAMOE operator bundle version for CVE respin
  deploy/olm-catalog/dev/8.0.2-2/manifests/bamoe-businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/dev/8.0.2-2/manifests/kieapp.crd.yaml
  deploy/olm-catalog/dev/8.0.2-2/metadata/annotations.yaml
  deploy/olm-catalog/prod/8.0.2-2/manifests/bamoe-businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/prod/8.0.2-2/manifests/kieapp.crd.yaml
  deploy/olm-catalog/prod/8.0.2-2/metadata/annotations.yaml
  deploy/olm-catalog/test/8.0.2-2/manifests/bamoe-businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/test/8.0.2-2/manifests/kieapp.crd.yaml
  deploy/olm-catalog/test/8.0.2-2/metadata/annotations.yaml
  version/version.go
Labels: approved

#863 [KIECLOUD-696] - update main from 7.13.2-1 update
  deploy/olm-catalog/dev/7.13.2-1/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/prod/7.13.2-1/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/test/7.13.2-1/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved

#864 [KIECLOUD-701] - Respin BA operator due CVE-2022-47629
  deploy/olm-catalog/dev/7.13.2-2/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/dev/7.13.2-2/manifests/kieapp.crd.yaml
  deploy/olm-catalog/dev/7.13.2-2/metadata/annotations.yaml
  deploy/olm-catalog/prod/7.13.2-2/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/prod/7.13.2-2/manifests/kieapp.crd.yaml
  deploy/olm-catalog/prod/7.13.2-2/metadata/annotations.yaml
  deploy/olm-catalog/test/7.13.2-2/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/test/7.13.2-2/manifests/kieapp.crd.yaml
  deploy/olm-catalog/test/7.13.2-2/metadata/annotations.yaml
  version/version.go
Labels: approved, lgtm

#866 [KIECLOUD-694] - fix osbs-builder-user assignment from krb principal
  hack/build-osbs.sh
Labels: approved, release-7.13.3, needs-cherry-pick :cherries:

#868 [KIECLOUD-704] - BA Operator - Upgrade OCP EUS to version 4.10
  deploy/olm-catalog/dev/7.13.2-2/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/prod/7.13.2-2/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/test/7.13.2-2/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/operator.yaml
  image-bundle.yaml
  pkg/controller/kieapp/constants/constants.go
Labels: approved, lgtm

#869 [KIECLOUD-705] - BAMOE BA Operator - Upgrade OCP EUS to version 4.10
  deploy/olm-catalog/dev/8.0.3-1/manifests/bamoe-businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/prod/8.0.3-1/manifests/bamoe-businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/test/8.0.3-1/manifests/bamoe-businessautomation-operator.clusterserviceversion.yaml
  deploy/operator.yaml
  image-bundle.yaml
  pkg/controller/kieapp/constants/constants.go
Labels: approved, lgtm, release-bamoe-8.0.3

#872 [KIECLOUD-708] - Prepare RHPAM Operator for CVEs respin
  deploy/olm-catalog/dev/7.13.2-3/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/dev/7.13.2-3/manifests/kieapp.crd.yaml
  deploy/olm-catalog/dev/7.13.2-3/metadata/annotations.yaml
  deploy/olm-catalog/prod/7.13.2-3/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/prod/7.13.2-3/manifests/kieapp.crd.yaml
  deploy/olm-catalog/prod/7.13.2-3/metadata/annotations.yaml
  deploy/olm-catalog/test/7.13.2-3/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/test/7.13.2-3/manifests/kieapp.crd.yaml
  deploy/olm-catalog/test/7.13.2-3/metadata/annotations.yaml
  version/version.go
Labels: approved, release-7.13.2

#873 [KIECLOUD-708] - Prepare RHPAM Operator for CVEs respin
  deploy/olm-catalog/dev/7.13.2-3/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/dev/7.13.2-3/manifests/kieapp.crd.yaml
  deploy/olm-catalog/dev/7.13.2-3/metadata/annotations.yaml
  deploy/olm-catalog/prod/7.13.2-3/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/prod/7.13.2-3/manifests/kieapp.crd.yaml
  deploy/olm-catalog/prod/7.13.2-3/metadata/annotations.yaml
  deploy/olm-catalog/test/7.13.2-3/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/test/7.13.2-3/manifests/kieapp.crd.yaml
  deploy/olm-catalog/test/7.13.2-3/metadata/annotations.yaml
  version/version.go
Labels: approved, release-7.13.3

#874 [KIECLOUD-708] - Prepare BAMOE Operator for CVEs respin
  deploy/olm-catalog/dev/8.0.2-3/manifests/bamoe-businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/dev/8.0.2-3/manifests/kieapp.crd.yaml
  deploy/olm-catalog/dev/8.0.2-3/metadata/annotations.yaml
  deploy/olm-catalog/prod/8.0.2-3/manifests/bamoe-businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/prod/8.0.2-3/manifests/kieapp.crd.yaml
  deploy/olm-catalog/prod/8.0.2-3/metadata/annotations.yaml
  deploy/olm-catalog/test/8.0.2-3/manifests/bamoe-businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/test/8.0.2-3/manifests/kieapp.crd.yaml
  deploy/olm-catalog/test/8.0.2-3/metadata/annotations.yaml
  pkg/apis/app/v2/zz_generated.deepcopy.go
  version/version.go
Labels: approved, release-bamoe-8.0.2
