Repository kiegroup/kie-cloud-operator, pull requests merged in 2023-09, with the labels that each got.

#920 [release-v7.13.x-blue][KIECLOUD-732] add missing subscription for BAMOE 8.0.4-1 operator
  deploy/olm-catalog/dev/8.0.4-1/manifests/bamoe-businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/prod/8.0.4-1/manifests/bamoe-businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/test/8.0.4-1/manifests/bamoe-businessautomation-operator.clusterserviceversion.yaml
Labels: lgtm

#921 [release-v7.13.x-blue-next][KIECLOUD-732] add missing subscription for BAMOE 8.0.4-1 operator
  deploy/olm-catalog/dev/8.0.4-1/manifests/bamoe-businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/prod/8.0.4-1/manifests/bamoe-businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/test/8.0.4-1/manifests/bamoe-businessautomation-operator.clusterserviceversion.yaml
Labels: lgtm

#919 [KIECLOUD-735] - Prepare RHPAM repositories for 7.13.5 release
  deploy/crs/v2/snippets/prior_version.yaml
  deploy/olm-catalog/dev/7.13.5-1/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/dev/7.13.5-1/manifests/kieapp.crd.yaml
  deploy/olm-catalog/dev/7.13.5-1/metadata/annotations.yaml
  deploy/olm-catalog/prod/7.13.5-1/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/prod/7.13.5-1/manifests/kieapp.crd.yaml
  deploy/olm-catalog/prod/7.13.5-1/metadata/annotations.yaml
  deploy/olm-catalog/test/7.13.5-1/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/test/7.13.5-1/manifests/kieapp.crd.yaml
  deploy/olm-catalog/test/7.13.5-1/metadata/annotations.yaml
  deploy/operator.yaml
  pkg/controller/kieapp/constants/constants.go
  pkg/controller/kieapp/defaults/upgrade_test.go
  rhpam-config/7.13.5/common.yaml
  rhpam-config/7.13.5/dashbuilder/rhpam-standalone-dashbuilder.yaml
  rhpam-config/7.13.5/dbs/mysql.yaml
  rhpam-config/7.13.5/dbs/pim/external.yaml
  rhpam-config/7.13.5/dbs/pim/mysql.yaml
  rhpam-config/7.13.5/dbs/pim/postgresql.yaml
  rhpam-config/7.13.5/dbs/postgresql.yaml
  rhpam-config/7.13.5/dbs/servers/external.yaml
  rhpam-config/7.13.5/dbs/servers/h2.yaml
  rhpam-config/7.13.5/dbs/servers/mysql.yaml
  rhpam-config/7.13.5/dbs/servers/postgresql.yaml
  rhpam-config/7.13.5/envs/rhdm-authoring-ha.yaml
  rhpam-config/7.13.5/envs/rhdm-authoring.yaml
  rhpam-config/7.13.5/envs/rhdm-production-immutable.yaml
  rhpam-config/7.13.5/envs/rhdm-trial.yaml
  rhpam-config/7.13.5/envs/rhpam-authoring-ha.yaml
  rhpam-config/7.13.5/envs/rhpam-authoring.yaml
  rhpam-config/7.13.5/envs/rhpam-production-immutable.yaml
  rhpam-config/7.13.5/envs/rhpam-production.yaml
  rhpam-config/7.13.5/envs/rhpam-standalone-dashbuilder.yaml
  rhpam-config/7.13.5/envs/rhpam-trial.yaml
  rhpam-config/7.13.5/jms/activemq-jms-config.yaml
  rhpam-config/7.13.5/pim/process-migration.yaml
  version/version.go
Labels: approved, release-7.13.5

#922 [release-v7.13.x] Update RHPAM bundle for CVE respin
  deploy/olm-catalog/dev/7.13.4-2/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/dev/7.13.4-2/manifests/kieapp.crd.yaml
  deploy/olm-catalog/dev/7.13.4-2/metadata/annotations.yaml
  deploy/olm-catalog/dev/manifests/kieapp.crd.yaml
  deploy/olm-catalog/prod/7.13.4-2/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/prod/7.13.4-2/manifests/kieapp.crd.yaml
  deploy/olm-catalog/prod/7.13.4-2/metadata/annotations.yaml
  deploy/olm-catalog/prod/manifests/kieapp.crd.yaml
  deploy/olm-catalog/test/7.13.4-2/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/test/7.13.4-2/manifests/kieapp.crd.yaml
  deploy/olm-catalog/test/7.13.4-2/metadata/annotations.yaml
  deploy/olm-catalog/test/manifests/kieapp.crd.yaml
  version/version.go
Labels: needs-cherry-pick :cherries:, release-7.13.4

#924 [release-v7.13.x] remove kieapp.cdr files that were wrongly added outside tag directory
  deploy/olm-catalog/dev/manifests/kieapp.crd.yaml
  deploy/olm-catalog/prod/manifests/kieapp.crd.yaml
  deploy/olm-catalog/test/manifests/kieapp.crd.yaml
Labels: approved, lgtm
