Repository kiegroup/kie-cloud-operator, pull requests merged in 2025-03, with the labels that each got.

#991 Fix replaces by in 8.0.7-1
  deploy/olm-catalog/dev/8.0.7-1/manifests/bamoe-businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/prod/8.0.7-1/manifests/bamoe-businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/test/8.0.7-1/manifests/bamoe-businessautomation-operator.clusterserviceversion.yaml
Labels: approved, lgtm

#992 Prepare 8.0.7.CR1 config
  deploy/olm-catalog/dev/8.0.6-4/manifests/bamoe-businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/dev/8.0.6-4/manifests/kieapp.crd.yaml
  deploy/olm-catalog/dev/8.0.6-4/metadata/annotations.yaml
  deploy/olm-catalog/dev/8.0.7-1/manifests/bamoe-businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/prod/8.0.6-4/manifests/bamoe-businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/prod/8.0.6-4/manifests/kieapp.crd.yaml
  deploy/olm-catalog/prod/8.0.6-4/metadata/annotations.yaml
  deploy/olm-catalog/prod/8.0.7-1/manifests/bamoe-businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/test/8.0.6-4/manifests/bamoe-businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/test/8.0.6-4/manifests/kieapp.crd.yaml
  deploy/olm-catalog/test/8.0.6-4/metadata/annotations.yaml
  deploy/olm-catalog/test/8.0.7-1/manifests/bamoe-businessautomation-operator.clusterserviceversion.yaml
  version/version.go
Labels: approved, lgtm

#995 [release-v7.13.x] adding Saumya as part of OWNERS file
  OWNERS
Labels: approved

#996 adding Saumya as part of OWNERS file
  OWNERS
Labels: approved

#993 [release-v7.13.x] Update RHPAM bundle for CVE respin (CVE-2025-1244)
  deploy/olm-catalog/dev/7.13.5-11/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/dev/7.13.5-11/manifests/kieapp.crd.yaml
  deploy/olm-catalog/dev/7.13.5-11/metadata/annotations.yaml
  deploy/olm-catalog/prod/7.13.5-11/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/prod/7.13.5-11/manifests/kieapp.crd.yaml
  deploy/olm-catalog/prod/7.13.5-11/metadata/annotations.yaml
  deploy/olm-catalog/test/7.13.5-11/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/test/7.13.5-11/manifests/kieapp.crd.yaml
  deploy/olm-catalog/test/7.13.5-11/metadata/annotations.yaml
  version/version.go
Labels: approved

#990 [DBACLD-168351] KIE app operators remain in the provisioning state
  pkg/controller/kieapp/deploy_ui.go
Labels: approved, lgtm, ok-to-test

#997 Update RHPAM bundle for CVE respin (CVE-2024-56171,CVE-2025-24928)
  deploy/olm-catalog/dev/7.13.5-12/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/dev/7.13.5-12/manifests/kieapp.crd.yaml
  deploy/olm-catalog/dev/7.13.5-12/metadata/annotations.yaml
  deploy/olm-catalog/prod/7.13.5-12/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/prod/7.13.5-12/manifests/kieapp.crd.yaml
  deploy/olm-catalog/prod/7.13.5-12/metadata/annotations.yaml
  deploy/olm-catalog/test/7.13.5-12/manifests/businessautomation-operator.clusterserviceversion.yaml
  deploy/olm-catalog/test/7.13.5-12/manifests/kieapp.crd.yaml
  deploy/olm-catalog/test/7.13.5-12/metadata/annotations.yaml
  version/version.go
Labels: approved
